**Importing library**

In [1]:
import pandas as pd 
import numpy as np 
import os

**Display Settings**

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

**File URL**

In [3]:
path1 ="../raw data/Metropolitan Cities - Cyber Crimes 2024(vol2-9b.1).xlsx"

**Loading URL Excel File**

In [4]:
df = pd.read_excel(path1, header=2)

# header = 2 as first 2 coloums are just table name and 

df.head()

,SL,City,2022,2023,2024,Actual Population (Lakhs) 2011,Rate of Total Cyber Crimes (2024),Chargesheeting Rate (2024)
0,1,Ahmedabad (Gujarat),261.0,246.0,396.0,63.5,6.2,48.6
1,2,Bengaluru (Karnataka),9940.0,17631.0,17561.0,85.0,206.6,24.2
2,3,Chennai (Tamil Nadu),271.0,1352.0,1882.0,87.0,21.6,41.2
3,4,Coimbatore (Tamil Nadu),68.0,207.0,300.0,21.5,13.9,17.9
4,5,Delhi City,685.0,407.0,404.0,163.1,2.5,77.8

**Inspect Raw Data**

In [5]:
df.shape

(21, 8)

In [6]:
df.columns

Index(['SL', 'City', '2022', '2023', '2024', 'Actual Population (Lakhs) 2011',
       'Rate of Total Cyber Crimes (2024)', 'Chargesheeting Rate (2024)'],
      dtype='object')

In [7]:
df.head()

,SL,City,2022,2023,2024,Actual Population (Lakhs) 2011,Rate of Total Cyber Crimes (2024),Chargesheeting Rate (2024)
0,1,Ahmedabad (Gujarat),261.0,246.0,396.0,63.5,6.2,48.6
1,2,Bengaluru (Karnataka),9940.0,17631.0,17561.0,85.0,206.6,24.2
2,3,Chennai (Tamil Nadu),271.0,1352.0,1882.0,87.0,21.6,41.2
3,4,Coimbatore (Tamil Nadu),68.0,207.0,300.0,21.5,13.9,17.9
4,5,Delhi City,685.0,407.0,404.0,163.1,2.5,77.8

**Cleaning Column Names**

In [8]:
df.columns = (
    df.columns.astype(str)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

df.columns

Index(['sl', 'city', '2022', '2023', '2024', 'actual_population_(lakhs)_2011',
       'rate_of_total_cyber_crimes_(2024)', 'chargesheeting_rate_(2024)'],
      dtype='object')

**Removing Empty Rows**

In [9]:
df.dropna(how='all', inplace=True)

df.shape

(21, 8)

**Removing Total Rows** -
Goverment Datasets usually contains rows like total, grand total, sub total

In [10]:
df = df[
    ~df['city']
    .astype(str)
    .str.contains('total', case=False, na=False)
]

**Droping SL Column** - No Analytical value , No business Meaning

In [11]:
df.drop(columns=['sl'], inplace=True)

In [12]:
df.columns

Index(['city', '2022', '2023', '2024', 'actual_population_(lakhs)_2011',
       'rate_of_total_cyber_crimes_(2024)', 'chargesheeting_rate_(2024)'],
      dtype='object')

**Melting Columns**

In [13]:
df_long = df.melt(
    id_vars=[
        'city',
        'actual_population_(lakhs)_2011',
        'rate_of_total_cyber_crimes_(2024)',
        'chargesheeting_rate_(2024)'
    ],

    value_vars=[
        '2022',
        '2023',
        '2024'
    ],

    var_name='year',
    value_name='cases'
)

df_long['category'] = 'Cybercrime'

In [14]:
df_long

,city,actual_population_(lakhs)_2011,rate_of_total_cyber_crimes_(2024),chargesheeting_rate_(2024),year,cases,category
0,Ahmedabad (Gujarat),63.5,6.2,48.6,2022,261.0,Cybercrime
1,Bengaluru (Karnataka),85.0,206.6,24.2,2022,9940.0,Cybercrime
2,Chennai (Tamil Nadu),87.0,21.6,41.2,2022,271.0,Cybercrime
3,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2022,68.0,Cybercrime
4,Delhi City,163.1,2.5,77.8,2022,685.0,Cybercrime
5,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2022,626.0,Cybercrime
6,Hyderabad (Telangana),77.5,51.7,12.9,2022,4436.0,Cybercrime
7,Indore (Madhya Pradesh),21.7,2.6,82.4,2022,47.0,Cybercrime
8,Jaipur (Rajasthan),30.7,6.4,33.2,2022,310.0,Cybercrime
9,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2022,541.0,Cybercrime
10,Kochi (Kerala),21.2,9.5,55.4,2022,96.0,Cybercrime
11,Kolkata (West Bengal),141.1,0.1,95.6,2022,75.0,Cybercrime
12,Kozhikode (Kerala),20.3,5.2,39.5,2022,45.0,Cybercrime
13,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2022,1134.0,Cybercrime
14,Mumbai (Maharashtra),184.1,26.8,30.8,2022,4724.0,Cybercrime
15,Nagpur (Maharashtra),25.0,10.1,79.6,2022,211.0,Cybercrime
16,Patna (Bihar),20.5,31.4,100.0,2022,222.0,Cybercrime
17,Pune (Maharashtra),50.5,29.8,26.6,2022,357.0,Cybercrime
18,Surat (Gujarat),45.8,5.8,66.7,2022,371.0,Cybercrime
19,NaN,NaN,NaN,NaN,2022,NaN,Cybercrime
20,Ahmedabad (Gujarat),63.5,6.2,48.6,2023,246.0,Cybercrime
21,Bengaluru (Karnataka),85.0,206.6,24.2,2023,17631.0,Cybercrime
22,Chennai (Tamil Nadu),87.0,21.6,41.2,2023,1352.0,Cybercrime
23,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2023,207.0,Cybercrime
24,Delhi City,163.1,2.5,77.8,2023,407.0,Cybercrime
25,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2023,880.0,Cybercrime
26,Hyderabad (Telangana),77.5,51.7,12.9,2023,4855.0,Cybercrime
27,Indore (Madhya Pradesh),21.7,2.6,82.4,2023,86.0,Cybercrime
28,Jaipur (Rajasthan),30.7,6.4,33.2,2023,551.0,Cybercrime
29,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2023,481.0,Cybercrime
30,Kochi (Kerala),21.2,9.5,55.4,2023,112.0,Cybercrime
31,Kolkata (West Bengal),141.1,0.1,95.6,2023,21.0,Cybercrime
32,Kozhikode (Kerala),20.3,5.2,39.5,2023,114.0,Cybercrime
33,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2023,1453.0,Cybercrime
34,Mumbai (Maharashtra),184.1,26.8,30.8,2023,4131.0,Cybercrime
35,Nagpur (Maharashtra),25.0,10.1,79.6,2023,309.0,Cybercrime
36,Patna (Bihar),20.5,31.4,100.0,2023,235.0,Cybercrime
37,Pune (Maharashtra),50.5,29.8,26.6,2023,487.0,Cybercrime
38,Surat (Gujarat),45.8,5.8,66.7,2023,397.0,Cybercrime
39,NaN,NaN,NaN,NaN,2023,NaN,Cybercrime
40,Ahmedabad (Gujarat),63.5,6.2,48.6,2024,396.0,Cybercrime
41,Bengaluru (Karnataka),85.0,206.6,24.2,2024,17561.0,Cybercrime
42,Chennai (Tamil Nadu),87.0,21.6,41.2,2024,1882.0,Cybercrime
43,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2024,300.0,Cybercrime
44,Delhi City,163.1,2.5,77.8,2024,404.0,Cybercrime
45,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2024,479.0,Cybercrime
46,Hyderabad (Telangana),77.5,51.7,12.9,2024,4009.0,Cybercrime
47,Indore (Madhya Pradesh),21.7,2.6,82.4,2024,57.0,Cybercrime
48,Jaipur (Rajasthan),30.7,6.4,33.2,2024,197.0,Cybercrime
49,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2024,449.0,Cybercrime
50,Kochi (Kerala),21.2,9.5,55.4,2024,201.0,Cybercrime
51,Kolkata (West Bengal),141.1,0.1,95.6,2024,21.0,Cybercrime
52,Kozhikode (Kerala),20.3,5.2,39.5,2024,106.0,Cybercrime
53,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2024,1292.0,Cybercrime
54,Mumbai (Maharashtra),184.1,26.8,30.8,2024,4939.0,Cybercrime
55,Nagpur (Maharashtra),25.0,10.1,79.6,2024,253.0,Cybercrime
56,Patna (Bihar),20.5,31.4,100.0,2024,642.0,Cybercrime
57,Pune (Maharashtra),50.5,29.8,26.6,2024,1504.0,Cybercrime
58,Surat (Gujarat),45.8,5.8,66.7,2024,266.0,Cybercrime
59,NaN,NaN,NaN,NaN,2024,NaN,Cybercrime

In [15]:
df_long.rename(columns={

    'actual_population_(lakhs)_2011':
        'population_lakhs_2011',

    'rate_of_total_cyber_crimes_(2024)':
        'crime_rate_2024',

    'chargesheeting_rate_(2024)':
        'chargesheeting_rate_2024'

}, inplace=True)

In [16]:
df_long

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category
0,Ahmedabad (Gujarat),63.5,6.2,48.6,2022,261.0,Cybercrime
1,Bengaluru (Karnataka),85.0,206.6,24.2,2022,9940.0,Cybercrime
2,Chennai (Tamil Nadu),87.0,21.6,41.2,2022,271.0,Cybercrime
3,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2022,68.0,Cybercrime
4,Delhi City,163.1,2.5,77.8,2022,685.0,Cybercrime
5,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2022,626.0,Cybercrime
6,Hyderabad (Telangana),77.5,51.7,12.9,2022,4436.0,Cybercrime
7,Indore (Madhya Pradesh),21.7,2.6,82.4,2022,47.0,Cybercrime
8,Jaipur (Rajasthan),30.7,6.4,33.2,2022,310.0,Cybercrime
9,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2022,541.0,Cybercrime
10,Kochi (Kerala),21.2,9.5,55.4,2022,96.0,Cybercrime
11,Kolkata (West Bengal),141.1,0.1,95.6,2022,75.0,Cybercrime
12,Kozhikode (Kerala),20.3,5.2,39.5,2022,45.0,Cybercrime
13,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2022,1134.0,Cybercrime
14,Mumbai (Maharashtra),184.1,26.8,30.8,2022,4724.0,Cybercrime
15,Nagpur (Maharashtra),25.0,10.1,79.6,2022,211.0,Cybercrime
16,Patna (Bihar),20.5,31.4,100.0,2022,222.0,Cybercrime
17,Pune (Maharashtra),50.5,29.8,26.6,2022,357.0,Cybercrime
18,Surat (Gujarat),45.8,5.8,66.7,2022,371.0,Cybercrime
19,NaN,NaN,NaN,NaN,2022,NaN,Cybercrime
20,Ahmedabad (Gujarat),63.5,6.2,48.6,2023,246.0,Cybercrime
21,Bengaluru (Karnataka),85.0,206.6,24.2,2023,17631.0,Cybercrime
22,Chennai (Tamil Nadu),87.0,21.6,41.2,2023,1352.0,Cybercrime
23,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2023,207.0,Cybercrime
24,Delhi City,163.1,2.5,77.8,2023,407.0,Cybercrime
25,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2023,880.0,Cybercrime
26,Hyderabad (Telangana),77.5,51.7,12.9,2023,4855.0,Cybercrime
27,Indore (Madhya Pradesh),21.7,2.6,82.4,2023,86.0,Cybercrime
28,Jaipur (Rajasthan),30.7,6.4,33.2,2023,551.0,Cybercrime
29,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2023,481.0,Cybercrime
30,Kochi (Kerala),21.2,9.5,55.4,2023,112.0,Cybercrime
31,Kolkata (West Bengal),141.1,0.1,95.6,2023,21.0,Cybercrime
32,Kozhikode (Kerala),20.3,5.2,39.5,2023,114.0,Cybercrime
33,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2023,1453.0,Cybercrime
34,Mumbai (Maharashtra),184.1,26.8,30.8,2023,4131.0,Cybercrime
35,Nagpur (Maharashtra),25.0,10.1,79.6,2023,309.0,Cybercrime
36,Patna (Bihar),20.5,31.4,100.0,2023,235.0,Cybercrime
37,Pune (Maharashtra),50.5,29.8,26.6,2023,487.0,Cybercrime
38,Surat (Gujarat),45.8,5.8,66.7,2023,397.0,Cybercrime
39,NaN,NaN,NaN,NaN,2023,NaN,Cybercrime
40,Ahmedabad (Gujarat),63.5,6.2,48.6,2024,396.0,Cybercrime
41,Bengaluru (Karnataka),85.0,206.6,24.2,2024,17561.0,Cybercrime
42,Chennai (Tamil Nadu),87.0,21.6,41.2,2024,1882.0,Cybercrime
43,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2024,300.0,Cybercrime
44,Delhi City,163.1,2.5,77.8,2024,404.0,Cybercrime
45,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2024,479.0,Cybercrime
46,Hyderabad (Telangana),77.5,51.7,12.9,2024,4009.0,Cybercrime
47,Indore (Madhya Pradesh),21.7,2.6,82.4,2024,57.0,Cybercrime
48,Jaipur (Rajasthan),30.7,6.4,33.2,2024,197.0,Cybercrime
49,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2024,449.0,Cybercrime
50,Kochi (Kerala),21.2,9.5,55.4,2024,201.0,Cybercrime
51,Kolkata (West Bengal),141.1,0.1,95.6,2024,21.0,Cybercrime
52,Kozhikode (Kerala),20.3,5.2,39.5,2024,106.0,Cybercrime
53,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2024,1292.0,Cybercrime
54,Mumbai (Maharashtra),184.1,26.8,30.8,2024,4939.0,Cybercrime
55,Nagpur (Maharashtra),25.0,10.1,79.6,2024,253.0,Cybercrime
56,Patna (Bihar),20.5,31.4,100.0,2024,642.0,Cybercrime
57,Pune (Maharashtra),50.5,29.8,26.6,2024,1504.0,Cybercrime
58,Surat (Gujarat),45.8,5.8,66.7,2024,266.0,Cybercrime
59,NaN,NaN,NaN,NaN,2024,NaN,Cybercrime

**Top Cities**

In [17]:
df_long.groupby('city')['cases'].sum()

city
Ahmedabad (Gujarat)            903.0
Bengaluru (Karnataka)        45132.0
Chennai (Tamil Nadu)          3505.0
Coimbatore (Tamil Nadu)        575.0
Delhi City                    1496.0
Ghaziabad (Uttar Pradesh)     1985.0
Hyderabad (Telangana)        13300.0
Indore (Madhya Pradesh)        190.0
Jaipur (Rajasthan)            1058.0
Kanpur (Uttar Pradesh)        1471.0
Kochi (Kerala)                 409.0
Kolkata (West Bengal)          117.0
Kozhikode (Kerala)             265.0
Lucknow (Uttar Pradesh)       3879.0
Mumbai (Maharashtra)         13794.0
Nagpur (Maharashtra)           773.0
Patna (Bihar)                 1099.0
Pune (Maharashtra)            2348.0
Surat (Gujarat)               1034.0
Name: cases, dtype: float64

**Trend Analysis**

In [18]:
df_long.groupby(['year', 'city'])['cases'].sum()

year  city
2022  Ahmedabad (Gujarat)            261.0
      Bengaluru (Karnataka)         9940.0
      Chennai (Tamil Nadu)           271.0
      Coimbatore (Tamil Nadu)         68.0
      Delhi City                     685.0
      Ghaziabad (Uttar Pradesh)      626.0
      Hyderabad (Telangana)         4436.0
      Indore (Madhya Pradesh)         47.0
      Jaipur (Rajasthan)             310.0
      Kanpur (Uttar Pradesh)         541.0
      Kochi (Kerala)                  96.0
      Kolkata (West Bengal)           75.0
      Kozhikode (Kerala)              45.0
      Lucknow (Uttar Pradesh)       1134.0
      Mumbai (Maharashtra)          4724.0
      Nagpur (Maharashtra)           211.0
      Patna (Bihar)                  222.0
      Pune (Maharashtra)             357.0
      Surat (Gujarat)                371.0
2023  Ahmedabad (Gujarat)            246.0
      Bengaluru (Karnataka)        17631.0
      Chennai (Tamil Nadu)          1352.0
      Coimbatore (Tamil Nadu)        207.0
      Delhi City                     407.0
      Ghaziabad (Uttar Pradesh)      880.0
      Hyderabad (Telangana)         4855.0
      Indore (Madhya Pradesh)         86.0
      Jaipur (Rajasthan)             551.0
      Kanpur (Uttar Pradesh)         481.0
      Kochi (Kerala)                 112.0
      Kolkata (West Bengal)           21.0
      Kozhikode (Kerala)             114.0
      Lucknow (Uttar Pradesh)       1453.0
      Mumbai (Maharashtra)          4131.0
      Nagpur (Maharashtra)           309.0
      Patna (Bihar)                  235.0
      Pune (Maharashtra)             487.0
      Surat (Gujarat)                397.0
2024  Ahmedabad (Gujarat)            396.0
      Bengaluru (Karnataka)        17561.0
      Chennai (Tamil Nadu)          1882.0
      Coimbatore (Tamil Nadu)        300.0
      Delhi City                     404.0
      Ghaziabad (Uttar Pradesh)      479.0
      Hyderabad (Telangana)         4009.0
      Indore (Madhya Pradesh)         57.0
      Jaipur (Rajasthan)             197.0
      Kanpur (Uttar Pradesh)         449.0
      Kochi (Kerala)                 201.0
      Kolkata (West Bengal)           21.0
      Kozhikode (Kerala)             106.0
      Lucknow (Uttar Pradesh)       1292.0
      Mumbai (Maharashtra)          4939.0
      Nagpur (Maharashtra)           253.0
      Patna (Bihar)                  642.0
      Pune (Maharashtra)            1504.0
      Surat (Gujarat)                266.0
Name: cases, dtype: float64

**CyberCrime Data**

In [19]:
df_long[df_long['category'] == 'Cybercrime']

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category
0,Ahmedabad (Gujarat),63.5,6.2,48.6,2022,261.0,Cybercrime
1,Bengaluru (Karnataka),85.0,206.6,24.2,2022,9940.0,Cybercrime
2,Chennai (Tamil Nadu),87.0,21.6,41.2,2022,271.0,Cybercrime
3,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2022,68.0,Cybercrime
4,Delhi City,163.1,2.5,77.8,2022,685.0,Cybercrime
5,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2022,626.0,Cybercrime
6,Hyderabad (Telangana),77.5,51.7,12.9,2022,4436.0,Cybercrime
7,Indore (Madhya Pradesh),21.7,2.6,82.4,2022,47.0,Cybercrime
8,Jaipur (Rajasthan),30.7,6.4,33.2,2022,310.0,Cybercrime
9,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2022,541.0,Cybercrime
10,Kochi (Kerala),21.2,9.5,55.4,2022,96.0,Cybercrime
11,Kolkata (West Bengal),141.1,0.1,95.6,2022,75.0,Cybercrime
12,Kozhikode (Kerala),20.3,5.2,39.5,2022,45.0,Cybercrime
13,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2022,1134.0,Cybercrime
14,Mumbai (Maharashtra),184.1,26.8,30.8,2022,4724.0,Cybercrime
15,Nagpur (Maharashtra),25.0,10.1,79.6,2022,211.0,Cybercrime
16,Patna (Bihar),20.5,31.4,100.0,2022,222.0,Cybercrime
17,Pune (Maharashtra),50.5,29.8,26.6,2022,357.0,Cybercrime
18,Surat (Gujarat),45.8,5.8,66.7,2022,371.0,Cybercrime
19,NaN,NaN,NaN,NaN,2022,NaN,Cybercrime
20,Ahmedabad (Gujarat),63.5,6.2,48.6,2023,246.0,Cybercrime
21,Bengaluru (Karnataka),85.0,206.6,24.2,2023,17631.0,Cybercrime
22,Chennai (Tamil Nadu),87.0,21.6,41.2,2023,1352.0,Cybercrime
23,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2023,207.0,Cybercrime
24,Delhi City,163.1,2.5,77.8,2023,407.0,Cybercrime
25,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2023,880.0,Cybercrime
26,Hyderabad (Telangana),77.5,51.7,12.9,2023,4855.0,Cybercrime
27,Indore (Madhya Pradesh),21.7,2.6,82.4,2023,86.0,Cybercrime
28,Jaipur (Rajasthan),30.7,6.4,33.2,2023,551.0,Cybercrime
29,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2023,481.0,Cybercrime
30,Kochi (Kerala),21.2,9.5,55.4,2023,112.0,Cybercrime
31,Kolkata (West Bengal),141.1,0.1,95.6,2023,21.0,Cybercrime
32,Kozhikode (Kerala),20.3,5.2,39.5,2023,114.0,Cybercrime
33,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2023,1453.0,Cybercrime
34,Mumbai (Maharashtra),184.1,26.8,30.8,2023,4131.0,Cybercrime
35,Nagpur (Maharashtra),25.0,10.1,79.6,2023,309.0,Cybercrime
36,Patna (Bihar),20.5,31.4,100.0,2023,235.0,Cybercrime
37,Pune (Maharashtra),50.5,29.8,26.6,2023,487.0,Cybercrime
38,Surat (Gujarat),45.8,5.8,66.7,2023,397.0,Cybercrime
39,NaN,NaN,NaN,NaN,2023,NaN,Cybercrime
40,Ahmedabad (Gujarat),63.5,6.2,48.6,2024,396.0,Cybercrime
41,Bengaluru (Karnataka),85.0,206.6,24.2,2024,17561.0,Cybercrime
42,Chennai (Tamil Nadu),87.0,21.6,41.2,2024,1882.0,Cybercrime
43,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2024,300.0,Cybercrime
44,Delhi City,163.1,2.5,77.8,2024,404.0,Cybercrime
45,Ghaziabad (Uttar Pradesh),23.6,20.3,21.3,2024,479.0,Cybercrime
46,Hyderabad (Telangana),77.5,51.7,12.9,2024,4009.0,Cybercrime
47,Indore (Madhya Pradesh),21.7,2.6,82.4,2024,57.0,Cybercrime
48,Jaipur (Rajasthan),30.7,6.4,33.2,2024,197.0,Cybercrime
49,Kanpur (Uttar Pradesh),29.2,15.4,84.6,2024,449.0,Cybercrime
50,Kochi (Kerala),21.2,9.5,55.4,2024,201.0,Cybercrime
51,Kolkata (West Bengal),141.1,0.1,95.6,2024,21.0,Cybercrime
52,Kozhikode (Kerala),20.3,5.2,39.5,2024,106.0,Cybercrime
53,Lucknow (Uttar Pradesh),29.0,44.5,22.8,2024,1292.0,Cybercrime
54,Mumbai (Maharashtra),184.1,26.8,30.8,2024,4939.0,Cybercrime
55,Nagpur (Maharashtra),25.0,10.1,79.6,2024,253.0,Cybercrime
56,Patna (Bihar),20.5,31.4,100.0,2024,642.0,Cybercrime
57,Pune (Maharashtra),50.5,29.8,26.6,2024,1504.0,Cybercrime
58,Surat (Gujarat),45.8,5.8,66.7,2024,266.0,Cybercrime
59,NaN,NaN,NaN,NaN,2024,NaN,Cybercrime

**Info of new df**

In [20]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city                      57 non-null     object
 1   population_lakhs_2011     57 non-null     float64
 2   crime_rate_2024           57 non-null     float64
 3   chargesheeting_rate_2024  57 non-null     float64
 4   year                      60 non-null     object
 5   cases                     57 non-null     float64
 6   category                  60 non-null     object
dtypes: float64(4), object(3)
memory usage: 3.4+ KB

**Changing Year Data Type to INT**

In [21]:
df_long['year']=df_long['year'].astype(int)

**Finding Null Values**

In [22]:
df_long[df_long.isnull().any(axis=1)]

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category
19,NaN,NaN,NaN,NaN,2022,NaN,Cybercrime
39,NaN,NaN,NaN,NaN,2023,NaN,Cybercrime
59,NaN,NaN,NaN,NaN,2024,NaN,Cybercrime

In [23]:
df_long.dropna(inplace=True)

In [24]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 0 to 58
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city                      57 non-null     object
 1   population_lakhs_2011     57 non-null     float64
 2   crime_rate_2024           57 non-null     float64
 3   chargesheeting_rate_2024  57 non-null     float64
 4   year                      57 non-null     int64
 5   cases                     57 non-null     float64
 6   category                  57 non-null     object
dtypes: float64(4), int64(1), object(2)
memory usage: 3.6+ KB

**Reseting Index After Deleting rows**

In [25]:
df_long.reset_index(drop=True, inplace=True)

**Check Duplicates**

In [26]:
df_long.duplicated().sum()

np.int64(0)

In [27]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city                      57 non-null     object
 1   population_lakhs_2011     57 non-null     float64
 2   crime_rate_2024           57 non-null     float64
 3   chargesheeting_rate_2024  57 non-null     float64
 4   year                      57 non-null     int64
 5   cases                     57 non-null     float64
 6   category                  57 non-null     object
dtypes: float64(4), int64(1), object(2)
memory usage: 3.2+ KB

In [28]:
df_long.head()

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category
0,Ahmedabad (Gujarat),63.5,6.2,48.6,2022,261.0,Cybercrime
1,Bengaluru (Karnataka),85.0,206.6,24.2,2022,9940.0,Cybercrime
2,Chennai (Tamil Nadu),87.0,21.6,41.2,2022,271.0,Cybercrime
3,Coimbatore (Tamil Nadu),21.5,13.9,17.9,2022,68.0,Cybercrime
4,Delhi City,163.1,2.5,77.8,2022,685.0,Cybercrime

In [29]:
def extract_city_state(df):

    # Create state column
    df['state'] = df['city'].str.extract(r'\((.*?)\)')

    # Clean city column
    df['city'] = df['city'].str.replace(
        r'\s*\(.*?\)',
        '',
        regex=True
    )

    # Handle Delhi separately
    df.loc[
        df['city'] == 'Delhi City',
        'state'
    ] = 'Delhi'

    return df

In [30]:
extract_city_state(df_long)

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category,state
0,Ahmedabad,63.5,6.2,48.6,2022,261.0,Cybercrime,Gujarat
1,Bengaluru,85.0,206.6,24.2,2022,9940.0,Cybercrime,Karnataka
2,Chennai,87.0,21.6,41.2,2022,271.0,Cybercrime,Tamil Nadu
3,Coimbatore,21.5,13.9,17.9,2022,68.0,Cybercrime,Tamil Nadu
4,Delhi City,163.1,2.5,77.8,2022,685.0,Cybercrime,Delhi
5,Ghaziabad,23.6,20.3,21.3,2022,626.0,Cybercrime,Uttar Pradesh
6,Hyderabad,77.5,51.7,12.9,2022,4436.0,Cybercrime,Telangana
7,Indore,21.7,2.6,82.4,2022,47.0,Cybercrime,Madhya Pradesh
8,Jaipur,30.7,6.4,33.2,2022,310.0,Cybercrime,Rajasthan
9,Kanpur,29.2,15.4,84.6,2022,541.0,Cybercrime,Uttar Pradesh
10,Kochi,21.2,9.5,55.4,2022,96.0,Cybercrime,Kerala
11,Kolkata,141.1,0.1,95.6,2022,75.0,Cybercrime,West Bengal
12,Kozhikode,20.3,5.2,39.5,2022,45.0,Cybercrime,Kerala
13,Lucknow,29.0,44.5,22.8,2022,1134.0,Cybercrime,Uttar Pradesh
14,Mumbai,184.1,26.8,30.8,2022,4724.0,Cybercrime,Maharashtra
15,Nagpur,25.0,10.1,79.6,2022,211.0,Cybercrime,Maharashtra
16,Patna,20.5,31.4,100.0,2022,222.0,Cybercrime,Bihar
17,Pune,50.5,29.8,26.6,2022,357.0,Cybercrime,Maharashtra
18,Surat,45.8,5.8,66.7,2022,371.0,Cybercrime,Gujarat
19,Ahmedabad,63.5,6.2,48.6,2023,246.0,Cybercrime,Gujarat
20,Bengaluru,85.0,206.6,24.2,2023,17631.0,Cybercrime,Karnataka
21,Chennai,87.0,21.6,41.2,2023,1352.0,Cybercrime,Tamil Nadu
22,Coimbatore,21.5,13.9,17.9,2023,207.0,Cybercrime,Tamil Nadu
23,Delhi City,163.1,2.5,77.8,2023,407.0,Cybercrime,Delhi
24,Ghaziabad,23.6,20.3,21.3,2023,880.0,Cybercrime,Uttar Pradesh
25,Hyderabad,77.5,51.7,12.9,2023,4855.0,Cybercrime,Telangana
26,Indore,21.7,2.6,82.4,2023,86.0,Cybercrime,Madhya Pradesh
27,Jaipur,30.7,6.4,33.2,2023,551.0,Cybercrime,Rajasthan
28,Kanpur,29.2,15.4,84.6,2023,481.0,Cybercrime,Uttar Pradesh
29,Kochi,21.2,9.5,55.4,2023,112.0,Cybercrime,Kerala
30,Kolkata,141.1,0.1,95.6,2023,21.0,Cybercrime,West Bengal
31,Kozhikode,20.3,5.2,39.5,2023,114.0,Cybercrime,Kerala
32,Lucknow,29.0,44.5,22.8,2023,1453.0,Cybercrime,Uttar Pradesh
33,Mumbai,184.1,26.8,30.8,2023,4131.0,Cybercrime,Maharashtra
34,Nagpur,25.0,10.1,79.6,2023,309.0,Cybercrime,Maharashtra
35,Patna,20.5,31.4,100.0,2023,235.0,Cybercrime,Bihar
36,Pune,50.5,29.8,26.6,2023,487.0,Cybercrime,Maharashtra
37,Surat,45.8,5.8,66.7,2023,397.0,Cybercrime,Gujarat
38,Ahmedabad,63.5,6.2,48.6,2024,396.0,Cybercrime,Gujarat
39,Bengaluru,85.0,206.6,24.2,2024,17561.0,Cybercrime,Karnataka
40,Chennai,87.0,21.6,41.2,2024,1882.0,Cybercrime,Tamil Nadu
41,Coimbatore,21.5,13.9,17.9,2024,300.0,Cybercrime,Tamil Nadu
42,Delhi City,163.1,2.5,77.8,2024,404.0,Cybercrime,Delhi
43,Ghaziabad,23.6,20.3,21.3,2024,479.0,Cybercrime,Uttar Pradesh
44,Hyderabad,77.5,51.7,12.9,2024,4009.0,Cybercrime,Telangana
45,Indore,21.7,2.6,82.4,2024,57.0,Cybercrime,Madhya Pradesh
46,Jaipur,30.7,6.4,33.2,2024,197.0,Cybercrime,Rajasthan
47,Kanpur,29.2,15.4,84.6,2024,449.0,Cybercrime,Uttar Pradesh
48,Kochi,21.2,9.5,55.4,2024,201.0,Cybercrime,Kerala
49,Kolkata,141.1,0.1,95.6,2024,21.0,Cybercrime,West Bengal
50,Kozhikode,20.3,5.2,39.5,2024,106.0,Cybercrime,Kerala
51,Lucknow,29.0,44.5,22.8,2024,1292.0,Cybercrime,Uttar Pradesh
52,Mumbai,184.1,26.8,30.8,2024,4939.0,Cybercrime,Maharashtra
53,Nagpur,25.0,10.1,79.6,2024,253.0,Cybercrime,Maharashtra
54,Patna,20.5,31.4,100.0,2024,642.0,Cybercrime,Bihar
55,Pune,50.5,29.8,26.6,2024,1504.0,Cybercrime,Maharashtra
56,Surat,45.8,5.8,66.7,2024,266.0,Cybercrime,Gujarat

In [31]:
df_long = df_long[
    [
        'year',
        'state',
        'city',
        'category',
        'cases',
        'population_lakhs_2011',
        'crime_rate_2024',
        'chargesheeting_rate_2024'
    ]
]

In [32]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Cybercrime,261.0,63.5,6.2,48.6
1,2022,Karnataka,Bengaluru,Cybercrime,9940.0,85.0,206.6,24.2
2,2022,Tamil Nadu,Chennai,Cybercrime,271.0,87.0,21.6,41.2
3,2022,Tamil Nadu,Coimbatore,Cybercrime,68.0,21.5,13.9,17.9
4,2022,Delhi,Delhi City,Cybercrime,685.0,163.1,2.5,77.8
5,2022,Uttar Pradesh,Ghaziabad,Cybercrime,626.0,23.6,20.3,21.3
6,2022,Telangana,Hyderabad,Cybercrime,4436.0,77.5,51.7,12.9
7,2022,Madhya Pradesh,Indore,Cybercrime,47.0,21.7,2.6,82.4
8,2022,Rajasthan,Jaipur,Cybercrime,310.0,30.7,6.4,33.2
9,2022,Uttar Pradesh,Kanpur,Cybercrime,541.0,29.2,15.4,84.6
10,2022,Kerala,Kochi,Cybercrime,96.0,21.2,9.5,55.4
11,2022,West Bengal,Kolkata,Cybercrime,75.0,141.1,0.1,95.6
12,2022,Kerala,Kozhikode,Cybercrime,45.0,20.3,5.2,39.5
13,2022,Uttar Pradesh,Lucknow,Cybercrime,1134.0,29.0,44.5,22.8
14,2022,Maharashtra,Mumbai,Cybercrime,4724.0,184.1,26.8,30.8
15,2022,Maharashtra,Nagpur,Cybercrime,211.0,25.0,10.1,79.6
16,2022,Bihar,Patna,Cybercrime,222.0,20.5,31.4,100.0
17,2022,Maharashtra,Pune,Cybercrime,357.0,50.5,29.8,26.6
18,2022,Gujarat,Surat,Cybercrime,371.0,45.8,5.8,66.7
19,2023,Gujarat,Ahmedabad,Cybercrime,246.0,63.5,6.2,48.6
20,2023,Karnataka,Bengaluru,Cybercrime,17631.0,85.0,206.6,24.2
21,2023,Tamil Nadu,Chennai,Cybercrime,1352.0,87.0,21.6,41.2
22,2023,Tamil Nadu,Coimbatore,Cybercrime,207.0,21.5,13.9,17.9
23,2023,Delhi,Delhi City,Cybercrime,407.0,163.1,2.5,77.8
24,2023,Uttar Pradesh,Ghaziabad,Cybercrime,880.0,23.6,20.3,21.3
25,2023,Telangana,Hyderabad,Cybercrime,4855.0,77.5,51.7,12.9
26,2023,Madhya Pradesh,Indore,Cybercrime,86.0,21.7,2.6,82.4
27,2023,Rajasthan,Jaipur,Cybercrime,551.0,30.7,6.4,33.2
28,2023,Uttar Pradesh,Kanpur,Cybercrime,481.0,29.2,15.4,84.6
29,2023,Kerala,Kochi,Cybercrime,112.0,21.2,9.5,55.4
30,2023,West Bengal,Kolkata,Cybercrime,21.0,141.1,0.1,95.6
31,2023,Kerala,Kozhikode,Cybercrime,114.0,20.3,5.2,39.5
32,2023,Uttar Pradesh,Lucknow,Cybercrime,1453.0,29.0,44.5,22.8
33,2023,Maharashtra,Mumbai,Cybercrime,4131.0,184.1,26.8,30.8
34,2023,Maharashtra,Nagpur,Cybercrime,309.0,25.0,10.1,79.6
35,2023,Bihar,Patna,Cybercrime,235.0,20.5,31.4,100.0
36,2023,Maharashtra,Pune,Cybercrime,487.0,50.5,29.8,26.6
37,2023,Gujarat,Surat,Cybercrime,397.0,45.8,5.8,66.7
38,2024,Gujarat,Ahmedabad,Cybercrime,396.0,63.5,6.2,48.6
39,2024,Karnataka,Bengaluru,Cybercrime,17561.0,85.0,206.6,24.2
40,2024,Tamil Nadu,Chennai,Cybercrime,1882.0,87.0,21.6,41.2
41,2024,Tamil Nadu,Coimbatore,Cybercrime,300.0,21.5,13.9,17.9
42,2024,Delhi,Delhi City,Cybercrime,404.0,163.1,2.5,77.8
43,2024,Uttar Pradesh,Ghaziabad,Cybercrime,479.0,23.6,20.3,21.3
44,2024,Telangana,Hyderabad,Cybercrime,4009.0,77.5,51.7,12.9
45,2024,Madhya Pradesh,Indore,Cybercrime,57.0,21.7,2.6,82.4
46,2024,Rajasthan,Jaipur,Cybercrime,197.0,30.7,6.4,33.2
47,2024,Uttar Pradesh,Kanpur,Cybercrime,449.0,29.2,15.4,84.6
48,2024,Kerala,Kochi,Cybercrime,201.0,21.2,9.5,55.4
49,2024,West Bengal,Kolkata,Cybercrime,21.0,141.1,0.1,95.6
50,2024,Kerala,Kozhikode,Cybercrime,106.0,20.3,5.2,39.5
51,2024,Uttar Pradesh,Lucknow,Cybercrime,1292.0,29.0,44.5,22.8
52,2024,Maharashtra,Mumbai,Cybercrime,4939.0,184.1,26.8,30.8
53,2024,Maharashtra,Nagpur,Cybercrime,253.0,25.0,10.1,79.6
54,2024,Bihar,Patna,Cybercrime,642.0,20.5,31.4,100.0
55,2024,Maharashtra,Pune,Cybercrime,1504.0,50.5,29.8,26.6
56,2024,Gujarat,Surat,Cybercrime,266.0,45.8,5.8,66.7

**Saving Master File**

In [33]:
df_long.to_csv("../cleaned data/master_cybercrime.csv",index=False)

**Reusable Cleaning functions**

**Function 1 - Clean Column Names**

In [34]:
def clean_column_names(df):

    df.columns=(
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ","_")
        .str.replace("-","_")
    )

    return df

**Function 2 - Clean Year Columns**

In [35]:
def clean_year_columns(df):

    df.rename(columns={
        '2022.0':'2022',
        '2023.0':'2023',
        '2024.0':'2024'},inplace =True) 

    return df

**Function 3 Remove Total Rows**

In [36]:
def remove_total_rows(df):

    df=df[
        ~df['city'].astype(str).str.contains('total',case=False, na=False)]

    return df

**Function 4 Drop Empty Rows**

In [37]:
def remove_empty_rows(df):

    df.dropna(how='all', inplace=True)

    return df

**Function 5 Drop Unnecessary Columns**

In [38]:
def remove_unwanted_columns(df):
    if 'sl' in df.columns:
        df = df.drop(columns=['sl'])
        
    return df

**Function 6 Melt Data**

In [39]:
def melt_crime_data(df, category_name, rate_column):

    df_long = df.melt(
        id_vars=[
            'city',
            'actual_population_(lakhs)_2011',
            rate_column,
            'chargesheeting_rate_(2024)'
        ],
        value_vars=['2022', '2023', '2024'],
        var_name='year',
        value_name='cases'
    )

    # Standardize column names
    df_long.rename(columns={
        'actual_population_(lakhs)_2011': 'population_lakhs_2011',
        rate_column: 'crime_rate_2024',
        'chargesheeting_rate_(2024)': 'chargesheeting_rate_2024'
    }, inplace=True)

    df_long['category'] = category_name

    return df_long

**Function 7 - Final Cleaning**

In [40]:


def final_cleaning(df):
   
    df = df.dropna()

    df = df.drop_duplicates()
  
    df = df.reset_index(drop=True)

    df['year'] = df['year'].astype(int)
    
    return df

**Function 8 - Extract City State**

In [41]:
def extract_city_state(df):

    # Create state column
    df['state'] = df['city'].str.extract(r'\((.*?)\)')

    # Clean city column
    df['city'] = df['city'].str.replace(
        r'\s*\(.*?\)',
        '',
        regex=True
    )

    # Handle Delhi separately
    df.loc[
        df['city'] == 'Delhi City',
        'state'
    ] = 'Delhi'

    return df

**Reorder columns**

In [42]:
def reorder_columns(df):
    df = df[
    [
        'year',
        'state',
        'city',
        'category',
        'cases',
        'population_lakhs_2011',
        'crime_rate_2024',
        'chargesheeting_rate_2024'
    ]]
    return df

**FULL ETL PIPELINE EXECUTION**

**Woman Crime Dataset**

In [75]:
path2= "../raw data/Metropolitan Cities - Crime Against Women.xlsx"

In [76]:
df = pd.read_excel(path2, header=1)

df.head(15)

,SL,City,2022,2023,2024,Actual Population (in Lakhs) (2011),Rate of Total Crime against Women (2024),Chargesheeting Rate (2024)
0,1.0,Ahmedabad (Gujarat),1452,1360,1059,30.0,35.3,89.7
1,2.0,Bengaluru (Karnataka),3924,4870,4748,40.6,117.0,70.5
2,3.0,Chennai (Tamil Nadu),736,745,1093,43.1,25.4,93.9
3,4.0,Coimbatore (Tamil Nadu),138,244,377,10.7,35.1,95.6
4,5.0,Delhi City,14158,13366,13396,75.8,176.8,73.6
5,6.0,Ghaziabad (Uttar Pradesh),1063,904,1265,11.0,114.8,65.8
6,7.0,Hyderabad (Telangana),3145,3822,3255,37.6,86.5,76.3
7,8.0,Indore (Madhya Pradesh),1809,1919,1884,10.4,181.5,76.2
8,9.0,Jaipur (Rajasthan),3479,3872,2894,14.5,199.0,55.7
9,10.0,Kanpur (Uttar Pradesh),2099,2071,1950,13.4,146.1,84.4
10,11.0,Kochi (Kerala),754,783,783,10.8,72.8,91.2
11,12.0,Kolkata (West Bengal),1890,1746,1958,67.9,28.8,98.5
12,13.0,Kozhikode (Kerala),759,627,665,10.6,62.5,92.6
13,14.0,Lucknow (Uttar Pradesh),2231,2902,2571,13.8,186.0,83.7
14,15.0,Mumbai (Maharashtra),6176,6025,6358,85.2,74.6,81.4

**Applying Pipeline Step-By-Step**

In [77]:
df = clean_column_names(df)

In [78]:
df = clean_year_columns(df)

In [79]:
df = remove_empty_rows(df)

In [80]:
df.columns

Index(['sl', 'city', '2022', '2023', '2024',
       'actual_population_(in_lakhs)_(2011)',
       'rate_of_total_crime_against_women_(2024)',
       'chargesheeting_rate_(2024)'],
      dtype='object')

In [81]:
df = remove_total_rows(df)

In [82]:
df = remove_unwanted_columns(df)

In [83]:
df.head()

,city,2022,2023,2024,actual_population_(in_lakhs)_(2011),rate_of_total_crime_against_women_(2024),chargesheeting_rate_(2024)
0,Ahmedabad (Gujarat),1452,1360,1059,30.0,35.3,89.7
1,Bengaluru (Karnataka),3924,4870,4748,40.6,117.0,70.5
2,Chennai (Tamil Nadu),736,745,1093,43.1,25.4,93.9
3,Coimbatore (Tamil Nadu),138,244,377,10.7,35.1,95.6
4,Delhi City,14158,13366,13396,75.8,176.8,73.6

In [84]:
df.columns

Index(['city', '2022', '2023', '2024', 'actual_population_(in_lakhs)_(2011)',
       'rate_of_total_crime_against_women_(2024)',
       'chargesheeting_rate_(2024)'],
      dtype='object')

In [85]:
df_long = df.melt(
    id_vars=[
        'city',
        'actual_population_(in_lakhs)_(2011)',
        'rate_of_total_crime_against_women_(2024)',
        'chargesheeting_rate_(2024)'
    ],

    value_vars=[
        '2022',
        '2023',
        '2024'
    ],

    var_name='year',
    value_name='cases'
)

In [86]:
df_long

,city,actual_population_(in_lakhs)_(2011),rate_of_total_crime_against_women_(2024),chargesheeting_rate_(2024),year,cases
0,Ahmedabad (Gujarat),30.0,35.3,89.7,2022,1452
1,Bengaluru (Karnataka),40.6,117.0,70.5,2022,3924
2,Chennai (Tamil Nadu),43.1,25.4,93.9,2022,736
3,Coimbatore (Tamil Nadu),10.7,35.1,95.6,2022,138
4,Delhi City,75.8,176.8,73.6,2022,14158
5,Ghaziabad (Uttar Pradesh),11.0,114.8,65.8,2022,1063
6,Hyderabad (Telangana),37.6,86.5,76.3,2022,3145
7,Indore (Madhya Pradesh),10.4,181.5,76.2,2022,1809
8,Jaipur (Rajasthan),14.5,199.0,55.7,2022,3479
9,Kanpur (Uttar Pradesh),13.4,146.1,84.4,2022,2099
10,Kochi (Kerala),10.8,72.8,91.2,2022,754
11,Kolkata (West Bengal),67.9,28.8,98.5,2022,1890
12,Kozhikode (Kerala),10.6,62.5,92.6,2022,759
13,Lucknow (Uttar Pradesh),13.8,186.0,83.7,2022,2231
14,Mumbai (Maharashtra),85.2,74.6,81.4,2022,6176
15,Nagpur (Maharashtra),12.2,123.8,78.6,2022,1259
16,Patna (Bihar),9.6,129.2,82.7,2022,812
17,Pune (Maharashtra),23.9,110.1,75.9,2022,2074
18,Surat (Gujarat),19.7,47.9,83.0,2022,797
19,Ahmedabad (Gujarat),30.0,35.3,89.7,2023,1360
20,Bengaluru (Karnataka),40.6,117.0,70.5,2023,4870
21,Chennai (Tamil Nadu),43.1,25.4,93.9,2023,745
22,Coimbatore (Tamil Nadu),10.7,35.1,95.6,2023,244
23,Delhi City,75.8,176.8,73.6,2023,13366
24,Ghaziabad (Uttar Pradesh),11.0,114.8,65.8,2023,904
25,Hyderabad (Telangana),37.6,86.5,76.3,2023,3822
26,Indore (Madhya Pradesh),10.4,181.5,76.2,2023,1919
27,Jaipur (Rajasthan),14.5,199.0,55.7,2023,3872
28,Kanpur (Uttar Pradesh),13.4,146.1,84.4,2023,2071
29,Kochi (Kerala),10.8,72.8,91.2,2023,783
30,Kolkata (West Bengal),67.9,28.8,98.5,2023,1746
31,Kozhikode (Kerala),10.6,62.5,92.6,2023,627
32,Lucknow (Uttar Pradesh),13.8,186.0,83.7,2023,2902
33,Mumbai (Maharashtra),85.2,74.6,81.4,2023,6025
34,Nagpur (Maharashtra),12.2,123.8,78.6,2023,1556
35,Patna (Bihar),9.6,129.2,82.7,2023,1162
36,Pune (Maharashtra),23.9,110.1,75.9,2023,2550
37,Surat (Gujarat),19.7,47.9,83.0,2023,869
38,Ahmedabad (Gujarat),30.0,35.3,89.7,2024,1059
39,Bengaluru (Karnataka),40.6,117.0,70.5,2024,4748
40,Chennai (Tamil Nadu),43.1,25.4,93.9,2024,1093
41,Coimbatore (Tamil Nadu),10.7,35.1,95.6,2024,377
42,Delhi City,75.8,176.8,73.6,2024,13396
43,Ghaziabad (Uttar Pradesh),11.0,114.8,65.8,2024,1265
44,Hyderabad (Telangana),37.6,86.5,76.3,2024,3255
45,Indore (Madhya Pradesh),10.4,181.5,76.2,2024,1884
46,Jaipur (Rajasthan),14.5,199.0,55.7,2024,2894
47,Kanpur (Uttar Pradesh),13.4,146.1,84.4,2024,1950
48,Kochi (Kerala),10.8,72.8,91.2,2024,783
49,Kolkata (West Bengal),67.9,28.8,98.5,2024,1958
50,Kozhikode (Kerala),10.6,62.5,92.6,2024,665
51,Lucknow (Uttar Pradesh),13.8,186.0,83.7,2024,2571
52,Mumbai (Maharashtra),85.2,74.6,81.4,2024,6358
53,Nagpur (Maharashtra),12.2,123.8,78.6,2024,1513
54,Patna (Bihar),9.6,129.2,82.7,2024,1239
55,Pune (Maharashtra),23.9,110.1,75.9,2024,2631
56,Surat (Gujarat),19.7,47.9,83.0,2024,945

In [87]:
df_long.rename(columns={

    'actual_population_(in_lakhs)_(2011)':
        'population_lakhs_2011',

    'rate_of_total_crime_against_women_(2024)':
        'crime_rate_2024',

    'chargesheeting_rate_(2024)':
        'chargesheeting_rate_2024'

}, inplace=True)

In [88]:
df_long

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases
0,Ahmedabad (Gujarat),30.0,35.3,89.7,2022,1452
1,Bengaluru (Karnataka),40.6,117.0,70.5,2022,3924
2,Chennai (Tamil Nadu),43.1,25.4,93.9,2022,736
3,Coimbatore (Tamil Nadu),10.7,35.1,95.6,2022,138
4,Delhi City,75.8,176.8,73.6,2022,14158
5,Ghaziabad (Uttar Pradesh),11.0,114.8,65.8,2022,1063
6,Hyderabad (Telangana),37.6,86.5,76.3,2022,3145
7,Indore (Madhya Pradesh),10.4,181.5,76.2,2022,1809
8,Jaipur (Rajasthan),14.5,199.0,55.7,2022,3479
9,Kanpur (Uttar Pradesh),13.4,146.1,84.4,2022,2099
10,Kochi (Kerala),10.8,72.8,91.2,2022,754
11,Kolkata (West Bengal),67.9,28.8,98.5,2022,1890
12,Kozhikode (Kerala),10.6,62.5,92.6,2022,759
13,Lucknow (Uttar Pradesh),13.8,186.0,83.7,2022,2231
14,Mumbai (Maharashtra),85.2,74.6,81.4,2022,6176
15,Nagpur (Maharashtra),12.2,123.8,78.6,2022,1259
16,Patna (Bihar),9.6,129.2,82.7,2022,812
17,Pune (Maharashtra),23.9,110.1,75.9,2022,2074
18,Surat (Gujarat),19.7,47.9,83.0,2022,797
19,Ahmedabad (Gujarat),30.0,35.3,89.7,2023,1360
20,Bengaluru (Karnataka),40.6,117.0,70.5,2023,4870
21,Chennai (Tamil Nadu),43.1,25.4,93.9,2023,745
22,Coimbatore (Tamil Nadu),10.7,35.1,95.6,2023,244
23,Delhi City,75.8,176.8,73.6,2023,13366
24,Ghaziabad (Uttar Pradesh),11.0,114.8,65.8,2023,904
25,Hyderabad (Telangana),37.6,86.5,76.3,2023,3822
26,Indore (Madhya Pradesh),10.4,181.5,76.2,2023,1919
27,Jaipur (Rajasthan),14.5,199.0,55.7,2023,3872
28,Kanpur (Uttar Pradesh),13.4,146.1,84.4,2023,2071
29,Kochi (Kerala),10.8,72.8,91.2,2023,783
30,Kolkata (West Bengal),67.9,28.8,98.5,2023,1746
31,Kozhikode (Kerala),10.6,62.5,92.6,2023,627
32,Lucknow (Uttar Pradesh),13.8,186.0,83.7,2023,2902
33,Mumbai (Maharashtra),85.2,74.6,81.4,2023,6025
34,Nagpur (Maharashtra),12.2,123.8,78.6,2023,1556
35,Patna (Bihar),9.6,129.2,82.7,2023,1162
36,Pune (Maharashtra),23.9,110.1,75.9,2023,2550
37,Surat (Gujarat),19.7,47.9,83.0,2023,869
38,Ahmedabad (Gujarat),30.0,35.3,89.7,2024,1059
39,Bengaluru (Karnataka),40.6,117.0,70.5,2024,4748
40,Chennai (Tamil Nadu),43.1,25.4,93.9,2024,1093
41,Coimbatore (Tamil Nadu),10.7,35.1,95.6,2024,377
42,Delhi City,75.8,176.8,73.6,2024,13396
43,Ghaziabad (Uttar Pradesh),11.0,114.8,65.8,2024,1265
44,Hyderabad (Telangana),37.6,86.5,76.3,2024,3255
45,Indore (Madhya Pradesh),10.4,181.5,76.2,2024,1884
46,Jaipur (Rajasthan),14.5,199.0,55.7,2024,2894
47,Kanpur (Uttar Pradesh),13.4,146.1,84.4,2024,1950
48,Kochi (Kerala),10.8,72.8,91.2,2024,783
49,Kolkata (West Bengal),67.9,28.8,98.5,2024,1958
50,Kozhikode (Kerala),10.6,62.5,92.6,2024,665
51,Lucknow (Uttar Pradesh),13.8,186.0,83.7,2024,2571
52,Mumbai (Maharashtra),85.2,74.6,81.4,2024,6358
53,Nagpur (Maharashtra),12.2,123.8,78.6,2024,1513
54,Patna (Bihar),9.6,129.2,82.7,2024,1239
55,Pune (Maharashtra),23.9,110.1,75.9,2024,2631
56,Surat (Gujarat),19.7,47.9,83.0,2024,945

In [89]:
df_long['category'] = 'Women Safety'

In [90]:
df_long = extract_city_state(df_long)
df_long

,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category,state
0,Ahmedabad,30.0,35.3,89.7,2022,1452,Women Safety,Gujarat
1,Bengaluru,40.6,117.0,70.5,2022,3924,Women Safety,Karnataka
2,Chennai,43.1,25.4,93.9,2022,736,Women Safety,Tamil Nadu
3,Coimbatore,10.7,35.1,95.6,2022,138,Women Safety,Tamil Nadu
4,Delhi City,75.8,176.8,73.6,2022,14158,Women Safety,Delhi
5,Ghaziabad,11.0,114.8,65.8,2022,1063,Women Safety,Uttar Pradesh
6,Hyderabad,37.6,86.5,76.3,2022,3145,Women Safety,Telangana
7,Indore,10.4,181.5,76.2,2022,1809,Women Safety,Madhya Pradesh
8,Jaipur,14.5,199.0,55.7,2022,3479,Women Safety,Rajasthan
9,Kanpur,13.4,146.1,84.4,2022,2099,Women Safety,Uttar Pradesh
10,Kochi,10.8,72.8,91.2,2022,754,Women Safety,Kerala
11,Kolkata,67.9,28.8,98.5,2022,1890,Women Safety,West Bengal
12,Kozhikode,10.6,62.5,92.6,2022,759,Women Safety,Kerala
13,Lucknow,13.8,186.0,83.7,2022,2231,Women Safety,Uttar Pradesh
14,Mumbai,85.2,74.6,81.4,2022,6176,Women Safety,Maharashtra
15,Nagpur,12.2,123.8,78.6,2022,1259,Women Safety,Maharashtra
16,Patna,9.6,129.2,82.7,2022,812,Women Safety,Bihar
17,Pune,23.9,110.1,75.9,2022,2074,Women Safety,Maharashtra
18,Surat,19.7,47.9,83.0,2022,797,Women Safety,Gujarat
19,Ahmedabad,30.0,35.3,89.7,2023,1360,Women Safety,Gujarat
20,Bengaluru,40.6,117.0,70.5,2023,4870,Women Safety,Karnataka
21,Chennai,43.1,25.4,93.9,2023,745,Women Safety,Tamil Nadu
22,Coimbatore,10.7,35.1,95.6,2023,244,Women Safety,Tamil Nadu
23,Delhi City,75.8,176.8,73.6,2023,13366,Women Safety,Delhi
24,Ghaziabad,11.0,114.8,65.8,2023,904,Women Safety,Uttar Pradesh
25,Hyderabad,37.6,86.5,76.3,2023,3822,Women Safety,Telangana
26,Indore,10.4,181.5,76.2,2023,1919,Women Safety,Madhya Pradesh
27,Jaipur,14.5,199.0,55.7,2023,3872,Women Safety,Rajasthan
28,Kanpur,13.4,146.1,84.4,2023,2071,Women Safety,Uttar Pradesh
29,Kochi,10.8,72.8,91.2,2023,783,Women Safety,Kerala
30,Kolkata,67.9,28.8,98.5,2023,1746,Women Safety,West Bengal
31,Kozhikode,10.6,62.5,92.6,2023,627,Women Safety,Kerala
32,Lucknow,13.8,186.0,83.7,2023,2902,Women Safety,Uttar Pradesh
33,Mumbai,85.2,74.6,81.4,2023,6025,Women Safety,Maharashtra
34,Nagpur,12.2,123.8,78.6,2023,1556,Women Safety,Maharashtra
35,Patna,9.6,129.2,82.7,2023,1162,Women Safety,Bihar
36,Pune,23.9,110.1,75.9,2023,2550,Women Safety,Maharashtra
37,Surat,19.7,47.9,83.0,2023,869,Women Safety,Gujarat
38,Ahmedabad,30.0,35.3,89.7,2024,1059,Women Safety,Gujarat
39,Bengaluru,40.6,117.0,70.5,2024,4748,Women Safety,Karnataka
40,Chennai,43.1,25.4,93.9,2024,1093,Women Safety,Tamil Nadu
41,Coimbatore,10.7,35.1,95.6,2024,377,Women Safety,Tamil Nadu
42,Delhi City,75.8,176.8,73.6,2024,13396,Women Safety,Delhi
43,Ghaziabad,11.0,114.8,65.8,2024,1265,Women Safety,Uttar Pradesh
44,Hyderabad,37.6,86.5,76.3,2024,3255,Women Safety,Telangana
45,Indore,10.4,181.5,76.2,2024,1884,Women Safety,Madhya Pradesh
46,Jaipur,14.5,199.0,55.7,2024,2894,Women Safety,Rajasthan
47,Kanpur,13.4,146.1,84.4,2024,1950,Women Safety,Uttar Pradesh
48,Kochi,10.8,72.8,91.2,2024,783,Women Safety,Kerala
49,Kolkata,67.9,28.8,98.5,2024,1958,Women Safety,West Bengal
50,Kozhikode,10.6,62.5,92.6,2024,665,Women Safety,Kerala
51,Lucknow,13.8,186.0,83.7,2024,2571,Women Safety,Uttar Pradesh
52,Mumbai,85.2,74.6,81.4,2024,6358,Women Safety,Maharashtra
53,Nagpur,12.2,123.8,78.6,2024,1513,Women Safety,Maharashtra
54,Patna,9.6,129.2,82.7,2024,1239,Women Safety,Bihar
55,Pune,23.9,110.1,75.9,2024,2631,Women Safety,Maharashtra
56,Surat,19.7,47.9,83.0,2024,945,Women Safety,Gujarat

In [91]:
df_long=reorder_columns(df_long)

In [92]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Women Safety,1452,30.0,35.3,89.7
1,2022,Karnataka,Bengaluru,Women Safety,3924,40.6,117.0,70.5
2,2022,Tamil Nadu,Chennai,Women Safety,736,43.1,25.4,93.9
3,2022,Tamil Nadu,Coimbatore,Women Safety,138,10.7,35.1,95.6
4,2022,Delhi,Delhi City,Women Safety,14158,75.8,176.8,73.6
5,2022,Uttar Pradesh,Ghaziabad,Women Safety,1063,11.0,114.8,65.8
6,2022,Telangana,Hyderabad,Women Safety,3145,37.6,86.5,76.3
7,2022,Madhya Pradesh,Indore,Women Safety,1809,10.4,181.5,76.2
8,2022,Rajasthan,Jaipur,Women Safety,3479,14.5,199.0,55.7
9,2022,Uttar Pradesh,Kanpur,Women Safety,2099,13.4,146.1,84.4
10,2022,Kerala,Kochi,Women Safety,754,10.8,72.8,91.2
11,2022,West Bengal,Kolkata,Women Safety,1890,67.9,28.8,98.5
12,2022,Kerala,Kozhikode,Women Safety,759,10.6,62.5,92.6
13,2022,Uttar Pradesh,Lucknow,Women Safety,2231,13.8,186.0,83.7
14,2022,Maharashtra,Mumbai,Women Safety,6176,85.2,74.6,81.4
15,2022,Maharashtra,Nagpur,Women Safety,1259,12.2,123.8,78.6
16,2022,Bihar,Patna,Women Safety,812,9.6,129.2,82.7
17,2022,Maharashtra,Pune,Women Safety,2074,23.9,110.1,75.9
18,2022,Gujarat,Surat,Women Safety,797,19.7,47.9,83.0
19,2023,Gujarat,Ahmedabad,Women Safety,1360,30.0,35.3,89.7
20,2023,Karnataka,Bengaluru,Women Safety,4870,40.6,117.0,70.5
21,2023,Tamil Nadu,Chennai,Women Safety,745,43.1,25.4,93.9
22,2023,Tamil Nadu,Coimbatore,Women Safety,244,10.7,35.1,95.6
23,2023,Delhi,Delhi City,Women Safety,13366,75.8,176.8,73.6
24,2023,Uttar Pradesh,Ghaziabad,Women Safety,904,11.0,114.8,65.8
25,2023,Telangana,Hyderabad,Women Safety,3822,37.6,86.5,76.3
26,2023,Madhya Pradesh,Indore,Women Safety,1919,10.4,181.5,76.2
27,2023,Rajasthan,Jaipur,Women Safety,3872,14.5,199.0,55.7
28,2023,Uttar Pradesh,Kanpur,Women Safety,2071,13.4,146.1,84.4
29,2023,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
30,2023,West Bengal,Kolkata,Women Safety,1746,67.9,28.8,98.5
31,2023,Kerala,Kozhikode,Women Safety,627,10.6,62.5,92.6
32,2023,Uttar Pradesh,Lucknow,Women Safety,2902,13.8,186.0,83.7
33,2023,Maharashtra,Mumbai,Women Safety,6025,85.2,74.6,81.4
34,2023,Maharashtra,Nagpur,Women Safety,1556,12.2,123.8,78.6
35,2023,Bihar,Patna,Women Safety,1162,9.6,129.2,82.7
36,2023,Maharashtra,Pune,Women Safety,2550,23.9,110.1,75.9
37,2023,Gujarat,Surat,Women Safety,869,19.7,47.9,83.0
38,2024,Gujarat,Ahmedabad,Women Safety,1059,30.0,35.3,89.7
39,2024,Karnataka,Bengaluru,Women Safety,4748,40.6,117.0,70.5
40,2024,Tamil Nadu,Chennai,Women Safety,1093,43.1,25.4,93.9
41,2024,Tamil Nadu,Coimbatore,Women Safety,377,10.7,35.1,95.6
42,2024,Delhi,Delhi City,Women Safety,13396,75.8,176.8,73.6
43,2024,Uttar Pradesh,Ghaziabad,Women Safety,1265,11.0,114.8,65.8
44,2024,Telangana,Hyderabad,Women Safety,3255,37.6,86.5,76.3
45,2024,Madhya Pradesh,Indore,Women Safety,1884,10.4,181.5,76.2
46,2024,Rajasthan,Jaipur,Women Safety,2894,14.5,199.0,55.7
47,2024,Uttar Pradesh,Kanpur,Women Safety,1950,13.4,146.1,84.4
48,2024,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
49,2024,West Bengal,Kolkata,Women Safety,1958,67.9,28.8,98.5
50,2024,Kerala,Kozhikode,Women Safety,665,10.6,62.5,92.6
51,2024,Uttar Pradesh,Lucknow,Women Safety,2571,13.8,186.0,83.7
52,2024,Maharashtra,Mumbai,Women Safety,6358,85.2,74.6,81.4
53,2024,Maharashtra,Nagpur,Women Safety,1513,12.2,123.8,78.6
54,2024,Bihar,Patna,Women Safety,1239,9.6,129.2,82.7
55,2024,Maharashtra,Pune,Women Safety,2631,23.9,110.1,75.9
56,2024,Gujarat,Surat,Women Safety,945,19.7,47.9,83.0

In [93]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Women Safety,1452,30.0,35.3,89.7
1,2022,Karnataka,Bengaluru,Women Safety,3924,40.6,117.0,70.5
2,2022,Tamil Nadu,Chennai,Women Safety,736,43.1,25.4,93.9
3,2022,Tamil Nadu,Coimbatore,Women Safety,138,10.7,35.1,95.6
4,2022,Delhi,Delhi City,Women Safety,14158,75.8,176.8,73.6
5,2022,Uttar Pradesh,Ghaziabad,Women Safety,1063,11.0,114.8,65.8
6,2022,Telangana,Hyderabad,Women Safety,3145,37.6,86.5,76.3
7,2022,Madhya Pradesh,Indore,Women Safety,1809,10.4,181.5,76.2
8,2022,Rajasthan,Jaipur,Women Safety,3479,14.5,199.0,55.7
9,2022,Uttar Pradesh,Kanpur,Women Safety,2099,13.4,146.1,84.4
10,2022,Kerala,Kochi,Women Safety,754,10.8,72.8,91.2
11,2022,West Bengal,Kolkata,Women Safety,1890,67.9,28.8,98.5
12,2022,Kerala,Kozhikode,Women Safety,759,10.6,62.5,92.6
13,2022,Uttar Pradesh,Lucknow,Women Safety,2231,13.8,186.0,83.7
14,2022,Maharashtra,Mumbai,Women Safety,6176,85.2,74.6,81.4
15,2022,Maharashtra,Nagpur,Women Safety,1259,12.2,123.8,78.6
16,2022,Bihar,Patna,Women Safety,812,9.6,129.2,82.7
17,2022,Maharashtra,Pune,Women Safety,2074,23.9,110.1,75.9
18,2022,Gujarat,Surat,Women Safety,797,19.7,47.9,83.0
19,2023,Gujarat,Ahmedabad,Women Safety,1360,30.0,35.3,89.7
20,2023,Karnataka,Bengaluru,Women Safety,4870,40.6,117.0,70.5
21,2023,Tamil Nadu,Chennai,Women Safety,745,43.1,25.4,93.9
22,2023,Tamil Nadu,Coimbatore,Women Safety,244,10.7,35.1,95.6
23,2023,Delhi,Delhi City,Women Safety,13366,75.8,176.8,73.6
24,2023,Uttar Pradesh,Ghaziabad,Women Safety,904,11.0,114.8,65.8
25,2023,Telangana,Hyderabad,Women Safety,3822,37.6,86.5,76.3
26,2023,Madhya Pradesh,Indore,Women Safety,1919,10.4,181.5,76.2
27,2023,Rajasthan,Jaipur,Women Safety,3872,14.5,199.0,55.7
28,2023,Uttar Pradesh,Kanpur,Women Safety,2071,13.4,146.1,84.4
29,2023,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
30,2023,West Bengal,Kolkata,Women Safety,1746,67.9,28.8,98.5
31,2023,Kerala,Kozhikode,Women Safety,627,10.6,62.5,92.6
32,2023,Uttar Pradesh,Lucknow,Women Safety,2902,13.8,186.0,83.7
33,2023,Maharashtra,Mumbai,Women Safety,6025,85.2,74.6,81.4
34,2023,Maharashtra,Nagpur,Women Safety,1556,12.2,123.8,78.6
35,2023,Bihar,Patna,Women Safety,1162,9.6,129.2,82.7
36,2023,Maharashtra,Pune,Women Safety,2550,23.9,110.1,75.9
37,2023,Gujarat,Surat,Women Safety,869,19.7,47.9,83.0
38,2024,Gujarat,Ahmedabad,Women Safety,1059,30.0,35.3,89.7
39,2024,Karnataka,Bengaluru,Women Safety,4748,40.6,117.0,70.5
40,2024,Tamil Nadu,Chennai,Women Safety,1093,43.1,25.4,93.9
41,2024,Tamil Nadu,Coimbatore,Women Safety,377,10.7,35.1,95.6
42,2024,Delhi,Delhi City,Women Safety,13396,75.8,176.8,73.6
43,2024,Uttar Pradesh,Ghaziabad,Women Safety,1265,11.0,114.8,65.8
44,2024,Telangana,Hyderabad,Women Safety,3255,37.6,86.5,76.3
45,2024,Madhya Pradesh,Indore,Women Safety,1884,10.4,181.5,76.2
46,2024,Rajasthan,Jaipur,Women Safety,2894,14.5,199.0,55.7
47,2024,Uttar Pradesh,Kanpur,Women Safety,1950,13.4,146.1,84.4
48,2024,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
49,2024,West Bengal,Kolkata,Women Safety,1958,67.9,28.8,98.5
50,2024,Kerala,Kozhikode,Women Safety,665,10.6,62.5,92.6
51,2024,Uttar Pradesh,Lucknow,Women Safety,2571,13.8,186.0,83.7
52,2024,Maharashtra,Mumbai,Women Safety,6358,85.2,74.6,81.4
53,2024,Maharashtra,Nagpur,Women Safety,1513,12.2,123.8,78.6
54,2024,Bihar,Patna,Women Safety,1239,9.6,129.2,82.7
55,2024,Maharashtra,Pune,Women Safety,2631,23.9,110.1,75.9
56,2024,Gujarat,Surat,Women Safety,945,19.7,47.9,83.0

In [94]:
final_cleaning(df_long)

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Women Safety,1452,30.0,35.3,89.7
1,2022,Karnataka,Bengaluru,Women Safety,3924,40.6,117.0,70.5
2,2022,Tamil Nadu,Chennai,Women Safety,736,43.1,25.4,93.9
3,2022,Tamil Nadu,Coimbatore,Women Safety,138,10.7,35.1,95.6
4,2022,Delhi,Delhi City,Women Safety,14158,75.8,176.8,73.6
5,2022,Uttar Pradesh,Ghaziabad,Women Safety,1063,11.0,114.8,65.8
6,2022,Telangana,Hyderabad,Women Safety,3145,37.6,86.5,76.3
7,2022,Madhya Pradesh,Indore,Women Safety,1809,10.4,181.5,76.2
8,2022,Rajasthan,Jaipur,Women Safety,3479,14.5,199.0,55.7
9,2022,Uttar Pradesh,Kanpur,Women Safety,2099,13.4,146.1,84.4
10,2022,Kerala,Kochi,Women Safety,754,10.8,72.8,91.2
11,2022,West Bengal,Kolkata,Women Safety,1890,67.9,28.8,98.5
12,2022,Kerala,Kozhikode,Women Safety,759,10.6,62.5,92.6
13,2022,Uttar Pradesh,Lucknow,Women Safety,2231,13.8,186.0,83.7
14,2022,Maharashtra,Mumbai,Women Safety,6176,85.2,74.6,81.4
15,2022,Maharashtra,Nagpur,Women Safety,1259,12.2,123.8,78.6
16,2022,Bihar,Patna,Women Safety,812,9.6,129.2,82.7
17,2022,Maharashtra,Pune,Women Safety,2074,23.9,110.1,75.9
18,2022,Gujarat,Surat,Women Safety,797,19.7,47.9,83.0
19,2023,Gujarat,Ahmedabad,Women Safety,1360,30.0,35.3,89.7
20,2023,Karnataka,Bengaluru,Women Safety,4870,40.6,117.0,70.5
21,2023,Tamil Nadu,Chennai,Women Safety,745,43.1,25.4,93.9
22,2023,Tamil Nadu,Coimbatore,Women Safety,244,10.7,35.1,95.6
23,2023,Delhi,Delhi City,Women Safety,13366,75.8,176.8,73.6
24,2023,Uttar Pradesh,Ghaziabad,Women Safety,904,11.0,114.8,65.8
25,2023,Telangana,Hyderabad,Women Safety,3822,37.6,86.5,76.3
26,2023,Madhya Pradesh,Indore,Women Safety,1919,10.4,181.5,76.2
27,2023,Rajasthan,Jaipur,Women Safety,3872,14.5,199.0,55.7
28,2023,Uttar Pradesh,Kanpur,Women Safety,2071,13.4,146.1,84.4
29,2023,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
30,2023,West Bengal,Kolkata,Women Safety,1746,67.9,28.8,98.5
31,2023,Kerala,Kozhikode,Women Safety,627,10.6,62.5,92.6
32,2023,Uttar Pradesh,Lucknow,Women Safety,2902,13.8,186.0,83.7
33,2023,Maharashtra,Mumbai,Women Safety,6025,85.2,74.6,81.4
34,2023,Maharashtra,Nagpur,Women Safety,1556,12.2,123.8,78.6
35,2023,Bihar,Patna,Women Safety,1162,9.6,129.2,82.7
36,2023,Maharashtra,Pune,Women Safety,2550,23.9,110.1,75.9
37,2023,Gujarat,Surat,Women Safety,869,19.7,47.9,83.0
38,2024,Gujarat,Ahmedabad,Women Safety,1059,30.0,35.3,89.7
39,2024,Karnataka,Bengaluru,Women Safety,4748,40.6,117.0,70.5
40,2024,Tamil Nadu,Chennai,Women Safety,1093,43.1,25.4,93.9
41,2024,Tamil Nadu,Coimbatore,Women Safety,377,10.7,35.1,95.6
42,2024,Delhi,Delhi City,Women Safety,13396,75.8,176.8,73.6
43,2024,Uttar Pradesh,Ghaziabad,Women Safety,1265,11.0,114.8,65.8
44,2024,Telangana,Hyderabad,Women Safety,3255,37.6,86.5,76.3
45,2024,Madhya Pradesh,Indore,Women Safety,1884,10.4,181.5,76.2
46,2024,Rajasthan,Jaipur,Women Safety,2894,14.5,199.0,55.7
47,2024,Uttar Pradesh,Kanpur,Women Safety,1950,13.4,146.1,84.4
48,2024,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
49,2024,West Bengal,Kolkata,Women Safety,1958,67.9,28.8,98.5
50,2024,Kerala,Kozhikode,Women Safety,665,10.6,62.5,92.6
51,2024,Uttar Pradesh,Lucknow,Women Safety,2571,13.8,186.0,83.7
52,2024,Maharashtra,Mumbai,Women Safety,6358,85.2,74.6,81.4
53,2024,Maharashtra,Nagpur,Women Safety,1513,12.2,123.8,78.6
54,2024,Bihar,Patna,Women Safety,1239,9.6,129.2,82.7
55,2024,Maharashtra,Pune,Women Safety,2631,23.9,110.1,75.9
56,2024,Gujarat,Surat,Women Safety,945,19.7,47.9,83.0

In [95]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Women Safety,1452,30.0,35.3,89.7
1,2022,Karnataka,Bengaluru,Women Safety,3924,40.6,117.0,70.5
2,2022,Tamil Nadu,Chennai,Women Safety,736,43.1,25.4,93.9
3,2022,Tamil Nadu,Coimbatore,Women Safety,138,10.7,35.1,95.6
4,2022,Delhi,Delhi City,Women Safety,14158,75.8,176.8,73.6
5,2022,Uttar Pradesh,Ghaziabad,Women Safety,1063,11.0,114.8,65.8
6,2022,Telangana,Hyderabad,Women Safety,3145,37.6,86.5,76.3
7,2022,Madhya Pradesh,Indore,Women Safety,1809,10.4,181.5,76.2
8,2022,Rajasthan,Jaipur,Women Safety,3479,14.5,199.0,55.7
9,2022,Uttar Pradesh,Kanpur,Women Safety,2099,13.4,146.1,84.4
10,2022,Kerala,Kochi,Women Safety,754,10.8,72.8,91.2
11,2022,West Bengal,Kolkata,Women Safety,1890,67.9,28.8,98.5
12,2022,Kerala,Kozhikode,Women Safety,759,10.6,62.5,92.6
13,2022,Uttar Pradesh,Lucknow,Women Safety,2231,13.8,186.0,83.7
14,2022,Maharashtra,Mumbai,Women Safety,6176,85.2,74.6,81.4
15,2022,Maharashtra,Nagpur,Women Safety,1259,12.2,123.8,78.6
16,2022,Bihar,Patna,Women Safety,812,9.6,129.2,82.7
17,2022,Maharashtra,Pune,Women Safety,2074,23.9,110.1,75.9
18,2022,Gujarat,Surat,Women Safety,797,19.7,47.9,83.0
19,2023,Gujarat,Ahmedabad,Women Safety,1360,30.0,35.3,89.7
20,2023,Karnataka,Bengaluru,Women Safety,4870,40.6,117.0,70.5
21,2023,Tamil Nadu,Chennai,Women Safety,745,43.1,25.4,93.9
22,2023,Tamil Nadu,Coimbatore,Women Safety,244,10.7,35.1,95.6
23,2023,Delhi,Delhi City,Women Safety,13366,75.8,176.8,73.6
24,2023,Uttar Pradesh,Ghaziabad,Women Safety,904,11.0,114.8,65.8
25,2023,Telangana,Hyderabad,Women Safety,3822,37.6,86.5,76.3
26,2023,Madhya Pradesh,Indore,Women Safety,1919,10.4,181.5,76.2
27,2023,Rajasthan,Jaipur,Women Safety,3872,14.5,199.0,55.7
28,2023,Uttar Pradesh,Kanpur,Women Safety,2071,13.4,146.1,84.4
29,2023,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
30,2023,West Bengal,Kolkata,Women Safety,1746,67.9,28.8,98.5
31,2023,Kerala,Kozhikode,Women Safety,627,10.6,62.5,92.6
32,2023,Uttar Pradesh,Lucknow,Women Safety,2902,13.8,186.0,83.7
33,2023,Maharashtra,Mumbai,Women Safety,6025,85.2,74.6,81.4
34,2023,Maharashtra,Nagpur,Women Safety,1556,12.2,123.8,78.6
35,2023,Bihar,Patna,Women Safety,1162,9.6,129.2,82.7
36,2023,Maharashtra,Pune,Women Safety,2550,23.9,110.1,75.9
37,2023,Gujarat,Surat,Women Safety,869,19.7,47.9,83.0
38,2024,Gujarat,Ahmedabad,Women Safety,1059,30.0,35.3,89.7
39,2024,Karnataka,Bengaluru,Women Safety,4748,40.6,117.0,70.5
40,2024,Tamil Nadu,Chennai,Women Safety,1093,43.1,25.4,93.9
41,2024,Tamil Nadu,Coimbatore,Women Safety,377,10.7,35.1,95.6
42,2024,Delhi,Delhi City,Women Safety,13396,75.8,176.8,73.6
43,2024,Uttar Pradesh,Ghaziabad,Women Safety,1265,11.0,114.8,65.8
44,2024,Telangana,Hyderabad,Women Safety,3255,37.6,86.5,76.3
45,2024,Madhya Pradesh,Indore,Women Safety,1884,10.4,181.5,76.2
46,2024,Rajasthan,Jaipur,Women Safety,2894,14.5,199.0,55.7
47,2024,Uttar Pradesh,Kanpur,Women Safety,1950,13.4,146.1,84.4
48,2024,Kerala,Kochi,Women Safety,783,10.8,72.8,91.2
49,2024,West Bengal,Kolkata,Women Safety,1958,67.9,28.8,98.5
50,2024,Kerala,Kozhikode,Women Safety,665,10.6,62.5,92.6
51,2024,Uttar Pradesh,Lucknow,Women Safety,2571,13.8,186.0,83.7
52,2024,Maharashtra,Mumbai,Women Safety,6358,85.2,74.6,81.4
53,2024,Maharashtra,Nagpur,Women Safety,1513,12.2,123.8,78.6
54,2024,Bihar,Patna,Women Safety,1239,9.6,129.2,82.7
55,2024,Maharashtra,Pune,Women Safety,2631,23.9,110.1,75.9
56,2024,Gujarat,Surat,Women Safety,945,19.7,47.9,83.0

In [96]:
df_long.to_csv(
    "../cleaned data/master_women_safety.csv",
    index=False
)

**Economic Offences Dataset**

In [99]:
path3 = "../raw data/Metropolitan Cities - Economic Offences 2024(vol2-8b.1).xlsx"

In [101]:
df=pd.read_excel(path3,header=2)

df.head(20)

,SL,City,2022,2023,2024,Actual Population (Lakhs) 2011,Rate of Total Economic Offences (2024),Chargesheeting Rate (2024)
0,1,Ahmedabad (Gujarat),591.0,646.0,806.0,63.5,12.7,64.3
1,2,Bengaluru (Karnataka),3245.0,3858.0,3477.0,85.0,40.9,49.1
2,3,Chennai (Tamil Nadu),1038.0,2155.0,2436.0,87.0,28.0,42.5
3,4,Coimbatore (Tamil Nadu),261.0,499.0,660.0,21.5,30.7,59.8
4,5,Delhi City,5007.0,4580.0,4524.0,163.1,27.7,58.1
5,6,Ghaziabad (Uttar Pradesh),1024.0,1004.0,775.0,23.6,32.9,59.7
6,7,Hyderabad (Telangana),6015.0,5728.0,5839.0,77.5,75.4,30.6
7,8,Indore (Madhya Pradesh),562.0,553.0,295.0,21.7,13.6,74.2
8,9,Jaipur (Rajasthan),5332.0,5304.0,5471.0,30.7,178.0,17.4
9,10,Kanpur (Uttar Pradesh),595.0,629.0,463.0,29.2,15.9,75.4
10,11,Kochi (Kerala),445.0,869.0,1050.0,21.2,49.6,65.0
11,12,Kolkata (West Bengal),2013.0,1544.0,1825.0,141.1,12.9,92.4
12,13,Kozhikode (Kerala),191.0,422.0,469.0,20.3,23.1,42.3
13,14,Lucknow (Uttar Pradesh),3702.0,2446.0,1732.0,29.0,59.7,50.8
14,15,Mumbai (Maharashtra),6960.0,6476.0,7771.0,184.1,42.2,48.2
15,16,Nagpur (Maharashtra),550.0,697.0,748.0,25.0,29.9,31.5
16,17,Patna (Bihar),1532.0,1861.0,1402.0,20.5,68.5,92.2
17,18,Pune (Maharashtra),1023.0,1207.0,2125.0,50.5,42.1,56.1
18,19,Surat (Gujarat),674.0,742.0,879.0,45.8,19.2,78.4
19,NaN,TOTAL CITIES,40760.0,41220.0,42747.0,1140.4,37.5,51.1

In [102]:
df.columns

Index(['SL', 'City', '2022', '2023', '2024', 'Actual Population (Lakhs) 2011',
       'Rate of Total Economic Offences (2024)', 'Chargesheeting Rate (2024)'],
      dtype='object')

In [103]:
df = clean_column_names(df)

In [104]:
df = clean_year_columns(df)

In [105]:
df = remove_empty_rows(df)

In [106]:
df = remove_total_rows(df)

In [107]:
df= remove_unwanted_columns(df)

In [108]:
def melt_crime_data(df, category_name, rate_column):

    df_long = df.melt(
        id_vars=[
            'city',
            'actual_population_(lakhs)_2011',
            rate_column,
            'chargesheeting_rate_(2024)'
        ],
        value_vars=['2022', '2023', '2024'],
        var_name='year',
        value_name='cases'
    )

    # Standardize column names
    df_long.rename(columns={
        'actual_population_(lakhs)_2011': 'population_lakhs_2011',
        rate_column: 'crime_rate_2024',
        'chargesheeting_rate_(2024)': 'chargesheeting_rate_2024'
    }, inplace=True)

    df_long['category'] = category_name

    return df_long

In [109]:
df_long = melt_crime_data(
    df,
    'Economic Offences',
    'rate_of_total_economic_offences_(2024)'
)

In [110]:
df_long = extract_city_state(df_long)

In [111]:
df_long = final_cleaning(df_long)

In [112]:
df_long = df_long[
    [
        'year',
        'state',
        'city',
        'category',
        'cases',
        'population_lakhs_2011',
        'crime_rate_2024',
        'chargesheeting_rate_2024'
    ]
]

In [113]:
df_long.to_csv(
    "../cleaned data/master_economic_offences.csv",
    index=False
)

In [114]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Economic Offences,591.0,63.5,12.7,64.3
1,2022,Karnataka,Bengaluru,Economic Offences,3245.0,85.0,40.9,49.1
2,2022,Tamil Nadu,Chennai,Economic Offences,1038.0,87.0,28.0,42.5
3,2022,Tamil Nadu,Coimbatore,Economic Offences,261.0,21.5,30.7,59.8
4,2022,Delhi,Delhi City,Economic Offences,5007.0,163.1,27.7,58.1
5,2022,Uttar Pradesh,Ghaziabad,Economic Offences,1024.0,23.6,32.9,59.7
6,2022,Telangana,Hyderabad,Economic Offences,6015.0,77.5,75.4,30.6
7,2022,Madhya Pradesh,Indore,Economic Offences,562.0,21.7,13.6,74.2
8,2022,Rajasthan,Jaipur,Economic Offences,5332.0,30.7,178.0,17.4
9,2022,Uttar Pradesh,Kanpur,Economic Offences,595.0,29.2,15.9,75.4
10,2022,Kerala,Kochi,Economic Offences,445.0,21.2,49.6,65.0
11,2022,West Bengal,Kolkata,Economic Offences,2013.0,141.1,12.9,92.4
12,2022,Kerala,Kozhikode,Economic Offences,191.0,20.3,23.1,42.3
13,2022,Uttar Pradesh,Lucknow,Economic Offences,3702.0,29.0,59.7,50.8
14,2022,Maharashtra,Mumbai,Economic Offences,6960.0,184.1,42.2,48.2
15,2022,Maharashtra,Nagpur,Economic Offences,550.0,25.0,29.9,31.5
16,2022,Bihar,Patna,Economic Offences,1532.0,20.5,68.5,92.2
17,2022,Maharashtra,Pune,Economic Offences,1023.0,50.5,42.1,56.1
18,2022,Gujarat,Surat,Economic Offences,674.0,45.8,19.2,78.4
19,2023,Gujarat,Ahmedabad,Economic Offences,646.0,63.5,12.7,64.3
20,2023,Karnataka,Bengaluru,Economic Offences,3858.0,85.0,40.9,49.1
21,2023,Tamil Nadu,Chennai,Economic Offences,2155.0,87.0,28.0,42.5
22,2023,Tamil Nadu,Coimbatore,Economic Offences,499.0,21.5,30.7,59.8
23,2023,Delhi,Delhi City,Economic Offences,4580.0,163.1,27.7,58.1
24,2023,Uttar Pradesh,Ghaziabad,Economic Offences,1004.0,23.6,32.9,59.7
25,2023,Telangana,Hyderabad,Economic Offences,5728.0,77.5,75.4,30.6
26,2023,Madhya Pradesh,Indore,Economic Offences,553.0,21.7,13.6,74.2
27,2023,Rajasthan,Jaipur,Economic Offences,5304.0,30.7,178.0,17.4
28,2023,Uttar Pradesh,Kanpur,Economic Offences,629.0,29.2,15.9,75.4
29,2023,Kerala,Kochi,Economic Offences,869.0,21.2,49.6,65.0
30,2023,West Bengal,Kolkata,Economic Offences,1544.0,141.1,12.9,92.4
31,2023,Kerala,Kozhikode,Economic Offences,422.0,20.3,23.1,42.3
32,2023,Uttar Pradesh,Lucknow,Economic Offences,2446.0,29.0,59.7,50.8
33,2023,Maharashtra,Mumbai,Economic Offences,6476.0,184.1,42.2,48.2
34,2023,Maharashtra,Nagpur,Economic Offences,697.0,25.0,29.9,31.5
35,2023,Bihar,Patna,Economic Offences,1861.0,20.5,68.5,92.2
36,2023,Maharashtra,Pune,Economic Offences,1207.0,50.5,42.1,56.1
37,2023,Gujarat,Surat,Economic Offences,742.0,45.8,19.2,78.4
38,2024,Gujarat,Ahmedabad,Economic Offences,806.0,63.5,12.7,64.3
39,2024,Karnataka,Bengaluru,Economic Offences,3477.0,85.0,40.9,49.1
40,2024,Tamil Nadu,Chennai,Economic Offences,2436.0,87.0,28.0,42.5
41,2024,Tamil Nadu,Coimbatore,Economic Offences,660.0,21.5,30.7,59.8
42,2024,Delhi,Delhi City,Economic Offences,4524.0,163.1,27.7,58.1
43,2024,Uttar Pradesh,Ghaziabad,Economic Offences,775.0,23.6,32.9,59.7
44,2024,Telangana,Hyderabad,Economic Offences,5839.0,77.5,75.4,30.6
45,2024,Madhya Pradesh,Indore,Economic Offences,295.0,21.7,13.6,74.2
46,2024,Rajasthan,Jaipur,Economic Offences,5471.0,30.7,178.0,17.4
47,2024,Uttar Pradesh,Kanpur,Economic Offences,463.0,29.2,15.9,75.4
48,2024,Kerala,Kochi,Economic Offences,1050.0,21.2,49.6,65.0
49,2024,West Bengal,Kolkata,Economic Offences,1825.0,141.1,12.9,92.4
50,2024,Kerala,Kozhikode,Economic Offences,469.0,20.3,23.1,42.3
51,2024,Uttar Pradesh,Lucknow,Economic Offences,1732.0,29.0,59.7,50.8
52,2024,Maharashtra,Mumbai,Economic Offences,7771.0,184.1,42.2,48.2
53,2024,Maharashtra,Nagpur,Economic Offences,748.0,25.0,29.9,31.5
54,2024,Bihar,Patna,Economic Offences,1402.0,20.5,68.5,92.2
55,2024,Maharashtra,Pune,Economic Offences,2125.0,50.5,42.1,56.1
56,2024,Gujarat,Surat,Economic Offences,879.0,45.8,19.2,78.4

**Crime Against Children**

In [115]:
path4 = '../raw data/Metropolitan Cities - Crime Against Children(table_4b.1).xlsx'

In [116]:
df = pd.read_excel(path4,header=1)

df.head(20)

,SL,City,2022,2023,2024,Chargesheeting Rate (2024)
0,1.0,Ahmedabad (Gujarat),829,832,942,82.9
1,2.0,Bengaluru (Karnataka),1578,1982,2026,37.0
2,3.0,Chennai (Tamil Nadu),514,573,719,96.0
3,4.0,Coimbatore (Tamil Nadu),83,193,243,96.2
4,5.0,Delhi City,7400,7731,7662,31.7
5,6.0,Ghaziabad (Uttar Pradesh),189,208,713,47.4
6,7.0,Hyderabad (Telangana),645,692,920,59.3
7,8.0,Indore (Madhya Pradesh),1082,1236,1157,46.3
8,9.0,Jaipur (Rajasthan),980,1099,863,33.9
9,10.0,Kanpur (Uttar Pradesh),437,426,379,79.2
10,11.0,Kochi (Kerala),206,230,267,91.1
11,12.0,Kolkata (West Bengal),602,297,468,99.6
12,13.0,Kozhikode (Kerala),265,250,245,86.7
13,14.0,Lucknow (Uttar Pradesh),398,844,880,59.9
14,15.0,Mumbai (Maharashtra),3178,3110,3374,52.3
15,16.0,Nagpur (Maharashtra),765,802,977,42.6
16,17.0,Patna (Bihar),127,144,653,72.7
17,18.0,Pune (Maharashtra),732,1234,1330,57.7
18,19.0,Surat (Gujarat),540,550,559,52.9
19,NaN,TOTAL CITIES,20550,22433,24377,49.6

In [117]:
df = clean_column_names(df)

In [118]:
df = clean_year_columns(df)

In [119]:
df=remove_total_rows(df)

In [120]:
df= remove_unwanted_columns(df)

In [121]:
df = remove_empty_rows(df)

In [122]:
df

                         city  2022  2023  2024  chargesheeting_rate_(2024)
0         Ahmedabad (Gujarat)   829   832   942                        82.9
1       Bengaluru (Karnataka)  1578  1982  2026                        37.0
2        Chennai (Tamil Nadu)   514   573   719                        96.0
3     Coimbatore (Tamil Nadu)    83   193   243                        96.2
4                  Delhi City  7400  7731  7662                        31.7
5   Ghaziabad (Uttar Pradesh)   189   208   713                        47.4
6       Hyderabad (Telangana)   645   692   920                        59.3
7     Indore (Madhya Pradesh)  1082  1236  1157                        46.3
8          Jaipur (Rajasthan)   980  1099   863                        33.9
9      Kanpur (Uttar Pradesh)   437   426   379                        79.2
10             Kochi (Kerala)   206   230   267                        91.1
11      Kolkata (West Bengal)   602   297   468                        99.6
12         Kozhikode (Kerala)   265   250   245                        86.7
13    Lucknow (Uttar Pradesh)   398   844   880                        59.9
14       Mumbai (Maharashtra)  3178  3110  3374                        52.3
15       Nagpur (Maharashtra)   765   802   977                        42.6
16              Patna (Bihar)   127   144   653                        72.7
17         Pune (Maharashtra)   732  1234  1330                        57.7
18            Surat (Gujarat)   540   550   559                        52.9

In [123]:
df_long = df.melt(
    id_vars=['city','chargesheeting_rate_(2024)'],
    value_vars=['2022','2023','2024'],
    var_name= 'year',
    value_name='cases')

In [124]:
df_long = df_long.rename(columns={'chargesheeting_rate_(2024)':'chargesheeting_rate_2024'})

In [125]:
df_long['category'] = 'children'

In [126]:
df_long

                         city  chargesheeting_rate_2024  year  cases  category
0         Ahmedabad (Gujarat)                      82.9  2022    829  children
1       Bengaluru (Karnataka)                      37.0  2022   1578  children
2        Chennai (Tamil Nadu)                      96.0  2022    514  children
3     Coimbatore (Tamil Nadu)                      96.2  2022     83  children
4                  Delhi City                      31.7  2022   7400  children
5   Ghaziabad (Uttar Pradesh)                      47.4  2022    189  children
6       Hyderabad (Telangana)                      59.3  2022    645  children
7     Indore (Madhya Pradesh)                      46.3  2022   1082  children
8          Jaipur (Rajasthan)                      33.9  2022    980  children
9      Kanpur (Uttar Pradesh)                      79.2  2022    437  children
10             Kochi (Kerala)                      91.1  2022    206  children
11      Kolkata (West Bengal)                      99.6  2022    602  children
12         Kozhikode (Kerala)                      86.7  2022    265  children
13    Lucknow (Uttar Pradesh)                      59.9  2022    398  children
14       Mumbai (Maharashtra)                      52.3  2022   3178  children
15       Nagpur (Maharashtra)                      42.6  2022    765  children
16              Patna (Bihar)                      72.7  2022    127  children
17         Pune (Maharashtra)                      57.7  2022    732  children
18            Surat (Gujarat)                      52.9  2022    540  children
19        Ahmedabad (Gujarat)                      82.9  2023    832  children
20      Bengaluru (Karnataka)                      37.0  2023   1982  children
21       Chennai (Tamil Nadu)                      96.0  2023    573  children
22    Coimbatore (Tamil Nadu)                      96.2  2023    193  children
23                 Delhi City                      31.7  2023   7731  children
24  Ghaziabad (Uttar Pradesh)                      47.4  2023    208  children
25      Hyderabad (Telangana)                      59.3  2023    692  children
26    Indore (Madhya Pradesh)                      46.3  2023   1236  children
27         Jaipur (Rajasthan)                      33.9  2023   1099  children
28     Kanpur (Uttar Pradesh)                      79.2  2023    426  children
29             Kochi (Kerala)                      91.1  2023    230  children
30      Kolkata (West Bengal)                      99.6  2023    297  children
31         Kozhikode (Kerala)                      86.7  2023    250  children
32    Lucknow (Uttar Pradesh)                      59.9  2023    844  children
33       Mumbai (Maharashtra)                      52.3  2023   3110  children
34       Nagpur (Maharashtra)                      42.6  2023    802  children
35              Patna (Bihar)                      72.7  2023    144  children
36         Pune (Maharashtra)                      57.7  2023   1234  children
37            Surat (Gujarat)                      52.9  2023    550  children
38        Ahmedabad (Gujarat)                      82.9  2024    942  children
39      Bengaluru (Karnataka)                      37.0  2024   2026  children
40       Chennai (Tamil Nadu)                      96.0  2024    719  children
41    Coimbatore (Tamil Nadu)                      96.2  2024    243  children
42                 Delhi City                      31.7  2024   7662  children
43  Ghaziabad (Uttar Pradesh)                      47.4  2024    713  children
44      Hyderabad (Telangana)                      59.3  2024    920  children
45    Indore (Madhya Pradesh)                      46.3  2024   1157  children
46         Jaipur (Rajasthan)                      33.9  2024    863  children
47     Kanpur (Uttar Pradesh)                      79.2  2024    379  children
48             Kochi (Kerala)                      91.1  2024    267  children
49      Kolkata (West Bengal)                      99.6  2024    468  children
50         Kozhikode (Kerala)                      86.7  2024    245  children
51    Lucknow (Uttar Pradesh)                      59.9  2024    880  children
52       Mumbai (Maharashtra)                      52.3  2024   3374  children
53       Nagpur (Maharashtra)                      42.6  2024    977  children
54              Patna (Bihar)                      72.7  2024    653  children
55         Pune (Maharashtra)                      57.7  2024   1330  children
56            Surat (Gujarat)                      52.9  2024    559  children

In [127]:
df_long= extract_city_state(df_long)
df_long

,city,chargesheeting_rate_2024,year,cases,category,state
0,Ahmedabad,82.9,2022,829,children,Gujarat
1,Bengaluru,37.0,2022,1578,children,Karnataka
2,Chennai,96.0,2022,514,children,Tamil Nadu
3,Coimbatore,96.2,2022,83,children,Tamil Nadu
4,Delhi City,31.7,2022,7400,children,Delhi
5,Ghaziabad,47.4,2022,189,children,Uttar Pradesh
6,Hyderabad,59.3,2022,645,children,Telangana
7,Indore,46.3,2022,1082,children,Madhya Pradesh
8,Jaipur,33.9,2022,980,children,Rajasthan
9,Kanpur,79.2,2022,437,children,Uttar Pradesh
10,Kochi,91.1,2022,206,children,Kerala
11,Kolkata,99.6,2022,602,children,West Bengal
12,Kozhikode,86.7,2022,265,children,Kerala
13,Lucknow,59.9,2022,398,children,Uttar Pradesh
14,Mumbai,52.3,2022,3178,children,Maharashtra
15,Nagpur,42.6,2022,765,children,Maharashtra
16,Patna,72.7,2022,127,children,Bihar
17,Pune,57.7,2022,732,children,Maharashtra
18,Surat,52.9,2022,540,children,Gujarat
19,Ahmedabad,82.9,2023,832,children,Gujarat
20,Bengaluru,37.0,2023,1982,children,Karnataka
21,Chennai,96.0,2023,573,children,Tamil Nadu
22,Coimbatore,96.2,2023,193,children,Tamil Nadu
23,Delhi City,31.7,2023,7731,children,Delhi
24,Ghaziabad,47.4,2023,208,children,Uttar Pradesh
25,Hyderabad,59.3,2023,692,children,Telangana
26,Indore,46.3,2023,1236,children,Madhya Pradesh
27,Jaipur,33.9,2023,1099,children,Rajasthan
28,Kanpur,79.2,2023,426,children,Uttar Pradesh
29,Kochi,91.1,2023,230,children,Kerala
30,Kolkata,99.6,2023,297,children,West Bengal
31,Kozhikode,86.7,2023,250,children,Kerala
32,Lucknow,59.9,2023,844,children,Uttar Pradesh
33,Mumbai,52.3,2023,3110,children,Maharashtra
34,Nagpur,42.6,2023,802,children,Maharashtra
35,Patna,72.7,2023,144,children,Bihar
36,Pune,57.7,2023,1234,children,Maharashtra
37,Surat,52.9,2023,550,children,Gujarat
38,Ahmedabad,82.9,2024,942,children,Gujarat
39,Bengaluru,37.0,2024,2026,children,Karnataka
40,Chennai,96.0,2024,719,children,Tamil Nadu
41,Coimbatore,96.2,2024,243,children,Tamil Nadu
42,Delhi City,31.7,2024,7662,children,Delhi
43,Ghaziabad,47.4,2024,713,children,Uttar Pradesh
44,Hyderabad,59.3,2024,920,children,Telangana
45,Indore,46.3,2024,1157,children,Madhya Pradesh
46,Jaipur,33.9,2024,863,children,Rajasthan
47,Kanpur,79.2,2024,379,children,Uttar Pradesh
48,Kochi,91.1,2024,267,children,Kerala
49,Kolkata,99.6,2024,468,children,West Bengal
50,Kozhikode,86.7,2024,245,children,Kerala
51,Lucknow,59.9,2024,880,children,Uttar Pradesh
52,Mumbai,52.3,2024,3374,children,Maharashtra
53,Nagpur,42.6,2024,977,children,Maharashtra
54,Patna,72.7,2024,653,children,Bihar
55,Pune,57.7,2024,1330,children,Maharashtra
56,Surat,52.9,2024,559,children,Gujarat

In [128]:
df_long=df_long[
    [
        'year','state','city','category','cases','chargesheeting_rate_2024']]

In [129]:
df_long

,year,state,city,category,cases,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,children,829,82.9
1,2022,Karnataka,Bengaluru,children,1578,37.0
2,2022,Tamil Nadu,Chennai,children,514,96.0
3,2022,Tamil Nadu,Coimbatore,children,83,96.2
4,2022,Delhi,Delhi City,children,7400,31.7
5,2022,Uttar Pradesh,Ghaziabad,children,189,47.4
6,2022,Telangana,Hyderabad,children,645,59.3
7,2022,Madhya Pradesh,Indore,children,1082,46.3
8,2022,Rajasthan,Jaipur,children,980,33.9
9,2022,Uttar Pradesh,Kanpur,children,437,79.2
10,2022,Kerala,Kochi,children,206,91.1
11,2022,West Bengal,Kolkata,children,602,99.6
12,2022,Kerala,Kozhikode,children,265,86.7
13,2022,Uttar Pradesh,Lucknow,children,398,59.9
14,2022,Maharashtra,Mumbai,children,3178,52.3
15,2022,Maharashtra,Nagpur,children,765,42.6
16,2022,Bihar,Patna,children,127,72.7
17,2022,Maharashtra,Pune,children,732,57.7
18,2022,Gujarat,Surat,children,540,52.9
19,2023,Gujarat,Ahmedabad,children,832,82.9
20,2023,Karnataka,Bengaluru,children,1982,37.0
21,2023,Tamil Nadu,Chennai,children,573,96.0
22,2023,Tamil Nadu,Coimbatore,children,193,96.2
23,2023,Delhi,Delhi City,children,7731,31.7
24,2023,Uttar Pradesh,Ghaziabad,children,208,47.4
25,2023,Telangana,Hyderabad,children,692,59.3
26,2023,Madhya Pradesh,Indore,children,1236,46.3
27,2023,Rajasthan,Jaipur,children,1099,33.9
28,2023,Uttar Pradesh,Kanpur,children,426,79.2
29,2023,Kerala,Kochi,children,230,91.1
30,2023,West Bengal,Kolkata,children,297,99.6
31,2023,Kerala,Kozhikode,children,250,86.7
32,2023,Uttar Pradesh,Lucknow,children,844,59.9
33,2023,Maharashtra,Mumbai,children,3110,52.3
34,2023,Maharashtra,Nagpur,children,802,42.6
35,2023,Bihar,Patna,children,144,72.7
36,2023,Maharashtra,Pune,children,1234,57.7
37,2023,Gujarat,Surat,children,550,52.9
38,2024,Gujarat,Ahmedabad,children,942,82.9
39,2024,Karnataka,Bengaluru,children,2026,37.0
40,2024,Tamil Nadu,Chennai,children,719,96.0
41,2024,Tamil Nadu,Coimbatore,children,243,96.2
42,2024,Delhi,Delhi City,children,7662,31.7
43,2024,Uttar Pradesh,Ghaziabad,children,713,47.4
44,2024,Telangana,Hyderabad,children,920,59.3
45,2024,Madhya Pradesh,Indore,children,1157,46.3
46,2024,Rajasthan,Jaipur,children,863,33.9
47,2024,Uttar Pradesh,Kanpur,children,379,79.2
48,2024,Kerala,Kochi,children,267,91.1
49,2024,West Bengal,Kolkata,children,468,99.6
50,2024,Kerala,Kozhikode,children,245,86.7
51,2024,Uttar Pradesh,Lucknow,children,880,59.9
52,2024,Maharashtra,Mumbai,children,3374,52.3
53,2024,Maharashtra,Nagpur,children,977,42.6
54,2024,Bihar,Patna,children,653,72.7
55,2024,Maharashtra,Pune,children,1330,57.7
56,2024,Gujarat,Surat,children,559,52.9

In [130]:
df_long.to_csv("../cleaned data/mastered_children.csv",index= False)

**Crime Against SC**

In [133]:
path5 = "../raw data/Metropolitan Cities - Crime Against SCs (vol2-7b.1).xlsx"

In [134]:
df = pd.read_excel(path5,header=2)

In [747]:
df.head(10)

,SL,City,2022,2023,2024,Chargesheeting Rate (2024)
0,1,Ahmedabad (Gujarat),189.0,177.0,126.0,95.9
1,2,Bengaluru (Karnataka),231.0,285.0,280.0,73.9
2,3,Chennai (Tamil Nadu),25.0,24.0,34.0,53.7
3,4,Coimbatore (Tamil Nadu),21.0,8.0,18.0,84.2
4,5,Delhi City,129.0,126.0,133.0,95.5
5,6,Ghaziabad (Uttar Pradesh),72.0,63.0,52.0,92.3
6,7,Hyderabad (Telangana),113.0,134.0,153.0,65.9
7,8,Indore (Madhya Pradesh),47.0,46.0,28.0,97.4
8,9,Jaipur (Rajasthan),381.0,489.0,396.0,31.4
9,10,Kanpur (Uttar Pradesh),376.0,263.0,271.0,89.4

In [748]:
df = clean_column_names(df)
df

,sl,city,2022,2023,2024,chargesheeting_rate_(2024)
0,1,Ahmedabad (Gujarat),189.0,177.0,126.0,95.9
1,2,Bengaluru (Karnataka),231.0,285.0,280.0,73.9
2,3,Chennai (Tamil Nadu),25.0,24.0,34.0,53.7
3,4,Coimbatore (Tamil Nadu),21.0,8.0,18.0,84.2
4,5,Delhi City,129.0,126.0,133.0,95.5
5,6,Ghaziabad (Uttar Pradesh),72.0,63.0,52.0,92.3
6,7,Hyderabad (Telangana),113.0,134.0,153.0,65.9
7,8,Indore (Madhya Pradesh),47.0,46.0,28.0,97.4
8,9,Jaipur (Rajasthan),381.0,489.0,396.0,31.4
9,10,Kanpur (Uttar Pradesh),376.0,263.0,271.0,89.4
10,11,Kochi (Kerala),22.0,43.0,42.0,62.5
11,12,Kolkata (West Bengal),10.0,10.0,7.0,-
12,13,Kozhikode (Kerala),27.0,30.0,23.0,68.8
13,14,Lucknow (Uttar Pradesh),420.0,517.0,490.0,84.4
14,15,Mumbai (Maharashtra),58.0,52.0,62.0,80.4
15,16,Nagpur (Maharashtra),35.0,40.0,66.0,96.8
16,17,Patna (Bihar),96.0,105.0,253.0,100
17,18,Pune (Maharashtra),61.0,70.0,121.0,100
18,19,Surat (Gujarat),34.0,38.0,51.0,95.7
19,NaN,TOTAL CITIES,2347.0,2520.0,2606.0,76.7
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [749]:
df = clean_year_columns(df)

In [750]:
df

,sl,city,2022,2023,2024,chargesheeting_rate_(2024)
0,1,Ahmedabad (Gujarat),189.0,177.0,126.0,95.9
1,2,Bengaluru (Karnataka),231.0,285.0,280.0,73.9
2,3,Chennai (Tamil Nadu),25.0,24.0,34.0,53.7
3,4,Coimbatore (Tamil Nadu),21.0,8.0,18.0,84.2
4,5,Delhi City,129.0,126.0,133.0,95.5
5,6,Ghaziabad (Uttar Pradesh),72.0,63.0,52.0,92.3
6,7,Hyderabad (Telangana),113.0,134.0,153.0,65.9
7,8,Indore (Madhya Pradesh),47.0,46.0,28.0,97.4
8,9,Jaipur (Rajasthan),381.0,489.0,396.0,31.4
9,10,Kanpur (Uttar Pradesh),376.0,263.0,271.0,89.4
10,11,Kochi (Kerala),22.0,43.0,42.0,62.5
11,12,Kolkata (West Bengal),10.0,10.0,7.0,-
12,13,Kozhikode (Kerala),27.0,30.0,23.0,68.8
13,14,Lucknow (Uttar Pradesh),420.0,517.0,490.0,84.4
14,15,Mumbai (Maharashtra),58.0,52.0,62.0,80.4
15,16,Nagpur (Maharashtra),35.0,40.0,66.0,96.8
16,17,Patna (Bihar),96.0,105.0,253.0,100
17,18,Pune (Maharashtra),61.0,70.0,121.0,100
18,19,Surat (Gujarat),34.0,38.0,51.0,95.7
19,NaN,TOTAL CITIES,2347.0,2520.0,2606.0,76.7
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [751]:
df = remove_unwanted_columns(df)
df

,city,2022,2023,2024,chargesheeting_rate_(2024)
0,Ahmedabad (Gujarat),189.0,177.0,126.0,95.9
1,Bengaluru (Karnataka),231.0,285.0,280.0,73.9
2,Chennai (Tamil Nadu),25.0,24.0,34.0,53.7
3,Coimbatore (Tamil Nadu),21.0,8.0,18.0,84.2
4,Delhi City,129.0,126.0,133.0,95.5
5,Ghaziabad (Uttar Pradesh),72.0,63.0,52.0,92.3
6,Hyderabad (Telangana),113.0,134.0,153.0,65.9
7,Indore (Madhya Pradesh),47.0,46.0,28.0,97.4
8,Jaipur (Rajasthan),381.0,489.0,396.0,31.4
9,Kanpur (Uttar Pradesh),376.0,263.0,271.0,89.4
10,Kochi (Kerala),22.0,43.0,42.0,62.5
11,Kolkata (West Bengal),10.0,10.0,7.0,-
12,Kozhikode (Kerala),27.0,30.0,23.0,68.8
13,Lucknow (Uttar Pradesh),420.0,517.0,490.0,84.4
14,Mumbai (Maharashtra),58.0,52.0,62.0,80.4
15,Nagpur (Maharashtra),35.0,40.0,66.0,96.8
16,Patna (Bihar),96.0,105.0,253.0,100
17,Pune (Maharashtra),61.0,70.0,121.0,100
18,Surat (Gujarat),34.0,38.0,51.0,95.7
19,TOTAL CITIES,2347.0,2520.0,2606.0,76.7
20,NaN,NaN,NaN,NaN,NaN

In [752]:
df = remove_empty_rows(df)

In [753]:
df= remove_total_rows(df)
df

                         city   2022   2023   2024 chargesheeting_rate_(2024)
0         Ahmedabad (Gujarat)  189.0  177.0  126.0                       95.9
1       Bengaluru (Karnataka)  231.0  285.0  280.0                       73.9
2        Chennai (Tamil Nadu)   25.0   24.0   34.0                       53.7
3     Coimbatore (Tamil Nadu)   21.0    8.0   18.0                       84.2
4                  Delhi City  129.0  126.0  133.0                       95.5
5   Ghaziabad (Uttar Pradesh)   72.0   63.0   52.0                       92.3
6       Hyderabad (Telangana)  113.0  134.0  153.0                       65.9
7     Indore (Madhya Pradesh)   47.0   46.0   28.0                       97.4
8          Jaipur (Rajasthan)  381.0  489.0  396.0                       31.4
9      Kanpur (Uttar Pradesh)  376.0  263.0  271.0                       89.4
10             Kochi (Kerala)   22.0   43.0   42.0                       62.5
11      Kolkata (West Bengal)   10.0   10.0    7.0                          -
12         Kozhikode (Kerala)   27.0   30.0   23.0                       68.8
13    Lucknow (Uttar Pradesh)  420.0  517.0  490.0                       84.4
14       Mumbai (Maharashtra)   58.0   52.0   62.0                       80.4
15       Nagpur (Maharashtra)   35.0   40.0   66.0                       96.8
16              Patna (Bihar)   96.0  105.0  253.0                        100
17         Pune (Maharashtra)   61.0   70.0  121.0                        100
18            Surat (Gujarat)   34.0   38.0   51.0                       95.7

In [754]:
df_long = df.melt(
    id_vars=['city', 'chargesheeting_rate_(2024)'], 
    value_vars=['2022', '2023', '2024'], 
    var_name='year',   
    value_name='cases' 
)

In [755]:
df_long

                         city chargesheeting_rate_(2024)  year  cases
0         Ahmedabad (Gujarat)                       95.9  2022  189.0
1       Bengaluru (Karnataka)                       73.9  2022  231.0
2        Chennai (Tamil Nadu)                       53.7  2022   25.0
3     Coimbatore (Tamil Nadu)                       84.2  2022   21.0
4                  Delhi City                       95.5  2022  129.0
5   Ghaziabad (Uttar Pradesh)                       92.3  2022   72.0
6       Hyderabad (Telangana)                       65.9  2022  113.0
7     Indore (Madhya Pradesh)                       97.4  2022   47.0
8          Jaipur (Rajasthan)                       31.4  2022  381.0
9      Kanpur (Uttar Pradesh)                       89.4  2022  376.0
10             Kochi (Kerala)                       62.5  2022   22.0
11      Kolkata (West Bengal)                          -  2022   10.0
12         Kozhikode (Kerala)                       68.8  2022   27.0
13    Lucknow (Uttar Pradesh)                       84.4  2022  420.0
14       Mumbai (Maharashtra)                       80.4  2022   58.0
15       Nagpur (Maharashtra)                       96.8  2022   35.0
16              Patna (Bihar)                        100  2022   96.0
17         Pune (Maharashtra)                        100  2022   61.0
18            Surat (Gujarat)                       95.7  2022   34.0
19        Ahmedabad (Gujarat)                       95.9  2023  177.0
20      Bengaluru (Karnataka)                       73.9  2023  285.0
21       Chennai (Tamil Nadu)                       53.7  2023   24.0
22    Coimbatore (Tamil Nadu)                       84.2  2023    8.0
23                 Delhi City                       95.5  2023  126.0
24  Ghaziabad (Uttar Pradesh)                       92.3  2023   63.0
25      Hyderabad (Telangana)                       65.9  2023  134.0
26    Indore (Madhya Pradesh)                       97.4  2023   46.0
27         Jaipur (Rajasthan)                       31.4  2023  489.0
28     Kanpur (Uttar Pradesh)                       89.4  2023  263.0
29             Kochi (Kerala)                       62.5  2023   43.0
30      Kolkata (West Bengal)                          -  2023   10.0
31         Kozhikode (Kerala)                       68.8  2023   30.0
32    Lucknow (Uttar Pradesh)                       84.4  2023  517.0
33       Mumbai (Maharashtra)                       80.4  2023   52.0
34       Nagpur (Maharashtra)                       96.8  2023   40.0
35              Patna (Bihar)                        100  2023  105.0
36         Pune (Maharashtra)                        100  2023   70.0
37            Surat (Gujarat)                       95.7  2023   38.0
38        Ahmedabad (Gujarat)                       95.9  2024  126.0
39      Bengaluru (Karnataka)                       73.9  2024  280.0
40       Chennai (Tamil Nadu)                       53.7  2024   34.0
41    Coimbatore (Tamil Nadu)                       84.2  2024   18.0
42                 Delhi City                       95.5  2024  133.0
43  Ghaziabad (Uttar Pradesh)                       92.3  2024   52.0
44      Hyderabad (Telangana)                       65.9  2024  153.0
45    Indore (Madhya Pradesh)                       97.4  2024   28.0
46         Jaipur (Rajasthan)                       31.4  2024  396.0
47     Kanpur (Uttar Pradesh)                       89.4  2024  271.0
48             Kochi (Kerala)                       62.5  2024   42.0
49      Kolkata (West Bengal)                          -  2024    7.0
50         Kozhikode (Kerala)                       68.8  2024   23.0
51    Lucknow (Uttar Pradesh)                       84.4  2024  490.0
52       Mumbai (Maharashtra)                       80.4  2024   62.0
53       Nagpur (Maharashtra)                       96.8  2024   66.0
54              Patna (Bihar)                        100  2024  253.0
55         Pune (Maharashtra)                        100  2024  121.0
56            Surat (Gujarat)                       95.7  2024   51.0

In [756]:
df_long = extract_city_state(df_long)

In [757]:
df_long

          city chargesheeting_rate_(2024)  year  cases           state
0    Ahmedabad                       95.9  2022  189.0         Gujarat
1    Bengaluru                       73.9  2022  231.0       Karnataka
2      Chennai                       53.7  2022   25.0      Tamil Nadu
3   Coimbatore                       84.2  2022   21.0      Tamil Nadu
4   Delhi City                       95.5  2022  129.0           Delhi
5    Ghaziabad                       92.3  2022   72.0   Uttar Pradesh
6    Hyderabad                       65.9  2022  113.0       Telangana
7       Indore                       97.4  2022   47.0  Madhya Pradesh
8       Jaipur                       31.4  2022  381.0       Rajasthan
9       Kanpur                       89.4  2022  376.0   Uttar Pradesh
10       Kochi                       62.5  2022   22.0          Kerala
11     Kolkata                          -  2022   10.0     West Bengal
12   Kozhikode                       68.8  2022   27.0          Kerala
13     Lucknow                       84.4  2022  420.0   Uttar Pradesh
14      Mumbai                       80.4  2022   58.0     Maharashtra
15      Nagpur                       96.8  2022   35.0     Maharashtra
16       Patna                        100  2022   96.0           Bihar
17        Pune                        100  2022   61.0     Maharashtra
18       Surat                       95.7  2022   34.0         Gujarat
19   Ahmedabad                       95.9  2023  177.0         Gujarat
20   Bengaluru                       73.9  2023  285.0       Karnataka
21     Chennai                       53.7  2023   24.0      Tamil Nadu
22  Coimbatore                       84.2  2023    8.0      Tamil Nadu
23  Delhi City                       95.5  2023  126.0           Delhi
24   Ghaziabad                       92.3  2023   63.0   Uttar Pradesh
25   Hyderabad                       65.9  2023  134.0       Telangana
26      Indore                       97.4  2023   46.0  Madhya Pradesh
27      Jaipur                       31.4  2023  489.0       Rajasthan
28      Kanpur                       89.4  2023  263.0   Uttar Pradesh
29       Kochi                       62.5  2023   43.0          Kerala
30     Kolkata                          -  2023   10.0     West Bengal
31   Kozhikode                       68.8  2023   30.0          Kerala
32     Lucknow                       84.4  2023  517.0   Uttar Pradesh
33      Mumbai                       80.4  2023   52.0     Maharashtra
34      Nagpur                       96.8  2023   40.0     Maharashtra
35       Patna                        100  2023  105.0           Bihar
36        Pune                        100  2023   70.0     Maharashtra
37       Surat                       95.7  2023   38.0         Gujarat
38   Ahmedabad                       95.9  2024  126.0         Gujarat
39   Bengaluru                       73.9  2024  280.0       Karnataka
40     Chennai                       53.7  2024   34.0      Tamil Nadu
41  Coimbatore                       84.2  2024   18.0      Tamil Nadu
42  Delhi City                       95.5  2024  133.0           Delhi
43   Ghaziabad                       92.3  2024   52.0   Uttar Pradesh
44   Hyderabad                       65.9  2024  153.0       Telangana
45      Indore                       97.4  2024   28.0  Madhya Pradesh
46      Jaipur                       31.4  2024  396.0       Rajasthan
47      Kanpur                       89.4  2024  271.0   Uttar Pradesh
48       Kochi                       62.5  2024   42.0          Kerala
49     Kolkata                          -  2024    7.0     West Bengal
50   Kozhikode                       68.8  2024   23.0          Kerala
51     Lucknow                       84.4  2024  490.0   Uttar Pradesh
52      Mumbai                       80.4  2024   62.0     Maharashtra
53      Nagpur                       96.8  2024   66.0     Maharashtra
54       Patna                        100  2024  253.0           Bihar
55        Pune                        100  2024  121.0     Maharashtra
56       Surat                       95.7  2024   51.0         Gujarat

In [758]:
df_long = df_long.rename(columns={'chargesheeting_rate_(2024)':'chargesheeting_rate_2024'})
df_long

          city chargesheeting_rate_2024  year  cases           state
0    Ahmedabad                     95.9  2022  189.0         Gujarat
1    Bengaluru                     73.9  2022  231.0       Karnataka
2      Chennai                     53.7  2022   25.0      Tamil Nadu
3   Coimbatore                     84.2  2022   21.0      Tamil Nadu
4   Delhi City                     95.5  2022  129.0           Delhi
5    Ghaziabad                     92.3  2022   72.0   Uttar Pradesh
6    Hyderabad                     65.9  2022  113.0       Telangana
7       Indore                     97.4  2022   47.0  Madhya Pradesh
8       Jaipur                     31.4  2022  381.0       Rajasthan
9       Kanpur                     89.4  2022  376.0   Uttar Pradesh
10       Kochi                     62.5  2022   22.0          Kerala
11     Kolkata                        -  2022   10.0     West Bengal
12   Kozhikode                     68.8  2022   27.0          Kerala
13     Lucknow                     84.4  2022  420.0   Uttar Pradesh
14      Mumbai                     80.4  2022   58.0     Maharashtra
15      Nagpur                     96.8  2022   35.0     Maharashtra
16       Patna                      100  2022   96.0           Bihar
17        Pune                      100  2022   61.0     Maharashtra
18       Surat                     95.7  2022   34.0         Gujarat
19   Ahmedabad                     95.9  2023  177.0         Gujarat
20   Bengaluru                     73.9  2023  285.0       Karnataka
21     Chennai                     53.7  2023   24.0      Tamil Nadu
22  Coimbatore                     84.2  2023    8.0      Tamil Nadu
23  Delhi City                     95.5  2023  126.0           Delhi
24   Ghaziabad                     92.3  2023   63.0   Uttar Pradesh
25   Hyderabad                     65.9  2023  134.0       Telangana
26      Indore                     97.4  2023   46.0  Madhya Pradesh
27      Jaipur                     31.4  2023  489.0       Rajasthan
28      Kanpur                     89.4  2023  263.0   Uttar Pradesh
29       Kochi                     62.5  2023   43.0          Kerala
30     Kolkata                        -  2023   10.0     West Bengal
31   Kozhikode                     68.8  2023   30.0          Kerala
32     Lucknow                     84.4  2023  517.0   Uttar Pradesh
33      Mumbai                     80.4  2023   52.0     Maharashtra
34      Nagpur                     96.8  2023   40.0     Maharashtra
35       Patna                      100  2023  105.0           Bihar
36        Pune                      100  2023   70.0     Maharashtra
37       Surat                     95.7  2023   38.0         Gujarat
38   Ahmedabad                     95.9  2024  126.0         Gujarat
39   Bengaluru                     73.9  2024  280.0       Karnataka
40     Chennai                     53.7  2024   34.0      Tamil Nadu
41  Coimbatore                     84.2  2024   18.0      Tamil Nadu
42  Delhi City                     95.5  2024  133.0           Delhi
43   Ghaziabad                     92.3  2024   52.0   Uttar Pradesh
44   Hyderabad                     65.9  2024  153.0       Telangana
45      Indore                     97.4  2024   28.0  Madhya Pradesh
46      Jaipur                     31.4  2024  396.0       Rajasthan
47      Kanpur                     89.4  2024  271.0   Uttar Pradesh
48       Kochi                     62.5  2024   42.0          Kerala
49     Kolkata                        -  2024    7.0     West Bengal
50   Kozhikode                     68.8  2024   23.0          Kerala
51     Lucknow                     84.4  2024  490.0   Uttar Pradesh
52      Mumbai                     80.4  2024   62.0     Maharashtra
53      Nagpur                     96.8  2024   66.0     Maharashtra
54       Patna                      100  2024  253.0           Bihar
55        Pune                      100  2024  121.0     Maharashtra
56       Surat                     95.7  2024   51.0         Gujarat

In [763]:
df_long['category']='SC'

In [764]:
df_long[
    [
        'year','state','city','category','cases','chargesheeting_rate_2024']]

    year           state        city category  cases chargesheeting_rate_2024
0   2022         Gujarat   Ahmedabad       SC    189                     95.9
1   2022       Karnataka   Bengaluru       SC    231                     73.9
2   2022      Tamil Nadu     Chennai       SC     25                     53.7
3   2022      Tamil Nadu  Coimbatore       SC     21                     84.2
4   2022           Delhi  Delhi City       SC    129                     95.5
5   2022   Uttar Pradesh   Ghaziabad       SC     72                     92.3
6   2022       Telangana   Hyderabad       SC    113                     65.9
7   2022  Madhya Pradesh      Indore       SC     47                     97.4
8   2022       Rajasthan      Jaipur       SC    381                     31.4
9   2022   Uttar Pradesh      Kanpur       SC    376                     89.4
10  2022          Kerala       Kochi       SC     22                     62.5
11  2022     West Bengal     Kolkata       SC     10                        -
12  2022          Kerala   Kozhikode       SC     27                     68.8
13  2022   Uttar Pradesh     Lucknow       SC    420                     84.4
14  2022     Maharashtra      Mumbai       SC     58                     80.4
15  2022     Maharashtra      Nagpur       SC     35                     96.8
16  2022           Bihar       Patna       SC     96                      100
17  2022     Maharashtra        Pune       SC     61                      100
18  2022         Gujarat       Surat       SC     34                     95.7
19  2023         Gujarat   Ahmedabad       SC    177                     95.9
20  2023       Karnataka   Bengaluru       SC    285                     73.9
21  2023      Tamil Nadu     Chennai       SC     24                     53.7
22  2023      Tamil Nadu  Coimbatore       SC      8                     84.2
23  2023           Delhi  Delhi City       SC    126                     95.5
24  2023   Uttar Pradesh   Ghaziabad       SC     63                     92.3
25  2023       Telangana   Hyderabad       SC    134                     65.9
26  2023  Madhya Pradesh      Indore       SC     46                     97.4
27  2023       Rajasthan      Jaipur       SC    489                     31.4
28  2023   Uttar Pradesh      Kanpur       SC    263                     89.4
29  2023          Kerala       Kochi       SC     43                     62.5
30  2023     West Bengal     Kolkata       SC     10                        -
31  2023          Kerala   Kozhikode       SC     30                     68.8
32  2023   Uttar Pradesh     Lucknow       SC    517                     84.4
33  2023     Maharashtra      Mumbai       SC     52                     80.4
34  2023     Maharashtra      Nagpur       SC     40                     96.8
35  2023           Bihar       Patna       SC    105                      100
36  2023     Maharashtra        Pune       SC     70                      100
37  2023         Gujarat       Surat       SC     38                     95.7
38  2024         Gujarat   Ahmedabad       SC    126                     95.9
39  2024       Karnataka   Bengaluru       SC    280                     73.9
40  2024      Tamil Nadu     Chennai       SC     34                     53.7
41  2024      Tamil Nadu  Coimbatore       SC     18                     84.2
42  2024           Delhi  Delhi City       SC    133                     95.5
43  2024   Uttar Pradesh   Ghaziabad       SC     52                     92.3
44  2024       Telangana   Hyderabad       SC    153                     65.9
45  2024  Madhya Pradesh      Indore       SC     28                     97.4
46  2024       Rajasthan      Jaipur       SC    396                     31.4
47  2024   Uttar Pradesh      Kanpur       SC    271                     89.4
48  2024          Kerala       Kochi       SC     42                     62.5
49  2024     West Bengal     Kolkata       SC      7                        -
50  2024          Kerala   Kozhikode       SC     23                     68.8
51  2024   Uttar Pradesh     Lucknow       SC    490                     84.4
52  2024     Maharashtra      Mumbai       SC     62                     80.4
53  2024     Maharashtra      Nagpur       SC     66                     96.8
54  2024           Bihar       Patna       SC    253                      100
55  2024     Maharashtra        Pune       SC    121                      100
56  2024         Gujarat       Surat       SC     51                     95.7

In [765]:
df_long['cases']=df_long['cases'].astype(int)

In [766]:
df_long

          city chargesheeting_rate_2024  year  cases           state category
0    Ahmedabad                     95.9  2022    189         Gujarat       SC
1    Bengaluru                     73.9  2022    231       Karnataka       SC
2      Chennai                     53.7  2022     25      Tamil Nadu       SC
3   Coimbatore                     84.2  2022     21      Tamil Nadu       SC
4   Delhi City                     95.5  2022    129           Delhi       SC
5    Ghaziabad                     92.3  2022     72   Uttar Pradesh       SC
6    Hyderabad                     65.9  2022    113       Telangana       SC
7       Indore                     97.4  2022     47  Madhya Pradesh       SC
8       Jaipur                     31.4  2022    381       Rajasthan       SC
9       Kanpur                     89.4  2022    376   Uttar Pradesh       SC
10       Kochi                     62.5  2022     22          Kerala       SC
11     Kolkata                        -  2022     10     West Bengal       SC
12   Kozhikode                     68.8  2022     27          Kerala       SC
13     Lucknow                     84.4  2022    420   Uttar Pradesh       SC
14      Mumbai                     80.4  2022     58     Maharashtra       SC
15      Nagpur                     96.8  2022     35     Maharashtra       SC
16       Patna                      100  2022     96           Bihar       SC
17        Pune                      100  2022     61     Maharashtra       SC
18       Surat                     95.7  2022     34         Gujarat       SC
19   Ahmedabad                     95.9  2023    177         Gujarat       SC
20   Bengaluru                     73.9  2023    285       Karnataka       SC
21     Chennai                     53.7  2023     24      Tamil Nadu       SC
22  Coimbatore                     84.2  2023      8      Tamil Nadu       SC
23  Delhi City                     95.5  2023    126           Delhi       SC
24   Ghaziabad                     92.3  2023     63   Uttar Pradesh       SC
25   Hyderabad                     65.9  2023    134       Telangana       SC
26      Indore                     97.4  2023     46  Madhya Pradesh       SC
27      Jaipur                     31.4  2023    489       Rajasthan       SC
28      Kanpur                     89.4  2023    263   Uttar Pradesh       SC
29       Kochi                     62.5  2023     43          Kerala       SC
30     Kolkata                        -  2023     10     West Bengal       SC
31   Kozhikode                     68.8  2023     30          Kerala       SC
32     Lucknow                     84.4  2023    517   Uttar Pradesh       SC
33      Mumbai                     80.4  2023     52     Maharashtra       SC
34      Nagpur                     96.8  2023     40     Maharashtra       SC
35       Patna                      100  2023    105           Bihar       SC
36        Pune                      100  2023     70     Maharashtra       SC
37       Surat                     95.7  2023     38         Gujarat       SC
38   Ahmedabad                     95.9  2024    126         Gujarat       SC
39   Bengaluru                     73.9  2024    280       Karnataka       SC
40     Chennai                     53.7  2024     34      Tamil Nadu       SC
41  Coimbatore                     84.2  2024     18      Tamil Nadu       SC
42  Delhi City                     95.5  2024    133           Delhi       SC
43   Ghaziabad                     92.3  2024     52   Uttar Pradesh       SC
44   Hyderabad                     65.9  2024    153       Telangana       SC
45      Indore                     97.4  2024     28  Madhya Pradesh       SC
46      Jaipur                     31.4  2024    396       Rajasthan       SC
47      Kanpur                     89.4  2024    271   Uttar Pradesh       SC
48       Kochi                     62.5  2024     42          Kerala       SC
49     Kolkata                        -  2024      7     West Bengal       SC
50   Kozhikode                     68.8  2024     23          Kerala       SC
51     Lucknow                     84.4  2024    490   Uttar Pradesh       SC
52      Mumbai                     80.4  2024     62     Maharashtra       SC
53      Nagpur                     96.8  2024     66     Maharashtra       SC
54       Patna                      100  2024    253           Bihar       SC
55        Pune                      100  2024    121     Maharashtra       SC
56       Surat                     95.7  2024     51         Gujarat       SC

In [768]:
df_long.to_csv("../cleaned data/mastered_sc.csv",index=False)

**Crime Against ST**

In [135]:
path6 = '../raw data/Metropolitan Cities - Crime Against STs (vol2-7d.1).xlsx'

In [136]:
df=pd.read_excel(path6,header=2)
df

,SL,City,2022,2023,2024,Chargesheeting Rate (2024)
0,1,Ahmedabad (Gujarat),18.0,18.0,12.0,91.7
1,2,Bengaluru (Karnataka),16.0,16.0,23.0,55
2,3,Chennai (Tamil Nadu),0.0,0.0,0.0,0
3,4,Coimbatore (Tamil Nadu),1.0,0.0,0.0,-
4,5,Delhi City,0.0,2.0,4.0,100
5,6,Ghaziabad (Uttar Pradesh),0.0,0.0,0.0,-
6,7,Hyderabad (Telangana),31.0,30.0,30.0,76.9
7,8,Indore (Madhya Pradesh),9.0,16.0,7.0,100
8,9,Jaipur (Rajasthan),214.0,228.0,228.0,23
9,10,Kanpur (Uttar Pradesh),0.0,0.0,0.0,-
10,11,Kochi (Kerala),5.0,3.0,8.0,83.3
11,12,Kolkata (West Bengal),2.0,2.0,0.0,-
12,13,Kozhikode (Kerala),3.0,2.0,2.0,100
13,14,Lucknow (Uttar Pradesh),0.0,0.0,0.0,-
14,15,Mumbai (Maharashtra),2.0,5.0,7.0,50
15,16,Nagpur (Maharashtra),12.0,6.0,15.0,100
16,17,Patna (Bihar),0.0,0.0,0.0,-
17,18,Pune (Maharashtra),0.0,3.0,7.0,100
18,19,Surat (Gujarat),16.0,18.0,17.0,94.1
19,NaN,TOTAL CITIES,329.0,349.0,360.0,46.1
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [137]:
df = clean_column_names(df)

In [138]:
df =clean_year_columns(df)

In [139]:
df

,sl,city,2022,2023,2024,chargesheeting_rate_(2024)
0,1,Ahmedabad (Gujarat),18.0,18.0,12.0,91.7
1,2,Bengaluru (Karnataka),16.0,16.0,23.0,55
2,3,Chennai (Tamil Nadu),0.0,0.0,0.0,0
3,4,Coimbatore (Tamil Nadu),1.0,0.0,0.0,-
4,5,Delhi City,0.0,2.0,4.0,100
5,6,Ghaziabad (Uttar Pradesh),0.0,0.0,0.0,-
6,7,Hyderabad (Telangana),31.0,30.0,30.0,76.9
7,8,Indore (Madhya Pradesh),9.0,16.0,7.0,100
8,9,Jaipur (Rajasthan),214.0,228.0,228.0,23
9,10,Kanpur (Uttar Pradesh),0.0,0.0,0.0,-
10,11,Kochi (Kerala),5.0,3.0,8.0,83.3
11,12,Kolkata (West Bengal),2.0,2.0,0.0,-
12,13,Kozhikode (Kerala),3.0,2.0,2.0,100
13,14,Lucknow (Uttar Pradesh),0.0,0.0,0.0,-
14,15,Mumbai (Maharashtra),2.0,5.0,7.0,50
15,16,Nagpur (Maharashtra),12.0,6.0,15.0,100
16,17,Patna (Bihar),0.0,0.0,0.0,-
17,18,Pune (Maharashtra),0.0,3.0,7.0,100
18,19,Surat (Gujarat),16.0,18.0,17.0,94.1
19,NaN,TOTAL CITIES,329.0,349.0,360.0,46.1
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [140]:
df = remove_unwanted_columns(df)

In [141]:
df=remove_total_rows(df)

In [142]:
df =remove_empty_rows(df)

In [143]:
df_long = df.melt(
    id_vars=['city','chargesheeting_rate_(2024)'],
    value_name='cases',
    value_vars=['2022','2023','2024'],
    var_name='year')

df_long['category']='ST'

In [144]:
df_long

                         city chargesheeting_rate_(2024)  year  cases category
0         Ahmedabad (Gujarat)                       91.7  2022   18.0       ST
1       Bengaluru (Karnataka)                         55  2022   16.0       ST
2        Chennai (Tamil Nadu)                          0  2022    0.0       ST
3     Coimbatore (Tamil Nadu)                          -  2022    1.0       ST
4                  Delhi City                        100  2022    0.0       ST
5   Ghaziabad (Uttar Pradesh)                          -  2022    0.0       ST
6       Hyderabad (Telangana)                       76.9  2022   31.0       ST
7     Indore (Madhya Pradesh)                        100  2022    9.0       ST
8          Jaipur (Rajasthan)                         23  2022  214.0       ST
9      Kanpur (Uttar Pradesh)                          -  2022    0.0       ST
10             Kochi (Kerala)                       83.3  2022    5.0       ST
11      Kolkata (West Bengal)                          -  2022    2.0       ST
12         Kozhikode (Kerala)                        100  2022    3.0       ST
13    Lucknow (Uttar Pradesh)                          -  2022    0.0       ST
14       Mumbai (Maharashtra)                         50  2022    2.0       ST
15       Nagpur (Maharashtra)                        100  2022   12.0       ST
16              Patna (Bihar)                          -  2022    0.0       ST
17         Pune (Maharashtra)                        100  2022    0.0       ST
18            Surat (Gujarat)                       94.1  2022   16.0       ST
19        Ahmedabad (Gujarat)                       91.7  2023   18.0       ST
20      Bengaluru (Karnataka)                         55  2023   16.0       ST
21       Chennai (Tamil Nadu)                          0  2023    0.0       ST
22    Coimbatore (Tamil Nadu)                          -  2023    0.0       ST
23                 Delhi City                        100  2023    2.0       ST
24  Ghaziabad (Uttar Pradesh)                          -  2023    0.0       ST
25      Hyderabad (Telangana)                       76.9  2023   30.0       ST
26    Indore (Madhya Pradesh)                        100  2023   16.0       ST
27         Jaipur (Rajasthan)                         23  2023  228.0       ST
28     Kanpur (Uttar Pradesh)                          -  2023    0.0       ST
29             Kochi (Kerala)                       83.3  2023    3.0       ST
30      Kolkata (West Bengal)                          -  2023    2.0       ST
31         Kozhikode (Kerala)                        100  2023    2.0       ST
32    Lucknow (Uttar Pradesh)                          -  2023    0.0       ST
33       Mumbai (Maharashtra)                         50  2023    5.0       ST
34       Nagpur (Maharashtra)                        100  2023    6.0       ST
35              Patna (Bihar)                          -  2023    0.0       ST
36         Pune (Maharashtra)                        100  2023    3.0       ST
37            Surat (Gujarat)                       94.1  2023   18.0       ST
38        Ahmedabad (Gujarat)                       91.7  2024   12.0       ST
39      Bengaluru (Karnataka)                         55  2024   23.0       ST
40       Chennai (Tamil Nadu)                          0  2024    0.0       ST
41    Coimbatore (Tamil Nadu)                          -  2024    0.0       ST
42                 Delhi City                        100  2024    4.0       ST
43  Ghaziabad (Uttar Pradesh)                          -  2024    0.0       ST
44      Hyderabad (Telangana)                       76.9  2024   30.0       ST
45    Indore (Madhya Pradesh)                        100  2024    7.0       ST
46         Jaipur (Rajasthan)                         23  2024  228.0       ST
47     Kanpur (Uttar Pradesh)                          -  2024    0.0       ST
48             Kochi (Kerala)                       83.3  2024    8.0       ST
49      Kolkata (West Bengal)                          -  2024    0.0       ST
50         Kozhikode (Kerala)                        100  2024    2.0       ST
51    Lucknow (Uttar Pradesh)                          -  2024    0.0       ST
52       Mumbai (Maharashtra)                         50  2024    7.0       ST
53       Nagpur (Maharashtra)                        100  2024   15.0       ST
54              Patna (Bihar)                          -  2024    0.0       ST
55         Pune (Maharashtra)                        100  2024    7.0       ST
56            Surat (Gujarat)                       94.1  2024   17.0       ST

In [145]:
df_long = df_long.rename(columns={'chargesheeting_rate_(2024)':'chargesheeting_rate_2024'})

In [146]:
df_long = extract_city_state(df_long)

In [147]:
df_long =df_long[
    [ 'year','state','city','category','cases','chargesheeting_rate_2024']]

In [148]:
df_long

    year           state        city category  cases chargesheeting_rate_2024
0   2022         Gujarat   Ahmedabad       ST   18.0                     91.7
1   2022       Karnataka   Bengaluru       ST   16.0                       55
2   2022      Tamil Nadu     Chennai       ST    0.0                        0
3   2022      Tamil Nadu  Coimbatore       ST    1.0                        -
4   2022           Delhi  Delhi City       ST    0.0                      100
5   2022   Uttar Pradesh   Ghaziabad       ST    0.0                        -
6   2022       Telangana   Hyderabad       ST   31.0                     76.9
7   2022  Madhya Pradesh      Indore       ST    9.0                      100
8   2022       Rajasthan      Jaipur       ST  214.0                       23
9   2022   Uttar Pradesh      Kanpur       ST    0.0                        -
10  2022          Kerala       Kochi       ST    5.0                     83.3
11  2022     West Bengal     Kolkata       ST    2.0                        -
12  2022          Kerala   Kozhikode       ST    3.0                      100
13  2022   Uttar Pradesh     Lucknow       ST    0.0                        -
14  2022     Maharashtra      Mumbai       ST    2.0                       50
15  2022     Maharashtra      Nagpur       ST   12.0                      100
16  2022           Bihar       Patna       ST    0.0                        -
17  2022     Maharashtra        Pune       ST    0.0                      100
18  2022         Gujarat       Surat       ST   16.0                     94.1
19  2023         Gujarat   Ahmedabad       ST   18.0                     91.7
20  2023       Karnataka   Bengaluru       ST   16.0                       55
21  2023      Tamil Nadu     Chennai       ST    0.0                        0
22  2023      Tamil Nadu  Coimbatore       ST    0.0                        -
23  2023           Delhi  Delhi City       ST    2.0                      100
24  2023   Uttar Pradesh   Ghaziabad       ST    0.0                        -
25  2023       Telangana   Hyderabad       ST   30.0                     76.9
26  2023  Madhya Pradesh      Indore       ST   16.0                      100
27  2023       Rajasthan      Jaipur       ST  228.0                       23
28  2023   Uttar Pradesh      Kanpur       ST    0.0                        -
29  2023          Kerala       Kochi       ST    3.0                     83.3
30  2023     West Bengal     Kolkata       ST    2.0                        -
31  2023          Kerala   Kozhikode       ST    2.0                      100
32  2023   Uttar Pradesh     Lucknow       ST    0.0                        -
33  2023     Maharashtra      Mumbai       ST    5.0                       50
34  2023     Maharashtra      Nagpur       ST    6.0                      100
35  2023           Bihar       Patna       ST    0.0                        -
36  2023     Maharashtra        Pune       ST    3.0                      100
37  2023         Gujarat       Surat       ST   18.0                     94.1
38  2024         Gujarat   Ahmedabad       ST   12.0                     91.7
39  2024       Karnataka   Bengaluru       ST   23.0                       55
40  2024      Tamil Nadu     Chennai       ST    0.0                        0
41  2024      Tamil Nadu  Coimbatore       ST    0.0                        -
42  2024           Delhi  Delhi City       ST    4.0                      100
43  2024   Uttar Pradesh   Ghaziabad       ST    0.0                        -
44  2024       Telangana   Hyderabad       ST   30.0                     76.9
45  2024  Madhya Pradesh      Indore       ST    7.0                      100
46  2024       Rajasthan      Jaipur       ST  228.0                       23
47  2024   Uttar Pradesh      Kanpur       ST    0.0                        -
48  2024          Kerala       Kochi       ST    8.0                     83.3
49  2024     West Bengal     Kolkata       ST    0.0                        -
50  2024          Kerala   Kozhikode       ST    2.0                      100
51  2024   Uttar Pradesh     Lucknow       ST    0.0                        -
52  2024     Maharashtra      Mumbai       ST    7.0                       50
53  2024     Maharashtra      Nagpur       ST   15.0                      100
54  2024           Bihar       Patna       ST    0.0                        -
55  2024     Maharashtra        Pune       ST    7.0                      100
56  2024         Gujarat       Surat       ST   17.0                     94.1

In [149]:
df_long.to_csv('../cleaned data/mastered_st.csv',index=False)

**Crime Against Senior**

In [150]:
path7 ='../raw data/Metropolitan Cities - Crime Against Senior(vol2-6b.1).xlsx'

In [153]:
df=pd.read_excel(path7,header=2)
df

,SL,City,2022,2023,2024 (IPC),2024 (BNS),2024 (Total),Chargesheeting Rate (2024)
0,1,Ahmedabad (Gujarat),238.0,184.0,98.0,68.0,166.0,51.1
1,2,Bengaluru (Karnataka),458.0,649.0,442.0,218.0,660.0,57.4
2,3,Chennai (Tamil Nadu),391.0,399.0,124.0,127.0,251.0,89.7
3,4,Coimbatore (Tamil Nadu),6.0,24.0,29.0,20.0,49.0,92.3
4,5,Delhi City,1313.0,1361.0,779.0,488.0,1267.0,51.6
5,6,Ghaziabad (Uttar Pradesh),0.0,0.0,0.0,0.0,0.0,-
6,7,Hyderabad (Telangana),331.0,292.0,0.0,1.0,1.0,-
7,8,Indore (Madhya Pradesh),207.0,273.0,74.0,39.0,113.0,96
8,9,Jaipur (Rajasthan),83.0,185.0,49.0,23.0,72.0,15.6
9,10,Kanpur (Uttar Pradesh),0.0,0.0,0.0,0.0,0.0,-
10,11,Kochi (Kerala),74.0,126.0,150.0,113.0,263.0,81.8
11,12,Kolkata (West Bengal),2.0,6.0,2.0,1.0,3.0,100
12,13,Kozhikode (Kerala),52.0,93.0,54.0,49.0,103.0,96
13,14,Lucknow (Uttar Pradesh),0.0,0.0,0.0,0.0,0.0,-
14,15,Mumbai (Maharashtra),572.0,518.0,482.0,309.0,791.0,51.6
15,16,Nagpur (Maharashtra),167.0,231.0,117.0,87.0,204.0,51.1
16,17,Patna (Bihar),0.0,0.0,0.0,0.0,0.0,-
17,18,Pune (Maharashtra),69.0,57.0,75.0,76.0,151.0,35.4
18,19,Surat (Gujarat),33.0,14.0,11.0,2.0,13.0,61.5
19,NaN,TOTAL CITIES,3996.0,4412.0,2486.0,1621.0,4107.0,59.1
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
df.columns

Index(['SL', 'City', '2022', '2023', '2024 (IPC)', '2024 (BNS)',
       '2024 (Total)', 'Chargesheeting Rate (2024)'],
      dtype='object')

In [155]:
df['2024']=df['2024 (Total)']

In [156]:
df

,SL,City,2022,2023,2024 (IPC),2024 (BNS),2024 (Total),Chargesheeting Rate (2024),2024
0,1,Ahmedabad (Gujarat),238.0,184.0,98.0,68.0,166.0,51.1,166.0
1,2,Bengaluru (Karnataka),458.0,649.0,442.0,218.0,660.0,57.4,660.0
2,3,Chennai (Tamil Nadu),391.0,399.0,124.0,127.0,251.0,89.7,251.0
3,4,Coimbatore (Tamil Nadu),6.0,24.0,29.0,20.0,49.0,92.3,49.0
4,5,Delhi City,1313.0,1361.0,779.0,488.0,1267.0,51.6,1267.0
5,6,Ghaziabad (Uttar Pradesh),0.0,0.0,0.0,0.0,0.0,-,0.0
6,7,Hyderabad (Telangana),331.0,292.0,0.0,1.0,1.0,-,1.0
7,8,Indore (Madhya Pradesh),207.0,273.0,74.0,39.0,113.0,96,113.0
8,9,Jaipur (Rajasthan),83.0,185.0,49.0,23.0,72.0,15.6,72.0
9,10,Kanpur (Uttar Pradesh),0.0,0.0,0.0,0.0,0.0,-,0.0
10,11,Kochi (Kerala),74.0,126.0,150.0,113.0,263.0,81.8,263.0
11,12,Kolkata (West Bengal),2.0,6.0,2.0,1.0,3.0,100,3.0
12,13,Kozhikode (Kerala),52.0,93.0,54.0,49.0,103.0,96,103.0
13,14,Lucknow (Uttar Pradesh),0.0,0.0,0.0,0.0,0.0,-,0.0
14,15,Mumbai (Maharashtra),572.0,518.0,482.0,309.0,791.0,51.6,791.0
15,16,Nagpur (Maharashtra),167.0,231.0,117.0,87.0,204.0,51.1,204.0
16,17,Patna (Bihar),0.0,0.0,0.0,0.0,0.0,-,0.0
17,18,Pune (Maharashtra),69.0,57.0,75.0,76.0,151.0,35.4,151.0
18,19,Surat (Gujarat),33.0,14.0,11.0,2.0,13.0,61.5,13.0
19,NaN,TOTAL CITIES,3996.0,4412.0,2486.0,1621.0,4107.0,59.1,4107.0
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [157]:
df.drop(columns=['2024 (IPC)','2024 (BNS)','2024 (Total)'],inplace=True)

In [158]:
df

,SL,City,2022,2023,Chargesheeting Rate (2024),2024
0,1,Ahmedabad (Gujarat),238.0,184.0,51.1,166.0
1,2,Bengaluru (Karnataka),458.0,649.0,57.4,660.0
2,3,Chennai (Tamil Nadu),391.0,399.0,89.7,251.0
3,4,Coimbatore (Tamil Nadu),6.0,24.0,92.3,49.0
4,5,Delhi City,1313.0,1361.0,51.6,1267.0
5,6,Ghaziabad (Uttar Pradesh),0.0,0.0,-,0.0
6,7,Hyderabad (Telangana),331.0,292.0,-,1.0
7,8,Indore (Madhya Pradesh),207.0,273.0,96,113.0
8,9,Jaipur (Rajasthan),83.0,185.0,15.6,72.0
9,10,Kanpur (Uttar Pradesh),0.0,0.0,-,0.0
10,11,Kochi (Kerala),74.0,126.0,81.8,263.0
11,12,Kolkata (West Bengal),2.0,6.0,100,3.0
12,13,Kozhikode (Kerala),52.0,93.0,96,103.0
13,14,Lucknow (Uttar Pradesh),0.0,0.0,-,0.0
14,15,Mumbai (Maharashtra),572.0,518.0,51.6,791.0
15,16,Nagpur (Maharashtra),167.0,231.0,51.1,204.0
16,17,Patna (Bihar),0.0,0.0,-,0.0
17,18,Pune (Maharashtra),69.0,57.0,35.4,151.0
18,19,Surat (Gujarat),33.0,14.0,61.5,13.0
19,NaN,TOTAL CITIES,3996.0,4412.0,59.1,4107.0
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [159]:
df = clean_column_names(df)

In [160]:
df= clean_year_columns(df)

In [161]:
df = remove_empty_rows(df)

In [162]:
df = remove_unwanted_columns(df)

In [163]:
df = remove_total_rows(df)

In [164]:
df = remove_empty_rows(df)

In [165]:
df

,city,2022,2023,chargesheeting_rate_(2024),2024
0,Ahmedabad (Gujarat),238.0,184.0,51.1,166.0
1,Bengaluru (Karnataka),458.0,649.0,57.4,660.0
2,Chennai (Tamil Nadu),391.0,399.0,89.7,251.0
3,Coimbatore (Tamil Nadu),6.0,24.0,92.3,49.0
4,Delhi City,1313.0,1361.0,51.6,1267.0
5,Ghaziabad (Uttar Pradesh),0.0,0.0,-,0.0
6,Hyderabad (Telangana),331.0,292.0,-,1.0
7,Indore (Madhya Pradesh),207.0,273.0,96,113.0
8,Jaipur (Rajasthan),83.0,185.0,15.6,72.0
9,Kanpur (Uttar Pradesh),0.0,0.0,-,0.0
10,Kochi (Kerala),74.0,126.0,81.8,263.0
11,Kolkata (West Bengal),2.0,6.0,100,3.0
12,Kozhikode (Kerala),52.0,93.0,96,103.0
13,Lucknow (Uttar Pradesh),0.0,0.0,-,0.0
14,Mumbai (Maharashtra),572.0,518.0,51.6,791.0
15,Nagpur (Maharashtra),167.0,231.0,51.1,204.0
16,Patna (Bihar),0.0,0.0,-,0.0
17,Pune (Maharashtra),69.0,57.0,35.4,151.0
18,Surat (Gujarat),33.0,14.0,61.5,13.0

In [166]:
df_long = df.melt(
    id_vars=['city','chargesheeting_rate_(2024)'],
    value_vars=['2022','2023','2024'],
    value_name='cases',
    var_name='year'
    )

In [167]:
df_long['category']='Senior Citizen'

In [168]:
df_long = df_long.rename(columns={'chargesheeting_rate_(2024)':'chargesheeting_rate_2024'})

In [169]:
df_long= extract_city_state(df_long)

In [170]:
df_long=df_long[
    [ 'year','state','city','category','cases','chargesheeting_rate_2024']]

In [173]:
df_long.to_csv('../cleaned data/Mastered_senior.csv',index=False)

**Crime Head-wise Economic**

In [202]:
path8='../raw data/Metropolitan Cities - Crime Head-wise Economic(vol2-8b.2).xlsx'

In [203]:
df = pd.read_excel(path8,header=2)
df.head(5)

,SL,City,Criminal Breach of Trust (Sec 316 BNS / Sec 406-409 IPC),"Counterfeiting (Sec 178-181, 183-188, 341(1-4) BNS / Sec 231-235, 237-240, 242-254, 489A-489E IPC)","Forgery, Cheating & Fraud (Sec 318(4), 338, 336(3)(4), 340(2), 339 BNS / Sec 420, 465, 467-474 IPC)",Total Economic Offences
0,1,Ahmedabad (Gujarat),135.0,10.0,661.0,806.0
1,2,Bengaluru (Karnataka),217.0,11.0,3249.0,3477.0
2,3,Chennai (Tamil Nadu),11.0,2.0,2423.0,2436.0
3,4,Coimbatore (Tamil Nadu),2.0,2.0,656.0,660.0
4,5,Delhi City,254.0,33.0,4237.0,4524.0

In [204]:
df = clean_column_names(df)
df

,sl,city,criminal_breach_of_trust_(sec_316_bns_/_sec_406_409_ipc),"counterfeiting_(sec_178_181,_183_188,_341(1_4)_bns_/_sec_231_235,_237_240,_242_254,_489a_489e_ipc)","forgery,_cheating_&_fraud_(sec_318(4),_338,_336(3)(4),_340(2),_339_bns_/_sec_420,_465,_467_474_ipc)",total_economic_offences
0,1,Ahmedabad (Gujarat),135.0,10.0,661.0,806.0
1,2,Bengaluru (Karnataka),217.0,11.0,3249.0,3477.0
2,3,Chennai (Tamil Nadu),11.0,2.0,2423.0,2436.0
3,4,Coimbatore (Tamil Nadu),2.0,2.0,656.0,660.0
4,5,Delhi City,254.0,33.0,4237.0,4524.0
5,6,Ghaziabad (Uttar Pradesh),249.0,7.0,519.0,775.0
6,7,Hyderabad (Telangana),155.0,5.0,5679.0,5839.0
7,8,Indore (Madhya Pradesh),46.0,1.0,248.0,295.0
8,9,Jaipur (Rajasthan),199.0,4.0,5268.0,5471.0
9,10,Kanpur (Uttar Pradesh),114.0,4.0,345.0,463.0
10,11,Kochi (Kerala),25.0,0.0,1025.0,1050.0
11,12,Kolkata (West Bengal),227.0,12.0,1586.0,1825.0
12,13,Kozhikode (Kerala),13.0,6.0,450.0,469.0
13,14,Lucknow (Uttar Pradesh),482.0,0.0,1250.0,1732.0
14,15,Mumbai (Maharashtra),1395.0,10.0,6366.0,7771.0
15,16,Nagpur (Maharashtra),48.0,3.0,697.0,748.0
16,17,Patna (Bihar),0.0,0.0,1402.0,1402.0
17,18,Pune (Maharashtra),93.0,2.0,2030.0,2125.0
18,19,Surat (Gujarat),312.0,5.0,562.0,879.0
19,NaN,TOTAL CITIES,3977.0,117.0,38653.0,42747.0
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [205]:
df = remove_total_rows(df)
df

,sl,city,criminal_breach_of_trust_(sec_316_bns_/_sec_406_409_ipc),"counterfeiting_(sec_178_181,_183_188,_341(1_4)_bns_/_sec_231_235,_237_240,_242_254,_489a_489e_ipc)","forgery,_cheating_&_fraud_(sec_318(4),_338,_336(3)(4),_340(2),_339_bns_/_sec_420,_465,_467_474_ipc)",total_economic_offences
0,1,Ahmedabad (Gujarat),135.0,10.0,661.0,806.0
1,2,Bengaluru (Karnataka),217.0,11.0,3249.0,3477.0
2,3,Chennai (Tamil Nadu),11.0,2.0,2423.0,2436.0
3,4,Coimbatore (Tamil Nadu),2.0,2.0,656.0,660.0
4,5,Delhi City,254.0,33.0,4237.0,4524.0
5,6,Ghaziabad (Uttar Pradesh),249.0,7.0,519.0,775.0
6,7,Hyderabad (Telangana),155.0,5.0,5679.0,5839.0
7,8,Indore (Madhya Pradesh),46.0,1.0,248.0,295.0
8,9,Jaipur (Rajasthan),199.0,4.0,5268.0,5471.0
9,10,Kanpur (Uttar Pradesh),114.0,4.0,345.0,463.0
10,11,Kochi (Kerala),25.0,0.0,1025.0,1050.0
11,12,Kolkata (West Bengal),227.0,12.0,1586.0,1825.0
12,13,Kozhikode (Kerala),13.0,6.0,450.0,469.0
13,14,Lucknow (Uttar Pradesh),482.0,0.0,1250.0,1732.0
14,15,Mumbai (Maharashtra),1395.0,10.0,6366.0,7771.0
15,16,Nagpur (Maharashtra),48.0,3.0,697.0,748.0
16,17,Patna (Bihar),0.0,0.0,1402.0,1402.0
17,18,Pune (Maharashtra),93.0,2.0,2030.0,2125.0
18,19,Surat (Gujarat),312.0,5.0,562.0,879.0
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [206]:
df= remove_empty_rows(df)
df

/var/folders/49/zsmlknk50xlgvpt62wqkw_jc0000gn/T/ipykernel_17955/2239912996.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(how='all', inplace=True)

,sl,city,criminal_breach_of_trust_(sec_316_bns_/_sec_406_409_ipc),"counterfeiting_(sec_178_181,_183_188,_341(1_4)_bns_/_sec_231_235,_237_240,_242_254,_489a_489e_ipc)","forgery,_cheating_&_fraud_(sec_318(4),_338,_336(3)(4),_340(2),_339_bns_/_sec_420,_465,_467_474_ipc)",total_economic_offences
0,1,Ahmedabad (Gujarat),135.0,10.0,661.0,806.0
1,2,Bengaluru (Karnataka),217.0,11.0,3249.0,3477.0
2,3,Chennai (Tamil Nadu),11.0,2.0,2423.0,2436.0
3,4,Coimbatore (Tamil Nadu),2.0,2.0,656.0,660.0
4,5,Delhi City,254.0,33.0,4237.0,4524.0
5,6,Ghaziabad (Uttar Pradesh),249.0,7.0,519.0,775.0
6,7,Hyderabad (Telangana),155.0,5.0,5679.0,5839.0
7,8,Indore (Madhya Pradesh),46.0,1.0,248.0,295.0
8,9,Jaipur (Rajasthan),199.0,4.0,5268.0,5471.0
9,10,Kanpur (Uttar Pradesh),114.0,4.0,345.0,463.0
10,11,Kochi (Kerala),25.0,0.0,1025.0,1050.0
11,12,Kolkata (West Bengal),227.0,12.0,1586.0,1825.0
12,13,Kozhikode (Kerala),13.0,6.0,450.0,469.0
13,14,Lucknow (Uttar Pradesh),482.0,0.0,1250.0,1732.0
14,15,Mumbai (Maharashtra),1395.0,10.0,6366.0,7771.0
15,16,Nagpur (Maharashtra),48.0,3.0,697.0,748.0
16,17,Patna (Bihar),0.0,0.0,1402.0,1402.0
17,18,Pune (Maharashtra),93.0,2.0,2030.0,2125.0
18,19,Surat (Gujarat),312.0,5.0,562.0,879.0
20,"Source: Crime in India 2024 - Volume II, NCRB",NaN,NaN,NaN,NaN,NaN

In [207]:
df = remove_unwanted_columns(df)

In [208]:
df

,city,criminal_breach_of_trust_(sec_316_bns_/_sec_406_409_ipc),"counterfeiting_(sec_178_181,_183_188,_341(1_4)_bns_/_sec_231_235,_237_240,_242_254,_489a_489e_ipc)","forgery,_cheating_&_fraud_(sec_318(4),_338,_336(3)(4),_340(2),_339_bns_/_sec_420,_465,_467_474_ipc)",total_economic_offences
0,Ahmedabad (Gujarat),135.0,10.0,661.0,806.0
1,Bengaluru (Karnataka),217.0,11.0,3249.0,3477.0
2,Chennai (Tamil Nadu),11.0,2.0,2423.0,2436.0
3,Coimbatore (Tamil Nadu),2.0,2.0,656.0,660.0
4,Delhi City,254.0,33.0,4237.0,4524.0
5,Ghaziabad (Uttar Pradesh),249.0,7.0,519.0,775.0
6,Hyderabad (Telangana),155.0,5.0,5679.0,5839.0
7,Indore (Madhya Pradesh),46.0,1.0,248.0,295.0
8,Jaipur (Rajasthan),199.0,4.0,5268.0,5471.0
9,Kanpur (Uttar Pradesh),114.0,4.0,345.0,463.0
10,Kochi (Kerala),25.0,0.0,1025.0,1050.0
11,Kolkata (West Bengal),227.0,12.0,1586.0,1825.0
12,Kozhikode (Kerala),13.0,6.0,450.0,469.0
13,Lucknow (Uttar Pradesh),482.0,0.0,1250.0,1732.0
14,Mumbai (Maharashtra),1395.0,10.0,6366.0,7771.0
15,Nagpur (Maharashtra),48.0,3.0,697.0,748.0
16,Patna (Bihar),0.0,0.0,1402.0,1402.0
17,Pune (Maharashtra),93.0,2.0,2030.0,2125.0
18,Surat (Gujarat),312.0,5.0,562.0,879.0
20,NaN,NaN,NaN,NaN,NaN

In [209]:
df = extract_city_state(df)

In [210]:
df.head(5)

,city,criminal_breach_of_trust_(sec_316_bns_/_sec_406_409_ipc),"counterfeiting_(sec_178_181,_183_188,_341(1_4)_bns_/_sec_231_235,_237_240,_242_254,_489a_489e_ipc)","forgery,_cheating_&_fraud_(sec_318(4),_338,_336(3)(4),_340(2),_339_bns_/_sec_420,_465,_467_474_ipc)",total_economic_offences,state
0,Ahmedabad,135.0,10.0,661.0,806.0,Gujarat
1,Bengaluru,217.0,11.0,3249.0,3477.0,Karnataka
2,Chennai,11.0,2.0,2423.0,2436.0,Tamil Nadu
3,Coimbatore,2.0,2.0,656.0,660.0,Tamil Nadu
4,Delhi City,254.0,33.0,4237.0,4524.0,Delhi

In [220]:
def normalize_crime_columns(df):

    df.columns = (df.columns.str.split('(').str[0].str.replace(',', '', regex=False).str.rstrip('_').str.lower())

    return df

In [233]:
df = normalize_crime_columns(df)

In [234]:
df

,city,criminal_breach_of_trust,counterfeiting,forgery_cheating_&_fraud,state
0,Ahmedabad,135.0,10.0,661.0,Gujarat
1,Bengaluru,217.0,11.0,3249.0,Karnataka
2,Chennai,11.0,2.0,2423.0,Tamil Nadu
3,Coimbatore,2.0,2.0,656.0,Tamil Nadu
4,Delhi City,254.0,33.0,4237.0,Delhi
5,Ghaziabad,249.0,7.0,519.0,Uttar Pradesh
6,Hyderabad,155.0,5.0,5679.0,Telangana
7,Indore,46.0,1.0,248.0,Madhya Pradesh
8,Jaipur,199.0,4.0,5268.0,Rajasthan
9,Kanpur,114.0,4.0,345.0,Uttar Pradesh
10,Kochi,25.0,0.0,1025.0,Kerala
11,Kolkata,227.0,12.0,1586.0,West Bengal
12,Kozhikode,13.0,6.0,450.0,Kerala
13,Lucknow,482.0,0.0,1250.0,Uttar Pradesh
14,Mumbai,1395.0,10.0,6366.0,Maharashtra
15,Nagpur,48.0,3.0,697.0,Maharashtra
16,Patna,0.0,0.0,1402.0,Bihar
17,Pune,93.0,2.0,2030.0,Maharashtra
18,Surat,312.0,5.0,562.0,Gujarat

In [235]:
df.columns

Index(['city', 'criminal_breach_of_trust', 'counterfeiting',
       'forgery_cheating_&_fraud', 'state'],
      dtype='object')

In [236]:
df = df.drop(columns=['total_economic_offences']

KeyError: "['total_economic_offences'] not found in axis"

In [280]:
df= remove_empty_rows(df)

In [239]:
df_long = df.melt(
    id_vars=['city','state'],
    value_vars=['criminal_breach_of_trust','counterfeiting','forgery_cheating_&_fraud'],
    value_name='cases',
    var_name='crime_head')

In [240]:
df_long['category'] = 'Economic Offences'

In [244]:
df_long.head(5)

        state        city           category                crime_head  cases
0     Gujarat   Ahmedabad  Economic Offences  criminal_breach_of_trust  135.0
1   Karnataka   Bengaluru  Economic Offences  criminal_breach_of_trust  217.0
2  Tamil Nadu     Chennai  Economic Offences  criminal_breach_of_trust   11.0
3  Tamil Nadu  Coimbatore  Economic Offences  criminal_breach_of_trust    2.0
4       Delhi  Delhi City  Economic Offences  criminal_breach_of_trust  254.0

In [243]:
df_long = df_long[
    [
        'state',
        'city',
        'category',
        'crime_head',
        'cases'
    ]
]

In [247]:
df_long.to_csv(
    "../cleaned data/fact_economic_crime_heads.csv",
    index=False
)

**IPC/BNS Crimes (Crime-head wise)**

In [281]:
path9=r'../raw data/Crime-head wise 2022-24(table_1.2).xlsx'

In [282]:
df_raw = pd.read_excel(path9, header=None)

In [283]:
df_raw.head(5)

,0,1,2,3,4,5,6,7,8,9,10
0,TABLE 1.2 - IPC/BNS Crimes (Crime Head-wise) -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SL,Crime Head,2022,NaN,2023,NaN,2024,NaN,NaN,NaN,NaN
2,NaN,NaN,Cases,Crime Rate,Cases,Crime Rate,IPC Cases,BNS Cases,Total IPC+BNS Cases,Crime Rate,% Share of IPC Crimes
3,1,Rape,31516,2.3,29670,2.1,19683,9853,29536,2.1,0.8
4,2,Attempt to Commit Rape,3288,0.2,2796,0.2,1503,1058,2561,0.2,0.1

In [284]:
header1 = df_raw.iloc[1]
header2 = df_raw.iloc[2]

In [285]:
new_columns = []

for col1, col2 in zip(header1, header2):

    col1 = str(col1).strip()
    col2 = str(col2).strip()

    # Handle unnamed columns
    if col1 == 'nan':
        new_columns.append(col2.lower().replace(' ', '_'))

    else:
        new_columns.append(
            f"{col1}_{col2}"
            .lower()
            .replace(' ', '_')
        )

In [286]:
df = df_raw.iloc[3:].copy()

In [287]:
df = df.iloc[2:].reset_index(drop=True)

In [288]:
df.columns = new_columns

In [289]:
df.reset_index(drop=True, inplace=True)
df

,sl_nan,crime_head_nan,2022_cases,crime_rate,2023_cases,crime_rate,2024_ipc_cases,bns_cases,total_ipc+bns_cases,crime_rate,%_share_of_ipc_crimes
0,3,Sexual Intercourse by employing deceitful means,-,-,-,-,0,1325,1325,0.1,0
1,4,Disclosure of Identity of Victim,-,-,-,-,0,11,11,0,0
2,5,Assault on Women with Intent to Outrage her Mo...,44867,3.3,45086,3.2,25829,22474,48303,3.4,1.4
3,6,Sexual Harassment,17809,1.3,17544,1.3,8130,7479,15609,1.1,0.4
4,6A,at Office Premises,419,0,381,0,305,83,388,0,0
...,...,...,...,...,...,...,...,...,...,...,...
163,A1,Insult to the Modesty of Women,8972,0.7,8823,0.6,-,-,-,-,-
164,A2,Cruelty by Husband or his Relatives,140019,10.1,133676,9.6,-,-,-,-,-
165,NaN,"Misc. BNS/IPC Crimes (Total of 54-57,E6-E7&A1-A2)",1041627,75.5,1141379,82,385998,347483,733481,52.2,20.7
166,68,Other BNS/IPC crimes,292964,21.2,316982,22.8,296526,306280,602806,42.9,17
167,NaN,Total Cognizable BNS/IPC crimes,3561379,258.1,3763102,270.3,1903047,1641561,3544608,252.3,100

In [290]:
df.drop(columns=[
    'sl_nan','%_share_of_ipc_crimes'
], inplace=True)

df

,crime_head_nan,2022_cases,crime_rate,2023_cases,crime_rate,2024_ipc_cases,bns_cases,total_ipc+bns_cases,crime_rate
0,Sexual Intercourse by employing deceitful means,-,-,-,-,0,1325,1325,0.1
1,Disclosure of Identity of Victim,-,-,-,-,0,11,11,0
2,Assault on Women with Intent to Outrage her Mo...,44867,3.3,45086,3.2,25829,22474,48303,3.4
3,Sexual Harassment,17809,1.3,17544,1.3,8130,7479,15609,1.1
4,at Office Premises,419,0,381,0,305,83,388,0
...,...,...,...,...,...,...,...,...,...
163,Insult to the Modesty of Women,8972,0.7,8823,0.6,-,-,-,-
164,Cruelty by Husband or his Relatives,140019,10.1,133676,9.6,-,-,-,-
165,"Misc. BNS/IPC Crimes (Total of 54-57,E6-E7&A1-A2)",1041627,75.5,1141379,82,385998,347483,733481,52.2
166,Other BNS/IPC crimes,292964,21.2,316982,22.8,296526,306280,602806,42.9
167,Total Cognizable BNS/IPC crimes,3561379,258.1,3763102,270.3,1903047,1641561,3544608,252.3

In [291]:
df.rename(columns={
    'crime_head_nan': 'crime_head'
}, inplace=True)

In [292]:
df

,crime_head,2022_cases,crime_rate,2023_cases,crime_rate,2024_ipc_cases,bns_cases,total_ipc+bns_cases,crime_rate
0,Sexual Intercourse by employing deceitful means,-,-,-,-,0,1325,1325,0.1
1,Disclosure of Identity of Victim,-,-,-,-,0,11,11,0
2,Assault on Women with Intent to Outrage her Mo...,44867,3.3,45086,3.2,25829,22474,48303,3.4
3,Sexual Harassment,17809,1.3,17544,1.3,8130,7479,15609,1.1
4,at Office Premises,419,0,381,0,305,83,388,0
...,...,...,...,...,...,...,...,...,...
163,Insult to the Modesty of Women,8972,0.7,8823,0.6,-,-,-,-
164,Cruelty by Husband or his Relatives,140019,10.1,133676,9.6,-,-,-,-
165,"Misc. BNS/IPC Crimes (Total of 54-57,E6-E7&A1-A2)",1041627,75.5,1141379,82,385998,347483,733481,52.2
166,Other BNS/IPC crimes,292964,21.2,316982,22.8,296526,306280,602806,42.9
167,Total Cognizable BNS/IPC crimes,3561379,258.1,3763102,270.3,1903047,1641561,3544608,252.3

In [293]:
df.columns

Index(['crime_head', '2022_cases', 'crime_rate', '2023_cases', 'crime_rate',
       '2024_ipc_cases', 'bns_cases', 'total_ipc+bns_cases', 'crime_rate'],
      dtype='object')

In [295]:
df.rename(columns={
    'total_ipc+bns_cases': '2024_cases'
}, inplace=True)

In [296]:
df.drop(columns=[
    '2024_ipc_cases',
    'bns_cases'
], inplace=True)

In [297]:
df.columns

Index(['crime_head', '2022_cases', 'crime_rate', '2023_cases', 'crime_rate',
       '2024_cases', 'crime_rate'],
      dtype='object')

In [305]:
cases_df = df.melt(
    id_vars=['crime_head'],
    value_vars=['2022_cases','2023_cases','2024_cases'],
    var_name='year_metric',
    value_name='cases')

In [306]:
cases_df

                                            crime_head year_metric    cases
0      Sexual Intercourse by employing deceitful means  2022_cases        -
1                     Disclosure of Identity of Victim  2022_cases        -
2    Assault on Women with Intent to Outrage her Mo...  2022_cases    44867
3                                    Sexual Harassment  2022_cases    17809
4                                   at Office Premises  2022_cases      419
..                                                 ...         ...      ...
499                     Insult to the Modesty of Women  2024_cases        -
500                Cruelty by Husband or his Relatives  2024_cases        -
501  Misc. BNS/IPC Crimes (Total of 54-57,E6-E7&A1-A2)  2024_cases   733481
502                               Other BNS/IPC crimes  2024_cases   602806
503                    Total Cognizable BNS/IPC crimes  2024_cases  3544608

[504 rows x 3 columns]

In [307]:
cases_df.columns

Index(['crime_head', 'year_metric', 'cases'], dtype='object')

In [308]:
cases_df['year'] = (
    cases_df['year_metric']
    .str.split('_')
    .str[0]
)

In [309]:
cases_df

,crime_head,year_metric,cases,year
0,Sexual Intercourse by employing deceitful means,2022_cases,-,2022
1,Disclosure of Identity of Victim,2022_cases,-,2022
2,Assault on Women with Intent to Outrage her Mo...,2022_cases,44867,2022
3,Sexual Harassment,2022_cases,17809,2022
4,at Office Premises,2022_cases,419,2022
...,...,...,...,...
499,Insult to the Modesty of Women,2024_cases,-,2024
500,Cruelty by Husband or his Relatives,2024_cases,-,2024
501,"Misc. BNS/IPC Crimes (Total of 54-57,E6-E7&A1-A2)",2024_cases,733481,2024
502,Other BNS/IPC crimes,2024_cases,602806,2024
503,Total Cognizable BNS/IPC crimes,2024_cases,3544608,2024

In [311]:
cases_df.drop(
    columns=['year_metric'],
    inplace=True
)

In [312]:
cases_df['crime_head'] = (

    cases_df['crime_head']

    .str.lower()

    .str.replace(' ', '_')

    .str.replace('-', '_')

    .str.replace('/', '_')

)

In [313]:
cases_df['category'] = 'IPC/BNS Crimes'

In [314]:
cases_df = cases_df[
    [
        'category',
        'crime_head',
        'year',
        'cases'
    ]
]

In [316]:
cases_df

,category,crime_head,year,cases
0,IPC/BNS Crimes,sexual_intercourse_by_employing_deceitful_means,2022,-
1,IPC/BNS Crimes,disclosure_of_identity_of_victim,2022,-
2,IPC/BNS Crimes,assault_on_women_with_intent_to_outrage_her_mo...,2022,44867
3,IPC/BNS Crimes,sexual_harassment,2022,17809
4,IPC/BNS Crimes,at_office_premises,2022,419
...,...,...,...,...
499,IPC/BNS Crimes,insult_to_the_modesty_of_women,2024,-
500,IPC/BNS Crimes,cruelty_by_husband_or_his_relatives,2024,-
501,IPC/BNS Crimes,"misc._bns_ipc_crimes_(total_of_54_57,e6_e7&a1_a2)",2024,733481
502,IPC/BNS Crimes,other_bns_ipc_crimes,2024,602806
503,IPC/BNS Crimes,total_cognizable_bns_ipc_crimes,2024,3544608

In [317]:
cases_df['cases'].isna().sum()

np.int64(0)

In [318]:
cases_df[
    cases_df['cases'].isna()
].head()

Empty DataFrame
Columns: [category, crime_head, year, cases]
Index: []

In [319]:
cases_df.dropna(
    subset=['cases'],
    inplace=True
)

NameError: name 'cases' is not defined

In [321]:
cases_df.reset_index(
    drop=True,
    inplace=True
)

In [322]:
cases_df.isna().sum()

category      0
crime_head    0
year          0
cases         0
dtype: int64

In [323]:
cases_df

,category,crime_head,year,cases
0,IPC/BNS Crimes,sexual_intercourse_by_employing_deceitful_means,2022,-
1,IPC/BNS Crimes,disclosure_of_identity_of_victim,2022,-
2,IPC/BNS Crimes,assault_on_women_with_intent_to_outrage_her_mo...,2022,44867
3,IPC/BNS Crimes,sexual_harassment,2022,17809
4,IPC/BNS Crimes,at_office_premises,2022,419
...,...,...,...,...
499,IPC/BNS Crimes,insult_to_the_modesty_of_women,2024,-
500,IPC/BNS Crimes,cruelty_by_husband_or_his_relatives,2024,-
501,IPC/BNS Crimes,"misc._bns_ipc_crimes_(total_of_54_57,e6_e7&a1_a2)",2024,733481
502,IPC/BNS Crimes,other_bns_ipc_crimes,2024,602806
503,IPC/BNS Crimes,total_cognizable_bns_ipc_crimes,2024,3544608

In [324]:
cases_df['year'] = cases_df['year'].astype(int)

In [330]:

cases_df.info

<bound method DataFrame.info of            category                                         crime_head  year  \
0    IPC/BNS Crimes    sexual_intercourse_by_employing_deceitful_means  2022
1    IPC/BNS Crimes                   disclosure_of_identity_of_victim  2022
2    IPC/BNS Crimes  assault_on_women_with_intent_to_outrage_her_mo...  2022
3    IPC/BNS Crimes                                  sexual_harassment  2022
4    IPC/BNS Crimes                                 at_office_premises  2022
..              ...                                                ...   ...
499  IPC/BNS Crimes                     insult_to_the_modesty_of_women  2024
500  IPC/BNS Crimes                cruelty_by_husband_or_his_relatives  2024
501  IPC/BNS Crimes  misc._bns_ipc_crimes_(total_of_54_57,e6_e7&a1_a2)  2024
502  IPC/BNS Crimes                               other_bns_ipc_crimes  2024
503  IPC/BNS Crimes                    total_cognizable_bns_ipc_crimes  2024

       cases
0          -
1          -
2      44867
3      17809
4        419
..       ...
499        -
500        -
501   733481
502   602806
503  3544608

[504 rows x 4 columns]>

In [331]:
cases_df.shape

(504, 4)

In [333]:
cases_df['year'] = cases_df['year'].astype(int)

In [336]:
cases_df

,category,crime_head,year,cases
0,IPC/BNS Crimes,sexual_intercourse_by_employing_deceitful_means,2022,-
1,IPC/BNS Crimes,disclosure_of_identity_of_victim,2022,-
2,IPC/BNS Crimes,assault_on_women_with_intent_to_outrage_her_mo...,2022,44867
3,IPC/BNS Crimes,sexual_harassment,2022,17809
4,IPC/BNS Crimes,at_office_premises,2022,419
...,...,...,...,...
499,IPC/BNS Crimes,insult_to_the_modesty_of_women,2024,-
500,IPC/BNS Crimes,cruelty_by_husband_or_his_relatives,2024,-
501,IPC/BNS Crimes,"misc._bns_ipc_crimes_(total_of_54_57,e6_e7&a1_a2)",2024,733481
502,IPC/BNS Crimes,other_bns_ipc_crimes,2024,602806
503,IPC/BNS Crimes,total_cognizable_bns_ipc_crimes,2024,3544608

In [337]:
cases_df.to_csv(
    "../cleaned data/fact_ipc_bns_crime_heads.csv",
    index=False
)

**Metropolitan Cities - SLL Crimes**

In [348]:
path10='../raw data/Metropolitan Cities - SLL Crimes 2022-24(table_1b.2).xlsx'

In [349]:
df = pd.read_excel(path10,header=1)
df.head(10)

,SL,City,2022,2023,2024,Actual Population (in Lakhs) (2011),Rate of Cognizable Crimes (SLL) (2024),Chargesheeting Rate (2024)
0,1.0,Ahmedabad (Gujarat),30973,24073,26444,63.5,416.3,99.7
1,2.0,Bengaluru (Karnataka),17521,26883,22840,85.0,268.7,40.7
2,3.0,Chennai (Tamil Nadu),24052,20804,30001,87.0,345.0,99.6
3,4.0,Coimbatore (Tamil Nadu),4708,4115,3098,21.5,144.0,91.4
4,5.0,Delhi City,19567,19934,22264,163.1,136.5,98.9
5,6.0,Ghaziabad (Uttar Pradesh),3347,2157,1567,23.6,66.4,69.1
6,7.0,Hyderabad (Telangana),2515,3975,3278,77.5,42.3,75.9
7,8.0,Indore (Madhya Pradesh),10491,5949,5191,21.7,239.5,99.8
8,9.0,Jaipur (Rajasthan),8790,9266,9203,30.7,299.5,94.4
9,10.0,Kanpur (Uttar Pradesh),3539,2462,2426,29.2,83.1,95.0

In [350]:
df = clean_column_names(df)

In [351]:
df = clean_year_columns(df)

In [352]:
df = remove_empty_rows(df)

In [353]:
df= remove_total_rows(df)

In [354]:
df =remove_unwanted_columns(df)

In [355]:
df

,city,2022,2023,2024,actual_population_(in_lakhs)_(2011),rate_of_cognizable_crimes_(sll)_(2024),chargesheeting_rate_(2024)
0,Ahmedabad (Gujarat),30973,24073,26444,63.5,416.3,99.7
1,Bengaluru (Karnataka),17521,26883,22840,85.0,268.7,40.7
2,Chennai (Tamil Nadu),24052,20804,30001,87.0,345.0,99.6
3,Coimbatore (Tamil Nadu),4708,4115,3098,21.5,144.0,91.4
4,Delhi City,19567,19934,22264,163.1,136.5,98.9
5,Ghaziabad (Uttar Pradesh),3347,2157,1567,23.6,66.4,69.1
6,Hyderabad (Telangana),2515,3975,3278,77.5,42.3,75.9
7,Indore (Madhya Pradesh),10491,5949,5191,21.7,239.5,99.8
8,Jaipur (Rajasthan),8790,9266,9203,30.7,299.5,94.4
9,Kanpur (Uttar Pradesh),3539,2462,2426,29.2,83.1,95.0
10,Kochi (Kerala),15493,42887,11473,21.2,541.7,99.6
11,Kolkata (West Bengal),1175,900,1355,141.1,9.6,95.9
12,Kozhikode (Kerala),3515,7397,5444,20.3,268.0,99.2
13,Lucknow (Uttar Pradesh),3943,13449,16954,29.0,584.4,61.9
14,Mumbai (Maharashtra),19809,20568,18626,184.1,101.2,99.4
15,Nagpur (Maharashtra),6278,6739,6111,25.0,244.6,99.1
16,Patna (Bihar),8871,9213,4749,20.5,232.0,100.0
17,Pune (Maharashtra),3099,4480,4852,50.5,96.1,97.2
18,Surat (Gujarat),45428,51689,51933,45.8,1132.7,99.9

In [356]:
df.columns

Index(['city', '2022', '2023', '2024', 'actual_population_(in_lakhs)_(2011)',
       'rate_of_cognizable_crimes_(sll)_(2024)', 'chargesheeting_rate_(2024)'],
      dtype='object')

In [357]:
df = extract_city_state(df)

In [358]:
df

,city,2022,2023,2024,actual_population_(in_lakhs)_(2011),rate_of_cognizable_crimes_(sll)_(2024),chargesheeting_rate_(2024),state
0,Ahmedabad,30973,24073,26444,63.5,416.3,99.7,Gujarat
1,Bengaluru,17521,26883,22840,85.0,268.7,40.7,Karnataka
2,Chennai,24052,20804,30001,87.0,345.0,99.6,Tamil Nadu
3,Coimbatore,4708,4115,3098,21.5,144.0,91.4,Tamil Nadu
4,Delhi City,19567,19934,22264,163.1,136.5,98.9,Delhi
5,Ghaziabad,3347,2157,1567,23.6,66.4,69.1,Uttar Pradesh
6,Hyderabad,2515,3975,3278,77.5,42.3,75.9,Telangana
7,Indore,10491,5949,5191,21.7,239.5,99.8,Madhya Pradesh
8,Jaipur,8790,9266,9203,30.7,299.5,94.4,Rajasthan
9,Kanpur,3539,2462,2426,29.2,83.1,95.0,Uttar Pradesh
10,Kochi,15493,42887,11473,21.2,541.7,99.6,Kerala
11,Kolkata,1175,900,1355,141.1,9.6,95.9,West Bengal
12,Kozhikode,3515,7397,5444,20.3,268.0,99.2,Kerala
13,Lucknow,3943,13449,16954,29.0,584.4,61.9,Uttar Pradesh
14,Mumbai,19809,20568,18626,184.1,101.2,99.4,Maharashtra
15,Nagpur,6278,6739,6111,25.0,244.6,99.1,Maharashtra
16,Patna,8871,9213,4749,20.5,232.0,100.0,Bihar
17,Pune,3099,4480,4852,50.5,96.1,97.2,Maharashtra
18,Surat,45428,51689,51933,45.8,1132.7,99.9,Gujarat

In [359]:
df_long = df.melt(

    id_vars=[
        'state',
        'city',
        'actual_population_(in_lakhs)_(2011)',
        'rate_of_cognizable_crimes_(sll)_(2024)',
        'chargesheeting_rate_(2024)'
    ],

    value_vars=[
        '2022',
        '2023',
        '2024'
    ],

    var_name='year',

    value_name='cases'
)

In [360]:
df_long.rename(columns={

    'actual_population_(in_lakhs)_(2011)':
    'population_lakhs_2011',

    'rate_of_cognizable_crimes_(sll)_(2024)':
    'crime_rate_2024',

    'chargesheeting_rate_(2024)':
    'chargesheeting_rate_2024'

}, inplace=True)

In [361]:
df_long['category'] = 'SLL Crimes'

In [362]:
df_long

,state,city,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024,year,cases,category
0,Gujarat,Ahmedabad,63.5,416.3,99.7,2022,30973,SLL Crimes
1,Karnataka,Bengaluru,85.0,268.7,40.7,2022,17521,SLL Crimes
2,Tamil Nadu,Chennai,87.0,345.0,99.6,2022,24052,SLL Crimes
3,Tamil Nadu,Coimbatore,21.5,144.0,91.4,2022,4708,SLL Crimes
4,Delhi,Delhi City,163.1,136.5,98.9,2022,19567,SLL Crimes
5,Uttar Pradesh,Ghaziabad,23.6,66.4,69.1,2022,3347,SLL Crimes
6,Telangana,Hyderabad,77.5,42.3,75.9,2022,2515,SLL Crimes
7,Madhya Pradesh,Indore,21.7,239.5,99.8,2022,10491,SLL Crimes
8,Rajasthan,Jaipur,30.7,299.5,94.4,2022,8790,SLL Crimes
9,Uttar Pradesh,Kanpur,29.2,83.1,95.0,2022,3539,SLL Crimes
10,Kerala,Kochi,21.2,541.7,99.6,2022,15493,SLL Crimes
11,West Bengal,Kolkata,141.1,9.6,95.9,2022,1175,SLL Crimes
12,Kerala,Kozhikode,20.3,268.0,99.2,2022,3515,SLL Crimes
13,Uttar Pradesh,Lucknow,29.0,584.4,61.9,2022,3943,SLL Crimes
14,Maharashtra,Mumbai,184.1,101.2,99.4,2022,19809,SLL Crimes
15,Maharashtra,Nagpur,25.0,244.6,99.1,2022,6278,SLL Crimes
16,Bihar,Patna,20.5,232.0,100.0,2022,8871,SLL Crimes
17,Maharashtra,Pune,50.5,96.1,97.2,2022,3099,SLL Crimes
18,Gujarat,Surat,45.8,1132.7,99.9,2022,45428,SLL Crimes
19,Gujarat,Ahmedabad,63.5,416.3,99.7,2023,24073,SLL Crimes
20,Karnataka,Bengaluru,85.0,268.7,40.7,2023,26883,SLL Crimes
21,Tamil Nadu,Chennai,87.0,345.0,99.6,2023,20804,SLL Crimes
22,Tamil Nadu,Coimbatore,21.5,144.0,91.4,2023,4115,SLL Crimes
23,Delhi,Delhi City,163.1,136.5,98.9,2023,19934,SLL Crimes
24,Uttar Pradesh,Ghaziabad,23.6,66.4,69.1,2023,2157,SLL Crimes
25,Telangana,Hyderabad,77.5,42.3,75.9,2023,3975,SLL Crimes
26,Madhya Pradesh,Indore,21.7,239.5,99.8,2023,5949,SLL Crimes
27,Rajasthan,Jaipur,30.7,299.5,94.4,2023,9266,SLL Crimes
28,Uttar Pradesh,Kanpur,29.2,83.1,95.0,2023,2462,SLL Crimes
29,Kerala,Kochi,21.2,541.7,99.6,2023,42887,SLL Crimes
30,West Bengal,Kolkata,141.1,9.6,95.9,2023,900,SLL Crimes
31,Kerala,Kozhikode,20.3,268.0,99.2,2023,7397,SLL Crimes
32,Uttar Pradesh,Lucknow,29.0,584.4,61.9,2023,13449,SLL Crimes
33,Maharashtra,Mumbai,184.1,101.2,99.4,2023,20568,SLL Crimes
34,Maharashtra,Nagpur,25.0,244.6,99.1,2023,6739,SLL Crimes
35,Bihar,Patna,20.5,232.0,100.0,2023,9213,SLL Crimes
36,Maharashtra,Pune,50.5,96.1,97.2,2023,4480,SLL Crimes
37,Gujarat,Surat,45.8,1132.7,99.9,2023,51689,SLL Crimes
38,Gujarat,Ahmedabad,63.5,416.3,99.7,2024,26444,SLL Crimes
39,Karnataka,Bengaluru,85.0,268.7,40.7,2024,22840,SLL Crimes
40,Tamil Nadu,Chennai,87.0,345.0,99.6,2024,30001,SLL Crimes
41,Tamil Nadu,Coimbatore,21.5,144.0,91.4,2024,3098,SLL Crimes
42,Delhi,Delhi City,163.1,136.5,98.9,2024,22264,SLL Crimes
43,Uttar Pradesh,Ghaziabad,23.6,66.4,69.1,2024,1567,SLL Crimes
44,Telangana,Hyderabad,77.5,42.3,75.9,2024,3278,SLL Crimes
45,Madhya Pradesh,Indore,21.7,239.5,99.8,2024,5191,SLL Crimes
46,Rajasthan,Jaipur,30.7,299.5,94.4,2024,9203,SLL Crimes
47,Uttar Pradesh,Kanpur,29.2,83.1,95.0,2024,2426,SLL Crimes
48,Kerala,Kochi,21.2,541.7,99.6,2024,11473,SLL Crimes
49,West Bengal,Kolkata,141.1,9.6,95.9,2024,1355,SLL Crimes
50,Kerala,Kozhikode,20.3,268.0,99.2,2024,5444,SLL Crimes
51,Uttar Pradesh,Lucknow,29.0,584.4,61.9,2024,16954,SLL Crimes
52,Maharashtra,Mumbai,184.1,101.2,99.4,2024,18626,SLL Crimes
53,Maharashtra,Nagpur,25.0,244.6,99.1,2024,6111,SLL Crimes
54,Bihar,Patna,20.5,232.0,100.0,2024,4749,SLL Crimes
55,Maharashtra,Pune,50.5,96.1,97.2,2024,4852,SLL Crimes
56,Gujarat,Surat,45.8,1132.7,99.9,2024,51933,SLL Crimes

In [366]:
df_long = df_long[
    [
        'year',
        'state',
        'city',
        'category',
        'cases',
        'population_lakhs_2011',
        'crime_rate_2024',
        'chargesheeting_rate_2024'
    ]
]

In [367]:
df_long = final_cleaning(df_long)

In [369]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,SLL Crimes,30973,63.5,416.3,99.7
1,2022,Karnataka,Bengaluru,SLL Crimes,17521,85.0,268.7,40.7
2,2022,Tamil Nadu,Chennai,SLL Crimes,24052,87.0,345.0,99.6
3,2022,Tamil Nadu,Coimbatore,SLL Crimes,4708,21.5,144.0,91.4
4,2022,Delhi,Delhi City,SLL Crimes,19567,163.1,136.5,98.9
5,2022,Uttar Pradesh,Ghaziabad,SLL Crimes,3347,23.6,66.4,69.1
6,2022,Telangana,Hyderabad,SLL Crimes,2515,77.5,42.3,75.9
7,2022,Madhya Pradesh,Indore,SLL Crimes,10491,21.7,239.5,99.8
8,2022,Rajasthan,Jaipur,SLL Crimes,8790,30.7,299.5,94.4
9,2022,Uttar Pradesh,Kanpur,SLL Crimes,3539,29.2,83.1,95.0
10,2022,Kerala,Kochi,SLL Crimes,15493,21.2,541.7,99.6
11,2022,West Bengal,Kolkata,SLL Crimes,1175,141.1,9.6,95.9
12,2022,Kerala,Kozhikode,SLL Crimes,3515,20.3,268.0,99.2
13,2022,Uttar Pradesh,Lucknow,SLL Crimes,3943,29.0,584.4,61.9
14,2022,Maharashtra,Mumbai,SLL Crimes,19809,184.1,101.2,99.4
15,2022,Maharashtra,Nagpur,SLL Crimes,6278,25.0,244.6,99.1
16,2022,Bihar,Patna,SLL Crimes,8871,20.5,232.0,100.0
17,2022,Maharashtra,Pune,SLL Crimes,3099,50.5,96.1,97.2
18,2022,Gujarat,Surat,SLL Crimes,45428,45.8,1132.7,99.9
19,2023,Gujarat,Ahmedabad,SLL Crimes,24073,63.5,416.3,99.7
20,2023,Karnataka,Bengaluru,SLL Crimes,26883,85.0,268.7,40.7
21,2023,Tamil Nadu,Chennai,SLL Crimes,20804,87.0,345.0,99.6
22,2023,Tamil Nadu,Coimbatore,SLL Crimes,4115,21.5,144.0,91.4
23,2023,Delhi,Delhi City,SLL Crimes,19934,163.1,136.5,98.9
24,2023,Uttar Pradesh,Ghaziabad,SLL Crimes,2157,23.6,66.4,69.1
25,2023,Telangana,Hyderabad,SLL Crimes,3975,77.5,42.3,75.9
26,2023,Madhya Pradesh,Indore,SLL Crimes,5949,21.7,239.5,99.8
27,2023,Rajasthan,Jaipur,SLL Crimes,9266,30.7,299.5,94.4
28,2023,Uttar Pradesh,Kanpur,SLL Crimes,2462,29.2,83.1,95.0
29,2023,Kerala,Kochi,SLL Crimes,42887,21.2,541.7,99.6
30,2023,West Bengal,Kolkata,SLL Crimes,900,141.1,9.6,95.9
31,2023,Kerala,Kozhikode,SLL Crimes,7397,20.3,268.0,99.2
32,2023,Uttar Pradesh,Lucknow,SLL Crimes,13449,29.0,584.4,61.9
33,2023,Maharashtra,Mumbai,SLL Crimes,20568,184.1,101.2,99.4
34,2023,Maharashtra,Nagpur,SLL Crimes,6739,25.0,244.6,99.1
35,2023,Bihar,Patna,SLL Crimes,9213,20.5,232.0,100.0
36,2023,Maharashtra,Pune,SLL Crimes,4480,50.5,96.1,97.2
37,2023,Gujarat,Surat,SLL Crimes,51689,45.8,1132.7,99.9
38,2024,Gujarat,Ahmedabad,SLL Crimes,26444,63.5,416.3,99.7
39,2024,Karnataka,Bengaluru,SLL Crimes,22840,85.0,268.7,40.7
40,2024,Tamil Nadu,Chennai,SLL Crimes,30001,87.0,345.0,99.6
41,2024,Tamil Nadu,Coimbatore,SLL Crimes,3098,21.5,144.0,91.4
42,2024,Delhi,Delhi City,SLL Crimes,22264,163.1,136.5,98.9
43,2024,Uttar Pradesh,Ghaziabad,SLL Crimes,1567,23.6,66.4,69.1
44,2024,Telangana,Hyderabad,SLL Crimes,3278,77.5,42.3,75.9
45,2024,Madhya Pradesh,Indore,SLL Crimes,5191,21.7,239.5,99.8
46,2024,Rajasthan,Jaipur,SLL Crimes,9203,30.7,299.5,94.4
47,2024,Uttar Pradesh,Kanpur,SLL Crimes,2426,29.2,83.1,95.0
48,2024,Kerala,Kochi,SLL Crimes,11473,21.2,541.7,99.6
49,2024,West Bengal,Kolkata,SLL Crimes,1355,141.1,9.6,95.9
50,2024,Kerala,Kozhikode,SLL Crimes,5444,20.3,268.0,99.2
51,2024,Uttar Pradesh,Lucknow,SLL Crimes,16954,29.0,584.4,61.9
52,2024,Maharashtra,Mumbai,SLL Crimes,18626,184.1,101.2,99.4
53,2024,Maharashtra,Nagpur,SLL Crimes,6111,25.0,244.6,99.1
54,2024,Bihar,Patna,SLL Crimes,4749,20.5,232.0,100.0
55,2024,Maharashtra,Pune,SLL Crimes,4852,50.5,96.1,97.2
56,2024,Gujarat,Surat,SLL Crimes,51933,45.8,1132.7,99.9

In [370]:
df_long.to_csv(
    "../cleaned data/master_sll_crimes.csv",
    index=False
)

**Metropolitan Cities - IPC and BNS Crimes**

In [43]:
path11='../raw data/Metropolitan Cities - Total IPC+BNS+SLL Crimes 2022-24(table_1b.3).xlsx'

In [44]:
df = pd.read_excel(path11,header=1)
df.head()

,SL,City,2022,2023,2024,Actual Population (in Lakhs) (2011),Rate of Cognizable Crimes (IPC+SLL) (2024),Chargesheeting Rate (2024)
0,1.0,Ahmedabad (Gujarat),53845,53311,49250,63.5,775.3,93.0
1,2.0,Bengaluru (Karnataka),46187,68520,57555,85.0,677.2,54.4
2,3.0,Chennai (Tamil Nadu),39138,36502,45766,87.0,526.3,93.8
3,4.0,Coimbatore (Tamil Nadu),9250,8812,7942,21.5,369.2,80.0
4,5.0,Delhi City,318555,343483,297666,163.1,1824.5,36.8

In [45]:
df.columns

Index(['SL', 'City', '2022', '2023', '2024',
       'Actual Population (in Lakhs) (2011)',
       'Rate of Cognizable Crimes (IPC+SLL) (2024)',
       'Chargesheeting Rate (2024)'],
      dtype='object')

In [46]:
df = clean_column_names(df)

In [47]:
df= clean_year_columns(df)

In [48]:
df = remove_empty_rows(df)

In [49]:
df = remove_total_rows(df)

In [50]:
df= remove_unwanted_columns(df)

In [51]:
df

,city,2022,2023,2024,actual_population_(in_lakhs)_(2011),rate_of_cognizable_crimes_(ipc+sll)_(2024),chargesheeting_rate_(2024)
0,Ahmedabad (Gujarat),53845,53311,49250,63.5,775.3,93.0
1,Bengaluru (Karnataka),46187,68520,57555,85.0,677.2,54.4
2,Chennai (Tamil Nadu),39138,36502,45766,87.0,526.3,93.8
3,Coimbatore (Tamil Nadu),9250,8812,7942,21.5,369.2,80.0
4,Delhi City,318555,343483,297666,163.1,1824.5,36.8
5,Ghaziabad (Uttar Pradesh),13207,11384,10530,23.6,446.4,55.1
6,Hyderabad (Telangana),23183,25749,30309,77.5,391.1,59.0
7,Indore (Madhya Pradesh),27127,24075,17360,21.7,801.1,73.9
8,Jaipur (Rajasthan),36961,39237,36946,30.7,1202.3,51.5
9,Kanpur (Uttar Pradesh),15260,13114,14776,29.2,506.0,80.4
10,Kochi (Kerala),28766,67616,21516,21.2,1015.9,96.5
11,Kolkata (West Bengal),12213,11843,13219,141.1,93.7,95.4
12,Kozhikode (Kerala),11589,18002,15754,20.3,775.7,95.6
13,Lucknow (Uttar Pradesh),19058,29472,31421,29.0,1083.1,67.4
14,Mumbai (Maharashtra),89098,65441,70054,184.1,380.4,80.8
15,Nagpur (Maharashtra),19167,24036,21898,25.0,876.6,77.9
16,Patna (Bihar),21393,23530,17217,20.5,841.1,78.3
17,Pune (Maharashtra),14173,17022,18560,50.5,367.5,80.9
18,Surat (Gujarat),55300,63142,63166,45.8,1377.7,97.7

In [52]:
df =extract_city_state(df)

In [53]:
df_long = df.melt(

    id_vars=[
        'state',
        'city',
        'actual_population_(in_lakhs)_(2011)',
        'rate_of_cognizable_crimes_(ipc+sll)_(2024)',
        'chargesheeting_rate_(2024)'
    ],
    value_vars=['2022','2023','2024'],
    var_name='year',
    value_name='cases'
)

In [54]:
df_long.rename(columns={

    'actual_population_(in_lakhs)_(2011)':
    'population_lakhs_2011',

    'rate_of_cognizable_crimes_(ipc+sll)_(2024)':
    'crime_rate_2024',

    'chargesheeting_rate_(2024)':
    'chargesheeting_rate_2024'
}, inplace=True)

In [55]:
df_long['category'] = 'Total IPC+BNS+SLL Crimes'

In [56]:
df_long = df_long[
    [
        'year',
        'state',
        'city',
        'category',
        'cases',
        'population_lakhs_2011',
        'crime_rate_2024',
        'chargesheeting_rate_2024'
    ]
]

In [57]:
df_long = final_cleaning(df_long)

In [58]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,Total IPC+BNS+SLL Crimes,53845,63.5,775.3,93.0
1,2022,Karnataka,Bengaluru,Total IPC+BNS+SLL Crimes,46187,85.0,677.2,54.4
2,2022,Tamil Nadu,Chennai,Total IPC+BNS+SLL Crimes,39138,87.0,526.3,93.8
3,2022,Tamil Nadu,Coimbatore,Total IPC+BNS+SLL Crimes,9250,21.5,369.2,80.0
4,2022,Delhi,Delhi City,Total IPC+BNS+SLL Crimes,318555,163.1,1824.5,36.8
5,2022,Uttar Pradesh,Ghaziabad,Total IPC+BNS+SLL Crimes,13207,23.6,446.4,55.1
6,2022,Telangana,Hyderabad,Total IPC+BNS+SLL Crimes,23183,77.5,391.1,59.0
7,2022,Madhya Pradesh,Indore,Total IPC+BNS+SLL Crimes,27127,21.7,801.1,73.9
8,2022,Rajasthan,Jaipur,Total IPC+BNS+SLL Crimes,36961,30.7,1202.3,51.5
9,2022,Uttar Pradesh,Kanpur,Total IPC+BNS+SLL Crimes,15260,29.2,506.0,80.4
10,2022,Kerala,Kochi,Total IPC+BNS+SLL Crimes,28766,21.2,1015.9,96.5
11,2022,West Bengal,Kolkata,Total IPC+BNS+SLL Crimes,12213,141.1,93.7,95.4
12,2022,Kerala,Kozhikode,Total IPC+BNS+SLL Crimes,11589,20.3,775.7,95.6
13,2022,Uttar Pradesh,Lucknow,Total IPC+BNS+SLL Crimes,19058,29.0,1083.1,67.4
14,2022,Maharashtra,Mumbai,Total IPC+BNS+SLL Crimes,89098,184.1,380.4,80.8
15,2022,Maharashtra,Nagpur,Total IPC+BNS+SLL Crimes,19167,25.0,876.6,77.9
16,2022,Bihar,Patna,Total IPC+BNS+SLL Crimes,21393,20.5,841.1,78.3
17,2022,Maharashtra,Pune,Total IPC+BNS+SLL Crimes,14173,50.5,367.5,80.9
18,2022,Gujarat,Surat,Total IPC+BNS+SLL Crimes,55300,45.8,1377.7,97.7
19,2023,Gujarat,Ahmedabad,Total IPC+BNS+SLL Crimes,53311,63.5,775.3,93.0
20,2023,Karnataka,Bengaluru,Total IPC+BNS+SLL Crimes,68520,85.0,677.2,54.4
21,2023,Tamil Nadu,Chennai,Total IPC+BNS+SLL Crimes,36502,87.0,526.3,93.8
22,2023,Tamil Nadu,Coimbatore,Total IPC+BNS+SLL Crimes,8812,21.5,369.2,80.0
23,2023,Delhi,Delhi City,Total IPC+BNS+SLL Crimes,343483,163.1,1824.5,36.8
24,2023,Uttar Pradesh,Ghaziabad,Total IPC+BNS+SLL Crimes,11384,23.6,446.4,55.1
25,2023,Telangana,Hyderabad,Total IPC+BNS+SLL Crimes,25749,77.5,391.1,59.0
26,2023,Madhya Pradesh,Indore,Total IPC+BNS+SLL Crimes,24075,21.7,801.1,73.9
27,2023,Rajasthan,Jaipur,Total IPC+BNS+SLL Crimes,39237,30.7,1202.3,51.5
28,2023,Uttar Pradesh,Kanpur,Total IPC+BNS+SLL Crimes,13114,29.2,506.0,80.4
29,2023,Kerala,Kochi,Total IPC+BNS+SLL Crimes,67616,21.2,1015.9,96.5
30,2023,West Bengal,Kolkata,Total IPC+BNS+SLL Crimes,11843,141.1,93.7,95.4
31,2023,Kerala,Kozhikode,Total IPC+BNS+SLL Crimes,18002,20.3,775.7,95.6
32,2023,Uttar Pradesh,Lucknow,Total IPC+BNS+SLL Crimes,29472,29.0,1083.1,67.4
33,2023,Maharashtra,Mumbai,Total IPC+BNS+SLL Crimes,65441,184.1,380.4,80.8
34,2023,Maharashtra,Nagpur,Total IPC+BNS+SLL Crimes,24036,25.0,876.6,77.9
35,2023,Bihar,Patna,Total IPC+BNS+SLL Crimes,23530,20.5,841.1,78.3
36,2023,Maharashtra,Pune,Total IPC+BNS+SLL Crimes,17022,50.5,367.5,80.9
37,2023,Gujarat,Surat,Total IPC+BNS+SLL Crimes,63142,45.8,1377.7,97.7
38,2024,Gujarat,Ahmedabad,Total IPC+BNS+SLL Crimes,49250,63.5,775.3,93.0
39,2024,Karnataka,Bengaluru,Total IPC+BNS+SLL Crimes,57555,85.0,677.2,54.4
40,2024,Tamil Nadu,Chennai,Total IPC+BNS+SLL Crimes,45766,87.0,526.3,93.8
41,2024,Tamil Nadu,Coimbatore,Total IPC+BNS+SLL Crimes,7942,21.5,369.2,80.0
42,2024,Delhi,Delhi City,Total IPC+BNS+SLL Crimes,297666,163.1,1824.5,36.8
43,2024,Uttar Pradesh,Ghaziabad,Total IPC+BNS+SLL Crimes,10530,23.6,446.4,55.1
44,2024,Telangana,Hyderabad,Total IPC+BNS+SLL Crimes,30309,77.5,391.1,59.0
45,2024,Madhya Pradesh,Indore,Total IPC+BNS+SLL Crimes,17360,21.7,801.1,73.9
46,2024,Rajasthan,Jaipur,Total IPC+BNS+SLL Crimes,36946,30.7,1202.3,51.5
47,2024,Uttar Pradesh,Kanpur,Total IPC+BNS+SLL Crimes,14776,29.2,506.0,80.4
48,2024,Kerala,Kochi,Total IPC+BNS+SLL Crimes,21516,21.2,1015.9,96.5
49,2024,West Bengal,Kolkata,Total IPC+BNS+SLL Crimes,13219,141.1,93.7,95.4
50,2024,Kerala,Kozhikode,Total IPC+BNS+SLL Crimes,15754,20.3,775.7,95.6
51,2024,Uttar Pradesh,Lucknow,Total IPC+BNS+SLL Crimes,31421,29.0,1083.1,67.4
52,2024,Maharashtra,Mumbai,Total IPC+BNS+SLL Crimes,70054,184.1,380.4,80.8
53,2024,Maharashtra,Nagpur,Total IPC+BNS+SLL Crimes,21898,25.0,876.6,77.9
54,2024,Bihar,Patna,Total IPC+BNS+SLL Crimes,17217,20.5,841.1,78.3
55,2024,Maharashtra,Pune,Total IPC+BNS+SLL Crimes,18560,50.5,367.5,80.9
56,2024,Gujarat,Surat,Total IPC+BNS+SLL Crimes,63166,45.8,1377.7,97.7

In [59]:
df_long.to_csv(
    "../cleaned data/master_total_ipc_bns_sll.csv",
    index=False
)

**Metropolitan Cities - IPC and BNS Crimes 2022-24**

In [416]:
path12= '../raw data/Metropolitan Cities - IPC and BNS Crimes 2022-24(table_1b.1).xlsx'

In [418]:
df =pd.read_excel(path12,header=1)
df.head(10)

,SL,City,2022,2023,2024 IPC Cases,2024 BNS Cases,2024 Total (IPC+BNS),Actual Population (in Lakhs) (2011),Rate of Cognizable Crimes (2024),Chargesheeting Rate (2024)
0,1.0,Ahmedabad (Gujarat),22872,29238,12926,9880,22806,63.5,359.0,85.1
1,2.0,Bengaluru (Karnataka),28666,41637,20300,14415,34715,85.0,408.5,63.4
2,3.0,Chennai (Tamil Nadu),15086,15698,9867,5898,15765,87.0,181.3,71.6
3,4.0,Coimbatore (Tamil Nadu),4542,4697,2781,2063,4844,21.5,225.2,74.0
4,5.0,Delhi City,298988,323549,136669,138733,275402,163.1,1688.0,31.9
5,6.0,Ghaziabad (Uttar Pradesh),9860,9227,4856,4107,8963,23.6,379.9,52.3
6,7.0,Hyderabad (Telangana),20668,21774,16114,10917,27031,77.5,348.8,56.9
7,8.0,Indore (Madhya Pradesh),16636,18126,7059,5110,12169,21.7,561.6,63.4
8,9.0,Jaipur (Rajasthan),28171,29971,17771,9972,27743,30.7,902.8,37.4
9,10.0,Kanpur (Uttar Pradesh),11721,10652,6183,6167,12350,29.2,422.9,77.3

In [419]:
df = clean_column_names(df)

In [420]:
df=clean_year_columns(df)

In [421]:
df=remove_empty_rows(df)
df=remove_total_rows(df)
df=remove_unwanted_columns(df)

In [423]:
df.head(5)

,city,2022,2023,2024_ipc_cases,2024_bns_cases,2024_total_(ipc+bns),actual_population_(in_lakhs)_(2011),rate_of_cognizable_crimes_(2024),chargesheeting_rate_(2024)
0,Ahmedabad (Gujarat),22872,29238,12926,9880,22806,63.5,359.0,85.1
1,Bengaluru (Karnataka),28666,41637,20300,14415,34715,85.0,408.5,63.4
2,Chennai (Tamil Nadu),15086,15698,9867,5898,15765,87.0,181.3,71.6
3,Coimbatore (Tamil Nadu),4542,4697,2781,2063,4844,21.5,225.2,74.0
4,Delhi City,298988,323549,136669,138733,275402,163.1,1688.0,31.9

In [424]:
df['2024']=df['2024_total_(ipc+bns)']

In [426]:
df.head()

,city,2022,2023,2024_ipc_cases,2024_bns_cases,2024_total_(ipc+bns),actual_population_(in_lakhs)_(2011),rate_of_cognizable_crimes_(2024),chargesheeting_rate_(2024),2024
0,Ahmedabad (Gujarat),22872,29238,12926,9880,22806,63.5,359.0,85.1,22806
1,Bengaluru (Karnataka),28666,41637,20300,14415,34715,85.0,408.5,63.4,34715
2,Chennai (Tamil Nadu),15086,15698,9867,5898,15765,87.0,181.3,71.6,15765
3,Coimbatore (Tamil Nadu),4542,4697,2781,2063,4844,21.5,225.2,74.0,4844
4,Delhi City,298988,323549,136669,138733,275402,163.1,1688.0,31.9,275402

In [429]:
df.drop(['2024_ipc_cases','2024_bns_cases','2024_total_(ipc+bns)'],axis=1,inplace=True)

In [430]:
df.head()

,city,2022,2023,actual_population_(in_lakhs)_(2011),rate_of_cognizable_crimes_(2024),chargesheeting_rate_(2024),2024
0,Ahmedabad (Gujarat),22872,29238,63.5,359.0,85.1,22806
1,Bengaluru (Karnataka),28666,41637,85.0,408.5,63.4,34715
2,Chennai (Tamil Nadu),15086,15698,87.0,181.3,71.6,15765
3,Coimbatore (Tamil Nadu),4542,4697,21.5,225.2,74.0,4844
4,Delhi City,298988,323549,163.1,1688.0,31.9,275402

In [431]:
df= extract_city_state(df)

In [432]:
df.columns

Index(['city', '2022', '2023', 'actual_population_(in_lakhs)_(2011)',
       'rate_of_cognizable_crimes_(2024)', 'chargesheeting_rate_(2024)',
       '2024', 'state'],
      dtype='object')

In [433]:
df_long = df.melt(

    id_vars=[
        'state','city','actual_population_(in_lakhs)_(2011)','rate_of_cognizable_crimes_(2024)','chargesheeting_rate_(2024)'],
    value_vars=['2022','2023','2024'],
    var_name='year',
    value_name='cases'
)

In [434]:
df_long.rename(columns={

    'actual_population_(in_lakhs)_(2011)':
    'population_lakhs_2011',

    'rate_of_cognizable_crimes_(2024)':
    'crime_rate_2024',

    'chargesheeting_rate_(2024)':
    'chargesheeting_rate_2024'

}, inplace=True)

In [435]:
df_long['category'] = 'IPC and BNS Crimes'

In [436]:
df_long = df_long[
    [
        'year',
        'state',
        'city',
        'category',
        'cases',
        'population_lakhs_2011',
        'crime_rate_2024',
        'chargesheeting_rate_2024'
    ]
]

In [437]:
df_long = final_cleaning(df_long)

In [438]:
df_long.to_csv(
    "../cleaned data/master_ipc_bns_crimes.csv",
    index=False
)

In [462]:
df_long

,year,state,city,category,cases,population_lakhs_2011,crime_rate_2024,chargesheeting_rate_2024
0,2022,Gujarat,Ahmedabad,IPC and BNS Crimes,22872,63.5,359.0,85.1
1,2022,Karnataka,Bengaluru,IPC and BNS Crimes,28666,85.0,408.5,63.4
2,2022,Tamil Nadu,Chennai,IPC and BNS Crimes,15086,87.0,181.3,71.6
3,2022,Tamil Nadu,Coimbatore,IPC and BNS Crimes,4542,21.5,225.2,74.0
4,2022,Delhi,Delhi City,IPC and BNS Crimes,298988,163.1,1688.0,31.9
5,2022,Uttar Pradesh,Ghaziabad,IPC and BNS Crimes,9860,23.6,379.9,52.3
6,2022,Telangana,Hyderabad,IPC and BNS Crimes,20668,77.5,348.8,56.9
7,2022,Madhya Pradesh,Indore,IPC and BNS Crimes,16636,21.7,561.6,63.4
8,2022,Rajasthan,Jaipur,IPC and BNS Crimes,28171,30.7,902.8,37.4
9,2022,Uttar Pradesh,Kanpur,IPC and BNS Crimes,11721,29.2,422.9,77.3
10,2022,Kerala,Kochi,IPC and BNS Crimes,13273,21.2,474.2,92.9
11,2022,West Bengal,Kolkata,IPC and BNS Crimes,11038,141.1,84.1,95.3
12,2022,Kerala,Kozhikode,IPC and BNS Crimes,8074,20.3,507.6,93.5
13,2022,Uttar Pradesh,Lucknow,IPC and BNS Crimes,15115,29.0,498.7,69.3
14,2022,Maharashtra,Mumbai,IPC and BNS Crimes,69289,184.1,279.3,74.7
15,2022,Maharashtra,Nagpur,IPC and BNS Crimes,12889,25.0,632.0,69.8
16,2022,Bihar,Patna,IPC and BNS Crimes,12522,20.5,609.1,69.9
17,2022,Maharashtra,Pune,IPC and BNS Crimes,11074,50.5,271.4,76.7
18,2022,Gujarat,Surat,IPC and BNS Crimes,9872,45.8,245.0,87.7
19,2023,Gujarat,Ahmedabad,IPC and BNS Crimes,29238,63.5,359.0,85.1
20,2023,Karnataka,Bengaluru,IPC and BNS Crimes,41637,85.0,408.5,63.4
21,2023,Tamil Nadu,Chennai,IPC and BNS Crimes,15698,87.0,181.3,71.6
22,2023,Tamil Nadu,Coimbatore,IPC and BNS Crimes,4697,21.5,225.2,74.0
23,2023,Delhi,Delhi City,IPC and BNS Crimes,323549,163.1,1688.0,31.9
24,2023,Uttar Pradesh,Ghaziabad,IPC and BNS Crimes,9227,23.6,379.9,52.3
25,2023,Telangana,Hyderabad,IPC and BNS Crimes,21774,77.5,348.8,56.9
26,2023,Madhya Pradesh,Indore,IPC and BNS Crimes,18126,21.7,561.6,63.4
27,2023,Rajasthan,Jaipur,IPC and BNS Crimes,29971,30.7,902.8,37.4
28,2023,Uttar Pradesh,Kanpur,IPC and BNS Crimes,10652,29.2,422.9,77.3
29,2023,Kerala,Kochi,IPC and BNS Crimes,24729,21.2,474.2,92.9
30,2023,West Bengal,Kolkata,IPC and BNS Crimes,10943,141.1,84.1,95.3
31,2023,Kerala,Kozhikode,IPC and BNS Crimes,10605,20.3,507.6,93.5
32,2023,Uttar Pradesh,Lucknow,IPC and BNS Crimes,16023,29.0,498.7,69.3
33,2023,Maharashtra,Mumbai,IPC and BNS Crimes,44873,184.1,279.3,74.7
34,2023,Maharashtra,Nagpur,IPC and BNS Crimes,17297,25.0,632.0,69.8
35,2023,Bihar,Patna,IPC and BNS Crimes,14317,20.5,609.1,69.9
36,2023,Maharashtra,Pune,IPC and BNS Crimes,12542,50.5,271.4,76.7
37,2023,Gujarat,Surat,IPC and BNS Crimes,11453,45.8,245.0,87.7
38,2024,Gujarat,Ahmedabad,IPC and BNS Crimes,22806,63.5,359.0,85.1
39,2024,Karnataka,Bengaluru,IPC and BNS Crimes,34715,85.0,408.5,63.4
40,2024,Tamil Nadu,Chennai,IPC and BNS Crimes,15765,87.0,181.3,71.6
41,2024,Tamil Nadu,Coimbatore,IPC and BNS Crimes,4844,21.5,225.2,74.0
42,2024,Delhi,Delhi City,IPC and BNS Crimes,275402,163.1,1688.0,31.9
43,2024,Uttar Pradesh,Ghaziabad,IPC and BNS Crimes,8963,23.6,379.9,52.3
44,2024,Telangana,Hyderabad,IPC and BNS Crimes,27031,77.5,348.8,56.9
45,2024,Madhya Pradesh,Indore,IPC and BNS Crimes,12169,21.7,561.6,63.4
46,2024,Rajasthan,Jaipur,IPC and BNS Crimes,27743,30.7,902.8,37.4
47,2024,Uttar Pradesh,Kanpur,IPC and BNS Crimes,12350,29.2,422.9,77.3
48,2024,Kerala,Kochi,IPC and BNS Crimes,10043,21.2,474.2,92.9
49,2024,West Bengal,Kolkata,IPC and BNS Crimes,11864,141.1,84.1,95.3
50,2024,Kerala,Kozhikode,IPC and BNS Crimes,10310,20.3,507.6,93.5
51,2024,Uttar Pradesh,Lucknow,IPC and BNS Crimes,14467,29.0,498.7,69.3
52,2024,Maharashtra,Mumbai,IPC and BNS Crimes,51428,184.1,279.3,74.7
53,2024,Maharashtra,Nagpur,IPC and BNS Crimes,15787,25.0,632.0,69.8
54,2024,Bihar,Patna,IPC and BNS Crimes,12468,20.5,609.1,69.9
55,2024,Maharashtra,Pune,IPC and BNS Crimes,13708,50.5,271.4,76.7
56,2024,Gujarat,Surat,IPC and BNS Crimes,11233,45.8,245.0,87.7

**SLL CRIME HEADWISE**

In [2]:
path13='../raw data/SLL Crimes (Crime head-wise) 2022-24(table_1.3).xlsx'

In [3]:
df_raw = pd.read_excel(path13,header=None)
df_raw

,0,1,2,3,4,5,6,7,8
0,TABLE 1.3 - SLL Crimes (Crime Head-wise) - 202...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SL,Crime Head,2022,NaN,2023,NaN,2024,NaN,% Share of SLL Crimes
2,NaN,NaN,Cases,Crime Rate,Cases,Crime Rate,Cases,Crime Rate,NaN
3,1,The Dowry Prohibition Act,13479,1,15489,1.1,12343,0.9,0.5
4,2,The Immoral Traffic (Prevention) Act,1497,0.1,2166,0.2,2137,0.2,0.1
...,...,...,...,...,...,...,...,...,...
91,67,City/Town Police Acts,48501,3.5,50018,3.6,58372,4.2,2.5
92,68,Other State Local Acts,117426,8.5,109118,7.8,104820,7.5,4.5
93,NaN,Other Regulatory & Enforcement – Acts (Total o...,717843,52,830364,59.6,732802,52.2,31.3
94,69,Other SLL Crimes,75665,5.5,53670,3.9,63437,4.5,2.7
95,NaN,Total Cognizable SLL Crimes,2263567,164.1,2478467,178,2341259,166.6,100

In [4]:
df = df_raw.iloc[3:].copy()

In [5]:
df.columns = [

    'sl',
    'crime_head',

    '2022_cases',
    '2022_crime_rate',

    '2023_cases',
    '2023_crime_rate',

    '2024_cases',
    '2024_crime_rate',

    'share_percent'
]

In [6]:
df.reset_index(
    drop=True,
    inplace=True
)

In [7]:
df.head()

,sl,crime_head,2022_cases,2022_crime_rate,2023_cases,2023_crime_rate,2024_cases,2024_crime_rate,share_percent
0,1,The Dowry Prohibition Act,13479,1,15489,1.1,12343,0.9,0.5
1,2,The Immoral Traffic (Prevention) Act,1497,0.1,2166,0.2,2137,0.2,0.1
2,3,The Protection of Women from Domestic Violence...,468,0,632,0,616,0,0
3,4,The Indecent Representation of Women (Prohibit...,28,0,31,0,21,0,0
4,NaN,Crime Against Women – Related Acts (Total of S...,15472,1.1,18318,1.3,15117,1.1,0.6

In [8]:
df.columns

Index(['sl', 'crime_head', '2022_cases', '2022_crime_rate', '2023_cases',
       '2023_crime_rate', '2024_cases', '2024_crime_rate', 'share_percent'],
      dtype='object')

In [9]:
df = df[
    [
        'crime_head',
        '2022_cases',
        '2023_cases',
        '2024_cases'
    ]
]

In [10]:
cases_df = df.melt(

    id_vars=['crime_head'],

    value_vars=[
        '2022_cases',
        '2023_cases',
        '2024_cases'
    ],

    var_name='year_metric',

    value_name='cases'
)

In [11]:
cases_df['year'] = (
    cases_df['year_metric']
    .str.split('_')
    .str[0]
)

In [12]:
cases_df.drop(
    columns=['year_metric'],
    inplace=True
)

In [13]:
cases_df.head()

                                          crime_head  cases  year
0                          The Dowry Prohibition Act  13479  2022
1               The Immoral Traffic (Prevention) Act   1497  2022
2  The Protection of Women from Domestic Violence...    468  2022
3  The Indecent Representation of Women (Prohibit...     28  2022
4  Crime Against Women – Related Acts (Total of S...  15472  2022

In [14]:
cases_df.dropna(
    subset=['cases'],
    inplace=True
)

In [15]:
cases_df['year'] = (
    cases_df['year']
    .astype(int)
)

cases_df['cases'] = pd.to_numeric(
    cases_df['cases'],
    errors='coerce'
)

In [16]:
cases_df.dropna(
    subset=['cases'],
    inplace=True
)

In [17]:
cases_df['category'] = 'SLL Crimes'

In [18]:
cases_df = cases_df[
    [
        'category',
        'crime_head',
        'year',
        'cases'
    ]
]

In [19]:
cases_df.reset_index(
    drop=True,
    inplace=True
)

In [21]:
cases_df.to_csv(
    "../cleaned data/fact_sll_crime_heads.csv",
    index=False,
    encoding="utf-8"
)

**Total Cases Registered 2022-24**

In [530]:
path14='../raw data/Total Cases Registered 2022-2024(table_1.1).xlsx'
path15='../raw data/Total Cases table2.xlsx'

In [531]:
table1=pd.read_excel(path14)
table2=pd.read_excel(path15)

In [532]:
table1.rename(columns={

    'number_of_complaints':
    'complaints_received',

    'number_of_firs_registered':
    'firs_registered',

    'number_of_online/efir_registered':
    'online_efirs'

}, inplace=True)

In [533]:
table1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   TABLE 1.1 - Total Complaints Received and Cases Registered under IPC/BNS and SLL - 2024  16 non-null     object
 1   Unnamed: 1                                                                               18 non-null     object
 2   Unnamed: 2                                                                               17 non-null     object
 3   Unnamed: 3                                                                               17 non-null     object
 4   Unnamed: 4                                                                               18 non-null     object
dtypes: object(5)
memory usage: 892.0+ bytes

In [534]:
table1

,TABLE 1.1 - Total Complaints Received and Cases Registered under IPC/BNS and SLL - 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,SL,Type of Complaint,Number of Complaints,Number of FIRs Registered,Number of Online/eFIR Registered
1,NaN,NaN,NaN,NaN,NaN
2,1,Oral Complaints,9171426,717242,0
3,1.1,Narrated to O/C / SHO,961973,645919,0
4,1.2,Distress call over phone/Dial 100 etc,8209453,71323,0
5,2,Written Complaints,10245560,4970720,197905
6,2.1,To O/C / SHO,5263134,3345313,0
7,2.2,To SP/Senior Officers,1356812,137758,0
8,2.3,Electronic Form,926733,29571,197905
9,2.4,Court Complaints,95958,89092,0
10,2.5,NHRC & SHRC,21948,1177,0
11,2.6,Commissions for SCs,6133,613,0
12,2.7,Commissions for STs,913,75,0
13,2.8,National/State Commission for Women,34040,3091,0
14,2.9,Children Welfare Boards/Commission,3639,1035,0
15,2.10,Complaints Initiated Suo-moto by police,1220062,1197555,0
16,2.11,Any Others Written Complaints,1316188,165440,0
17,NaN,Total Complaints/FIRs,19416986,5687962,197905
18,NaN,Total FIRs Registered (Col.4+Col.5),NaN,NaN,5885867

In [535]:
table1.columns = table1.iloc[0]

In [536]:
table1 = table1.iloc[2:].copy()

In [537]:
table1.reset_index(
    drop=True,
    inplace=True
)

In [538]:
table1 = clean_column_names(table1)

In [539]:
table1.columns

Index(['sl', 'type_of_complaint', 'number_of_complaints',
       'number_of_firs_registered', 'number_of_online/efir_registered'],
      dtype='object', name=0)

In [540]:
table1 = table1[
    [
        'type_of_complaint',
        'number_of_complaints',
        'number_of_firs_registered',
        'number_of_online/efir_registered'
    ]
].copy()

In [541]:
table1.rename(columns={

    'number_of_complaints':
    'complaints_received',

    'number_of_firs_registered':
    'firs_registered',

    'number_of_online/efir_registered':
    'online_efirs'

}, inplace=True)

In [542]:
numeric_cols = [
    'complaints_received',
    'firs_registered',
    'online_efirs'
]

for col in numeric_cols:

    table1[col] = pd.to_numeric(
        table1[col],
        errors='coerce'
    )

In [543]:
table1['type_of_complaint'] = (

    table1['type_of_complaint'].str.lower().str.replace(' ', '_').str.replace('/', '_').str.replace('-', '_')

)

In [544]:
table1.dropna(
    subset=['type_of_complaint'],
    inplace=True
)

In [545]:
table1.reset_index(
    drop=True,
    inplace=True
)

In [546]:
table1

,type_of_complaint,complaints_received,firs_registered,online_efirs
0,oral_complaints,9171426.0,717242.0,0
1,narrated_to_o_c___sho,961973.0,645919.0,0
2,distress_call_over_phone_dial_100_etc,8209453.0,71323.0,0
3,written_complaints,10245560.0,4970720.0,197905
4,to_o_c___sho,5263134.0,3345313.0,0
5,to_sp_senior_officers,1356812.0,137758.0,0
6,electronic_form,926733.0,29571.0,197905
7,court_complaints,95958.0,89092.0,0
8,nhrc_&_shrc,21948.0,1177.0,0
9,commissions_for_scs,6133.0,613.0,0
10,commissions_for_sts,913.0,75.0,0
11,national_state_commission_for_women,34040.0,3091.0,0
12,children_welfare_boards_commission,3639.0,1035.0,0
13,complaints_initiated_suo_moto_by_police,1220062.0,1197555.0,0
14,any_others_written_complaints,1316188.0,165440.0,0
15,total_complaints_firs,19416986.0,5687962.0,197905
16,total_firs_registered_(col.4+col.5),NaN,NaN,5885867

In [548]:
table1.to_csv(
    "../cleaned data/fact_complaint_registration.csv",
    index=False
)

In [549]:
table2.head(10)

,Crimes under IPC/BNS and SLL - 2022-2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,S.No.,Year,Mid-Year Projected Population (in Lakhs),IPC/BNS Incidence,SLL Incidence,Total Incidence,IPC/BNS Crime Rate,SLL Crime Rate,Total Crime Rate,% of IPC/BNS Crimes to Total Cognizable Crimes
1,1,2022,13797.5,3561379,2263567,5824946,258.1,164.1,422.2,61.1
2,2,2023,13923.3,3763102,2478467,6241569,270.3,178,448.3,60.3
3,3,2024,14049.1,3544608,2341259,5885867,252.3,166.6,418.9,60.2

TypeError: 'DataFrame' object is not callable

In [551]:
table2.columns = table2.iloc[0]

In [552]:
table2 = table2.iloc[1:].copy()

In [553]:
table2.reset_index(
    drop=True,
    inplace=True
)

In [554]:
table2 = clean_column_names(table2)

In [555]:
table2.drop(
    columns=['s.no.'],
    inplace=True
)

In [556]:
table2.columns = (

    table2.columns

    .str.replace('/', '_')

    .str.replace('%', 'percent')

    .str.replace(' ', '_')

)

In [557]:
table2.columns

Index(['year', 'mid_year_projected_population_(in_lakhs)', 'ipc_bns_incidence',
       'sll_incidence', 'total_incidence', 'ipc_bns_crime_rate',
       'sll_crime_rate', 'total_crime_rate',
       'percent_of_ipc_bns_crimes_to_total_cognizable_crimes'],
      dtype='object', name=0)

In [558]:
for col in table2.columns:

    if col != 'year':

        table2[col] = pd.to_numeric(
            table2[col],
            errors='coerce'
        )

In [559]:
table2['year'] = (
    table2['year']
    .astype(int)
)

In [560]:
table2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   year                                                  3 non-null      int64
 1   mid_year_projected_population_(in_lakhs)              3 non-null      float64
 2   ipc_bns_incidence                                     3 non-null      int64
 3   sll_incidence                                         3 non-null      int64
 4   total_incidence                                       3 non-null      int64
 5   ipc_bns_crime_rate                                    3 non-null      float64
 6   sll_crime_rate                                        3 non-null      float64
 7   total_crime_rate                                      3 non-null      float64
 8   percent_of_ipc_bns_crimes_to_total_cognizable_crimes  3 non-null      float64
dtypes: float64(5), int64(4)
memory usage: 348.0 bytes

In [562]:
table2.to_csv(
    "../cleaned data/fact_national_crime_summary.csv",
    index=False
)